Megabit/Blazorise

Source/Extensions/Blazorise.Charts/Base/BaseChart.cs, Source/Extensions/Blazorise.Charts/ChartData.cs, Source/Extensions/Blazorise.Charts/JS.cs, Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js, Tests/Blazorise.Demo/Pages/Tests/ChartsPage.razor, docs/_docs/extensions/chart.md
It seems that one of the Blazor Json Serialization limitations is that it strictly limits properties to the declared `<T>` data types in `List<T>` and not looking at runtime subclasses of `T`.
This pull request works around that limitation.
For `ChartData<TItem>` by casting the `List<ChartDataset<TItem>> Datasets` to` List<object>` which happily serializes `TItem` properties and `TItem` subclass properties.
Unhappily, it does not honor `EmitDefaultValue = false` attribute instructions in this way. I investigated casting to specific ChartDataset subclasses however found that the codebase did not always honor the correct use of `ChartDataset` subclass for each graph type, so I was not sure if that was a design intention to accept it. (This can be revisited if you are OK for the PR to …
=> Enable chart specific options to be serialized

README.md, docs/_docs/start.md, docs/_docs/usage/bootstrap.md, docs/_docs/usage/bulma.md, docs/_docs/usage/material.md
With Blazor/Core Preview 8, the terms used to describe Server-side and Client-side Blazor changed to Blazor Server and Blazor WebAssembly, respectively. 
[ASP.NET Core and Blazor updates in .NET Core 3.0 Preview 8](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/)
[Introduction to Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0)
After Blazor Server officially launches this month, new interested users may be thrown off if the terminology is different here than in official documentation.
This change updates the Readme and docs to use those terms instead.
=> Rename Server-side and Client-side Blazor

Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js
If you made a change to any of the chart options after the initial render they were not getting applied. Data changes were.
Changing the lines in the update method to not include config fixed this.
=> Chart Options Not Updating

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Fixed up autocomplete show that the dropdown menu is only displayed when there is FilteredData available.
=> Fix so that Autocomplete dropdown doesn't show empty dropdown

Source/Blazorise.Bulma/TextEdit.razor, Source/Blazorise/TextEdit.razor, Source/Blazorise/TextEdit.razor.cs
Added `VisibleCharacters` attribute to the `TextEdit` component. It is used as an abstraction over `size` attribute on native `<input>` element
=> feat: added attribute VisibleCharacters to TextEdit

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridColumn.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridCommandColumn.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridClearFilterCommand.razor, Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor, Source/Extensions/Blazorise.DataGrid/_DataGridNewCommand.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs, Tests/Blazorise.Demo/Pages/Tests/DataGridPage.razor
- Renamed `AllowEdit` to `Editable`, `AllowSort` to `Sortable` and `AllowFilter` to `Filterable` on DataGrid
- Ability to handle the editing of cell values by `CellsEditableOnNewCommand` and `CellsEditableOnEditCommand`
- Ability to handle visibility of command buttons by `NewCommandAllowed`, `EditCommandAllowed`, etc.
=> feat: better handling of editing the DataGrid

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
The reason for bug was that `TextEdit` was working wrong in previous versions of Blazorise. After refactoring in 0.8.7 the behavior has changed but I didn't update Autocomplete.
=> fix: Autocomplete no longer works in 0.8.7

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Fixed bug where `SelectedValueChanged` wasn't called when `Autocomplete` clears the text.
#300
=> fix: call SelectedValueChanged when Autocomplete clears

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
=> fix: DataGrid RowRemoved called even if RowRemoving was canceled

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
#441 
`RowSaving` replaced with two new event handlers `RowInserting` and `RowUpdating`.
=> feat: added RowInserting and RowUpdating event handlers for DataGrid

.github/workflows/dotnetcore.yml, Source/Extensions/Blazorise.Sidebar/Sidebar.razor, Source/Extensions/Blazorise.Sidebar/SidebarData.cs
When using the Sidebar extension I wanted to use the dynamic approach because it seemed more flexible. Then I found out that items are collapsed by default. I ended up having to reimplement the logic from Sidebar.razor to add this option.
This commit adds exactly that option. The SidebarItemInfo has a new property which will expand it and all sub-items. The toggling still works no matter in which state the items start.
I think Blazorise is a fantastic library and I look forward to contributing more.
=> Sidebar items can be expanded by default when using the dynamic method

Source/Blazorise/Enums.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/ExtensionMethods.cs
Added `SortDirection.None` to enable custom sorting on `ReadData` event handler.
@ricardoromaobr Can you please confirm on your side this is working?
=> feat: added SortDirection.None for DataGrid

Source/Blazorise/Adapters/CloseActivatorAdapter.cs, Source/Blazorise/BarDropdownToggle.razor.cs, Source/Blazorise/DropdownToggle.razor.cs, Source/Blazorise/Enums.cs, Source/Blazorise/EventArguments.cs, Source/Blazorise/ICloseActivator.cs, Source/Blazorise/Modal.razor.cs, Source/Blazorise/ModalBackdrop.razor.cs, Source/Blazorise/wwwroot/blazorise.js
#549 
Added `CloseReason` enum to the modal `Closing` event which can be used for better control over stopping modal from closing.
=> feat: CloseReason for closable components like Modal, Dropdown, etc.

Source/Blazorise.Bootstrap/FileEdit.razor, Source/Blazorise.Bulma/FileEdit.razor, Source/Blazorise/Adapters/FileEditAdapter.cs, Source/Blazorise/EventArguments.cs, Source/Blazorise/FileEdit.razor, Source/Blazorise/FileEdit.razor.cs, Source/Blazorise/FileEntry.cs, Source/Blazorise/FileEntryStreamReader.cs, Source/Blazorise/IFileEntry.cs, Source/Blazorise/IJSRunner.cs, Source/Blazorise/JSRunner.cs, Source/Blazorise/RemoteFileEntryStreamReader.cs, Source/Blazorise/wwwroot/blazorise.js, Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor, docs/_data/navigation.yml, docs/_docs/components/file.md
#367 
This PR includes the changes to `FileEdit` component to allow the uploading of single or multiple files. It also includes the `Written` and `Progressed` events. Documentation page is also fully written.
All the work is based on the blog post from: https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/
=> feat: File upload

Source/Blazorise/EventArguments.cs, Source/Blazorise/FileEdit.razor.cs, Source/Blazorise/FileEntry.cs, Source/Blazorise/IFileEntry.cs, Source/Blazorise/IJSRunner.cs, Source/Blazorise/JSRunner.cs, Source/Blazorise/RemoteFileEntryStreamReader.cs, Source/Blazorise/wwwroot/blazorise.js, Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor, docs/_docs/components/file.md
#367 
Made some changes to the FileEdit upload process
- removed `tasked`  batches when read-writing the streams
- added new events `Started` and `Ended`
@iberisoft Can you test this PR before I merge? I cannot find any issue with the upload files sizes. The only issue I experience is slow upload on WebAssembly. On server-side project it works really fast.
=> file upload optimizations

Source/Blazorise.AntDesign/FieldBody.razor.cs, Source/Blazorise.AntDesign/FieldLabel.razor.cs, Source/Blazorise.Bootstrap/FieldBody.razor, Source/Blazorise.Bulma/FieldBody.razor, Source/Blazorise.Bulma/FieldBody.razor.cs, Source/Blazorise.Bulma/FieldLabel.razor.cs, Source/Blazorise/BaseInputComponent.razor.cs, Source/Blazorise/BaseSizableFieldComponent.cs, Source/Blazorise/Button.razor, Source/Blazorise/Button.razor.cs, Source/Blazorise/FieldBody.razor, Source/Blazorise/FieldBody.razor.cs, Source/Blazorise/FieldLabel.razor, Source/Blazorise/FieldLabel.razor.cs
#303 Remove the need for FieldBody for horizontal fields
**Copied from task:** After further investigation I found FieldBody has more benefits to stay. Instead I will refactor and remove BaseSizableComponent inheritance from all input components. The problem with defining column sizes on inputs directly is that it's generally not supported by all providers. Defining column sizes on button or check makes little sense. That should go to it's container. And it is precisely why FieldBody is used for.
Changed in this PR:
- removed inheritance if BaseSizableComponent from all input components
- replaced BaseSizableComponent with BaseSizableFieldComponent
- removed unused cascade parameters
- renamed some of the properties
=> refactor: removed ColumnSize from input components

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor, Source/Blazorise/Slider.razor
- Simple fix for `Slider` initial value ignoring `Max` on Bootstrap provider
- Add demo/test for `Slider` having large `Max`
Fixes #677
=> Fix slider initial value ignoring max

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
#605 Set DataColumn visibility to true/false but still allow popup/form to show field for editing
Added new property `Displayable` to data-grid column. It is used to show or hide column when grid is in display mode.
This PR is the implemented based on #615
=> feat: Add option to control column visibility in display mode

Source/Blazorise/EventHandlers.cs, Source/Blazorise/IValidation.cs, Source/Blazorise/Validation.razor.cs, Source/Blazorise/Validations.razor.cs
#583 ValidatedAll not called when ValidationMode.Auto
- `ValidatedAll` will now be called every time that all validations have passed
- Converted `ValidatedAll` to EventCallback
- Removed `ValidatedAllEventHandler` delegate
=> fix: ValidatedAll not called for Auto validations

Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs, Source/Blazorise.AntDesign/Styles/_card.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Since Ant Design has the concept of a `Cover` element for `Card` which is structured like the following:
```
<div class="ant-card-cover">
</div>
```
This class `.ant-card-cover` applies additional styling to the child elements.
These are missed in Blazorise.
Since Blazorise has `CardImage` as its equivalent (without the parent class) I have added the additional CSS directly to the `<img ... />` element that has the `.ant-card-cover` class.
Example of Ant Design CSS can be found [here.](https://github.com/ant-design/ant-design/blob/master/components/card/style/index.less#L132)
**Edit:**
Moved this CSS once I saw it is partially covered in the `ThemeGenerator` (still learning about Blazorise code structure!)
I think that the `Top` and `Bottom` `img` elements of the `Card` should follow Ant …
=> [AntDesign] fix: ant card image/cover

Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.AntDesign/AntDesignStyleProvider.cs, Source/Blazorise.AntDesign/Styles/_progress.scss, Source/Blazorise.AntDesign/Styles/blazorise.antdesign.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
There was an issue with the Ant Design progress bar background taking up too much vertical space:
I have fixed it to the following: 
**Edit:**
Additionally, I have also added better styling for the `ProgressBar` inner text on Ant Design.
Was:
Now:
However, since this is non-standard of Ant Design, I have put this styling in a new "Blazorise" specific class `.b-ant-progress-text`
=> [AntDesign] fix: progress bar

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Fixes issue in #627 as per @stsrki suggestion.
Changed demo project `DataGrid` page `Childrens` column to show as example.
=> fix: insert empty cell when DataGridColumn Filterable is False

Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.AntDesign/Config.cs, Source/Blazorise.AntDesign/Styles/_table.scss, Source/Blazorise.AntDesign/TableRowHeader.razor, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
One last Ant Design fix before **0.9.0** from me!
Ant Design does not seem to support `th` tags in the `tbody` element rows (`TableRowHeader` component).
It was looking like:
I have updated them to be `td` elements for Ant Design and created a custom CSS class for `bold`.
=> fix: Ant Desgin TableRowHeader

Tests/BasicTestApp.Client/Properties/launchSettings.json, Tests/BasicTestApp.Server/Properties/launchSettings.json, Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj, Tests/Blazorise.E2ETests/Properties/launchSettings.json, Tests/Blazorise.E2ETests/package.json
Tests were falling, and adding `"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",` to `launchSettings.json` helped.
=> fix: modified launchSettings.json and removed CodeCoverage reference

Source/Blazorise.Bootstrap/ModalContent.razor.cs
I found a bug in 0.9 where setting the ModalSize is missing the CSS class prefix for bootstrap.  This lead to getting `xl` not `modal-xl` when setting to ExtraLarge.
=> Fixing Modal Size CSS

Demos/Blazorise.Demo/Layouts/MainLayout.razor, Source/Blazorise.AntDesign/Styles/_layout.scss, Source/Blazorise.Bootstrap/Styles/_layout.scss, Source/Blazorise.Frolic/Styles/_layout.scss, Source/Blazorise.Material/Styles/_layout.scss, Source/Blazorise/ClassProvider.cs, Source/Blazorise/IClassProvider.cs, Source/Blazorise/Layout.razor.cs, Source/Blazorise/Styles/_layout.scss, Source/Blazorise/Theme.cs, Source/Blazorise/ThemeGenerator.cs, Source/Blazorise/wwwroot/blazorise.css, Source/Extensions/Blazorise.Sidebar/wwwroot/blazorise.sidebar.css
@stsrki until [this CSS issue](https://github.com/w3c/csswg-drafts/issues/865) is fixed, we cannot use `position: sticky` header **and** `overflow-x: hidden` on `Layout` elements. `overflow-x: hidden` is required for responsive to work well within the `Layout` elements.
Since responsiveness is more important.. I have made workaround for the `sticky` header by using `fixed` and calculating the offset of the `Sidebar` (in `_layout.scss`).
This isn't perfect for all situations and would be better if the offset calculation was tied to the `margin` of the `Sidebar` (but this requires more JSInterop knowledge than I have!)
**Also**, removed the now un-need `.b-body-layout`.. which is a win.
=> Additional fixes for responsive Layout

Demos/Blazorise.Demo/Layouts/MainLayout.razor, Source/Extensions/Blazorise.Sidebar/Sidebar.razor, Source/Extensions/Blazorise.Sidebar/Sidebar.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarBrand.razor, Source/Extensions/Blazorise.Sidebar/SidebarBrand.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarContent.razor, Source/Extensions/Blazorise.Sidebar/SidebarContent.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarFooter.razor, Source/Extensions/Blazorise.Sidebar/SidebarFooter.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarItem.razor, Source/Extensions/Blazorise.Sidebar/SidebarItem.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarLabel.razor, Source/Extensions/Blazorise.Sidebar/SidebarLabel.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarNavigation.razor, Source/Extensions/Blazorise.Sidebar/SidebarNavigation.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarSubItem.razor, Source/Extensions/Blazorise.Sidebar/SidebarSubItem.razor.cs
#795 Bug: SidebarLink with Clicked event behaves as an expandable node
Fixes include:
- Expandable icon does not show if there is no subitems
- Click and Toggled events converted to EventCallback
- All Sidebar components converted to partial classes
- Fixed demo Sidebar
=> Fixes for SidebarItem

Source/Blazorise.Material/Config.cs, Source/Blazorise.Material/MaterialThemeGenerator.cs, Source/Blazorise.Material/Switch.razor, Source/Blazorise/ComponentMapper.cs, Source/Blazorise/IComponentMapper.cs, Source/Blazorise/ThemeGenerator.cs
#799 Weird graphics for Switch in Material
Material Switch was missing `<span class="custom-control-track"></span>` from it's implementation.
=> fix: Missing Switch track color for Material provider

Source/Blazorise.AntDesign/CollapseHeader.razor, Source/Blazorise.AntDesign/Config.cs, Source/Blazorise/Collapse.razor, Source/Blazorise/Collapse.razor.cs, Source/Blazorise/CollapseBody.razor.cs, Source/Blazorise/CollapseHeader.razor.cs
In Ant Design, the `Header` of the `Collapse` is clickable ([for reference](https://ant.design/components/collapse/#components-collapse-demo-basic)).
So I have made some changes to allow the Ant Design `Header` to be clickable in Blazorise.
Addresses #820
=> fix: Make Ant Design collapse header clickable

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor, Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor, Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor
**Note**: I realised after that this requires PR #822 to work correctly for Ant Design
Issue was that Ant Design doesn't like the use of empty `FieldLabels`
Addresses #818
=> fix: Remove empty FieldLabels and replace with Offsets in demos

Source/Blazorise.AntDesign/Styles/_dropdown.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css, Source/Extensions/Blazorise.Components/Autocomplete.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
#824 Autocomplete not working in AntDesign
- Fixed Dropdown menu visibility
- Fixed input width within dropodown
=> fix: Autocomplete dropdown menu not showing AntDesign

Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.AntDesign/Styles/_form.scss, Source/Blazorise.AntDesign/Styles/_grid.scss, Source/Blazorise.AntDesign/Styles/_variables.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Added `Row`/`Column` guttering to Ant Design as a default that matches Bootstrap/Material.
Addresses #831
=> fix: Ant Design default row gutter to match Bootstrap

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor, Source/Blazorise.Bootstrap/Styles/_form.scss, Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
#664 Switch Component Cursor Property doesn't work
Fixed switch cursor for bootstrap provider
=> fix: Switch cursor not working

Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor, Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor.cs
#447 DetailRowTemplate - Remove empty td or change size
#622 [DataGrid] [Material] Issue with DetailRowTemplate in Editable DataGrid
Removed an empty table cells for detail row making it to fill entire row.
=> fix: remove empty cell for detail row

Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.Bootstrap/BootstrapClassProvider.cs, Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Blazorise.Frolic/FrolicClassProvider.cs, Source/Blazorise/BaseValidationResult.cs, Source/Blazorise/ClassProvider.cs, Source/Blazorise/EventArguments.cs, Source/Blazorise/EventHandlers.cs, Source/Blazorise/IClassProvider.cs, Source/Blazorise/IValidation.cs, Source/Blazorise/Providers/EmptyClassProvider.cs, Source/Blazorise/RadioGroup.razor, Source/Blazorise/Validation.razor.cs, Source/Blazorise/ValidationError.razor, Source/Blazorise/ValidationError.razor.cs, Source/Blazorise/ValidationNone.razor, Source/Blazorise/ValidationNone.razor.cs, Source/Blazorise/ValidationSuccess.razor, Source/Blazorise/ValidationSuccess.razor.cs, Source/Blazorise/ValidationSummary.razor, Source/Blazorise/ValidationSummary.razor.cs, Source/Blazorise/Validations.razor.cs, docs/_docs/components/validation.md, docs/_docs/helpers/enums.md
This PR covers two tickets: #658 and #851 
Changes include:
- new `ValidationSummary` component that acts as a placeholder for listing all error messages
- new `StatusChanged` event callback that is used to notify of latest validation status
- renamed BaseValidationSummary into BaseValidationResult
- removed unused delegates from EventHandlers.cs
- updated validation page in documentation
=> feat: validation summary

Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Blazorise/PaginationItem.razor, Source/Blazorise/PaginationItem.razor.cs, Source/Blazorise/PaginationLink.razor.cs
#669 
Active state from PaginationItem was cascaded to PaginationLink but it was missing a call to DirtyClass().
=> fix: bulma datagrid pagination links not active

Demos/Blazorise.Demo/Pages/Tests/ChartsPage.razor, Demos/Blazorise.Demo/Pages/Tests/LiveChartsPage.razor.cs, Source/Extensions/Blazorise.Charts/BaseChart.cs, Source/Extensions/Blazorise.Charts/JS.cs, Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js
#792 error with charts after redrawing
This PR adds additional APIs to handle the chart update.
- AddDatasetsAndUpdate()
- AddLabelsDatasetsAndUpdate()
The problem with separate calls to chart with Clear(), AddLabel(), AddDataset() and Update() is that chartjs for some reason will raise an exception sometimes before update is called. Since it is random I cannot find the true cause. So I introduce this new APIs that will merge several calls into one operation.
=> fix: new apis for updating chart

Source/Blazorise/Modal.razor.cs
#483 Scroll not working after NavigationManager navigation
The problem was that on navigation modal with dispose and because of that some class-names were left behind. Now the call to dispose of any class-names will always be called.
=> fix: modal not removing the classname from modal when navigation occured

Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor.cs
Content of detail row wasn't spanning entire width of the detail row for me without a command column being specified.  Reversing subtraction logic created the same effect when command column was specified.  Decided to remove it to resolve the issue.  
I'm probably doing something wrong and have never tried creating a pull request before so feel free to straighten me out and tell me what I should do :) and if it's better to ask on gitter or just open an issue that's cool just let me know.
=> Dev091 datagriddetail columnspan fix

Source/Blazorise/BaseTextInput.razor.cs, Source/Blazorise/IJSRunner.cs, Source/Blazorise/JSRunner.cs, Source/Blazorise/MemoEdit.razor.cs, Source/Blazorise/wwwroot/blazorise.js
#655 Memo cursor jumps to end when enclosed in a field and Text is bound
#733 TextEdit jump caret to the end of the text for every typed char, when ChangeTextOnKeyPress is true.
Fixes the bug with caret jumping to the end of input when `Text` is set to **two-way** binding and `Options.ChangeTextOnKeyPress` is set to true.
=> fix: TextEdit and MemoEdit caret jump

Source/Extensions/Blazorise.Charts/ChartOptions.cs
#961 ChartOptions : Scales object has typo in "Axe"
=> fix: renamed Chart Axe class into Axis

Source/Blazorise/Utils/Converters.cs, Tests/Blazorise.Tests/Utils/ConvertersTests.cs
Sorry @stsrki,
I tried to use my own convertor code for the chartjs, and I noticed that some things were wrong.
The problem was that Arrays and Lists were not correctly processed.
So the arrays yAxes and xAxes where passed to the javascript as:
``` js
{"barPercentage":0.899999976,"categoryPercentage":0.800000012,"barThickness":0,"maxBarThickness":0,"scales":{"xAxes":{"capacity":4,"count":1},"yAxes":{"capacity":4,"count":1}},"responsive":true,"maintainAspectRatio":true,"aspectRatio":2}
```
this has been fixed in this PR + I've aded some more tests for nested objects, simple-arrays, complex-arrays, simple-lists and complex-lists.
=> Fix Convertor.ToDictionary for Arrays and Lists

Source/Blazorise/Bar.razor.cs
@stsrki opening PR as a patch for `dev091`. 
I can change the target branch if thats not what you want.
Fixes #1026
=> fix: Server-Side pre-rendering issue with Bar calling JSInterop

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, docs/_docs/extensions/chart.md
A couple fixes for the following scenarios:
- New form isn't shown when the data is empty and the edit mode is set to Form
- The empty template and loading template both show when loading and empty
- Hide the pager when the data is empty or while loading data
- Fixed the scenario when manual data read is being used and a new item is added the view isn't refreshed respecting the sorting, filtering, and paging
- Fixed the scenario when manual data read is being used and an item is deleted on a page and the page becomes empty
=> Fixes for DataGrid manual data read behavior

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/PopupTitleContext.cs, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor.cs, docs/_docs/extensions/datagrid.md
- Add PopupTitleContext class
- Add TitleTemplate to _DataGridModal
- Add PopupTitleTemplate property to DataGrid
- Use PopupTitleTemplate for set TitleTemplate of _DataGridModal
- Create example of PopupTitleTemplate on DataGridPage
- Extend DataGrid documentation for PopupTitleTemplate
PR is made for feature proposal #918 
This PR also resolve a part of #1064
=>  DataGrid. Title property for modal dialog. 

Source/Blazorise.Bootstrap/ModalContent.razor.cs, Source/Blazorise/Enums.cs, Source/Blazorise/ModalContent.razor.cs, docs/_docs/helpers/sizes.md
#1065 Bootstrap ModalContent generating invalid class name
- Removed `ModalSize.Null` in favor of `ModalSize.Default`
- Updated docs
=> Fixed invalid classname for ModalContent size

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
#1043 Bar component : BarEnd is not pushed on right side if there's no BarStart Element in BarMenu
=> Fixed BarEnd positioning when BarStart is not defined

Demos/Blazorise.Demo.Bulma/wwwroot/index.html, Source/Blazorise.AntDesign/FileEdit.razor, Source/Blazorise.Bootstrap/FileEdit.razor, Source/Blazorise.Bulma/FileEdit.razor, Source/Blazorise.Bulma/Styles/_form.scss, Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css, Source/Blazorise/FileEdit.razor.cs
#952 Bootstrap FileEdit does not show filename(s) after browsing
- Fixed FileEdit for: Bootstrap, AntDesign, Bulma
- Fixed Bulma FileEdit not showing as fullwidth
- Update Bulma css to latest version
=> Fixed FileEdit not displaying selected filename

Source/Blazorise/ClassProvider.cs, Source/Blazorise/IClassProvider.cs, Source/Blazorise/Layout.razor, Source/Blazorise/Layout.razor.cs, Source/Blazorise/LayoutFooter.razor.cs, Source/Blazorise/Providers/EmptyClassProvider.cs, Source/Blazorise/Styles/_bar.scss, Source/Blazorise/Styles/_layout.scss, Source/Blazorise/wwwroot/blazorise.css, docs/_docs/components/bar.md, docs/_docs/components/layout.md, docs/_examples/layout/header-on-top-with-sider.html
More details can be found at #1089 
@stsrki I have added a `LoadingClass` to `Layout` to represent what you suggested on #1084.
This can be overridden with CSS for a spinner or progress bar, but I have also provided a default.
Let me know what you think, didn't want to spend too much time on that right now.
=> Layout Improvements

Source/Blazorise.AntDesign/Styles/_bar.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css, Source/Blazorise/Styles/_bar.scss, Source/Blazorise/wwwroot/blazorise.css
`.b-bar-menu` still had `height: calc(100% - var(--b-vertical-bar-brand-height, 64px));`
This was causing the Bar to break when you created it _without_ a `BarBrand`.
Noticed when further testing new layout changes for "header on top" setup.
Also fixed issue with AntDesign bar.
=> fix: Resolved Bar issue relating to recent Layout Improvements

Source/Extensions/Blazorise.TreeView/_TreeViewNode.razor
It's just one line of code, but it helped me to lower the initial loading time. By only loading the children if the root node is expanded.
=> Adding somekind of lazy loading to the tree view

Source/Blazorise/BaseTextInput.razor.cs, Source/Blazorise/BlazoriseOptions.cs, Source/Blazorise/MemoEdit.razor.cs, Source/Blazorise/Utils/ValueDelayer.cs, docs/_docs/components/memo.md, docs/_docs/components/text.md
#1053 TextEdit jump caret to the end of the text for every typed char, when ChangeTextOnKeyPress is true
- Added `DelayTextOnKeyPress` and `DelayTextOnKeyPressInterval` to global options
- Override of `DelayTextOnKeyPress` and `DelayTextOnKeyPressInterval` added to TextEdit and MemoEdit
- With the  `DelayTextOnKeyPress` enabled every value entered into text field will be slightly delayed
- Updated docs
=> Delay the text entered in TextEdit when ChangeTextOnKeyPress is true

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
#1203 In DataGrid DisplayFormat disappears when Editing Inline
=> Fixed display format of non editable field in datagrid inline mode

Source/Blazorise/FileEdit.razor.cs, Source/Blazorise/IJSRunner.cs, Source/Blazorise/JSRunner.cs, Source/Blazorise/wwwroot/blazorise.js, docs/_docs/components/file.md
#1177 Add Reset() method to FileEdit
- `FileEdit `will automatically reset after each upload if `AutoReset` is enabled
- Added new `Reset()` method for manual operation
=> Added Reset method to FileEdit

Source/Blazorise/Validation.razor.cs, Source/Blazorise/Validations.razor.cs
For scenarios with a dynamic set of validations, we want to ensure a validation is removed if it has been disposed, so the validation set doesn't keep checking for it, and holding on to it in memory.
This is taken from #1234 and moved to this dev092 branch as mentioned [here](https://github.com/stsrki/Blazorise/pull/1234#issuecomment-675088852)
@peterlentine
=> Remove a validation from the parent validation set when it is disposed

docs/_docs/components/tab.md
Wanted to disable a Tab and noticed the 'Disabled' and 'Clicked' attributes missing from the docs.
=> Added 'Disabled' and 'Clicked'-attributes to Tab.md docs

Source/Blazorise/Slider.razor
The slide currently doesn't update directly when it's dragged around by the mouse.
It's only updated when the drag stops / mouse button signals up.
To caputure mouse input directly, the `oninput` needs to be handled as well (see stackoverflow: [onchange event on input type=range is not triggering in firefox while dragging](https://stackoverflow.com/a/19067260/2132796)).
=> Update Slider value when dragged by mouse

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
Fix for https://github.com/stsrki/Blazorise/issues/1223 
DataGridColumn Displayable="false" shows column in DataGridEditMode.Inline edit mode
=> Fix for Displayable column in inline edit mode

Source/Blazorise/Validation.razor.cs, docs/_docs/components/validation.md
#1329 
Done:
- Added `StatusChanged` event to `Validation` component
- Fixes bug with model validation calling notification multiple times
Usage:
```cshtml
<Validation Validator="@ValidationRule.IsNotEmpty" @bind-Status="@nameStatus">
<Field Horizontal="true">
<FieldLabel ColumnSize="ColumnSize.Is2">
Full Name
@if ( nameStatus != ValidationStatus.Error )
{
<span style="color:red;">*</span>
}
</FieldLabel>
<FieldBody ColumnSize="ColumnSize.Is10">
<TextEdit Placeholder="First and last name">
<Feedback>
<ValidationError>Enter full name!</ValidationError>
</Feedback>
</TextEdit>
</FieldBody>
</Field>
</Validation>
```
=> Added StatusChanged event to Validation component

Source/Extensions/Blazorise.RichTextEdit/Blazorise.RichTextEdit.csproj, Source/Extensions/Blazorise.TreeView/Blazorise.TreeView.csproj
Fix nuget author names
Issue: [1280](https://github.com/stsrki/Blazorise/issues/1280)
=> fix 1280 - bad author names in nuget package

Source/Blazorise/Validation.razor.cs
resolve #1495 0.9.2 Breaking Change: Validation.Validate() now requires a parameter
=> Adds a public Validate() methods

Source/Extensions/Blazorise.RichTextEdit/Enums.cs, Source/Extensions/Blazorise.RichTextEdit/Providers/RichTextEditActionClassProvider.cs
One of the button actions was missing for creating [links](https://quilljs.com/docs/quickstart/)
=> RichTextEdit - Add missing link action

Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js
Resolve [1414](https://github.com/stsrki/Blazorise/issues/1414#issuecomment-732977799).
Did some quick testing of both the wasm as server hosted version of RTE and both seem to work fine with this fix.
=> RTE - Fix for issue 1414 - Server hosted gives js errors

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
fix #1558 DataGrid PageSize Item changed without reloading the datasource
=> DataGrid PageSize does not trigger refresh in manual mode

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor, docs/_docs/extensions/datagrid.md
- Implemented EmptyCellTemplate to allow customization of all cells that are null. Updated the docs and added an EmptyCellTemplate to Datagrid Demo.
- EmptyCellTemplate is only applied if DisplayTemplate is not defined for that column.
=> DataGrid: EmptyCellTemplate

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs
- fix #1362, #1568 
- Renamed CellAreEditable and moved the method into column.
- Used this method also at DataGridModal to get the same behavior for popup.
=> Fixed CellsEditableOn for popup edit mode.

Source/Blazorise.Bootstrap/Field.razor.cs
fix #1587 Cards within field are displaced since 0.9.2.3
=> Fixed issue with Field column size

Source/Blazorise/Styles/_variables.scss, Source/Blazorise/Styles/tooltip.scss, Source/Blazorise/Themes/Models/ThemeTooltipOptions.cs, Source/Blazorise/Themes/ThemeGenerator.cs, Source/Blazorise/wwwroot/blazorise.css
resolve #1172 Tooltip transparency not working
**Done:**
- Removed `BackgroundOpacity` from theme options
- Alpha value is now set through BackgroundColor
=> Better background color for tooltip opacity

docs/_docs/components/divider.md
The "Type" attribute is incorrectly used - "DividerType" is the correct attribute
=> Fix attribute documentation for Divider

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Moved paginationContext's events subscription from constructor into OnAfterRender to prevent them beeing triggered by the first SetParameters.
fix #1609
=> DataGrid: fix double ReadData

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/FilterContext.cs
@stsrki The Clear Filter bugfix.
There's a couple of things here.
The bug only happens when using the Filter Template. I noticed the Filter Template takes in a FilterContext from a DataColumn.FilterContext property. So on the Demo both the First Name and City Column Filters have this bug.
I don't know why there exists a Filter and a FilterContext property on the DataColumn but I'm sure there's a good reason...
- The FilterContext.TriggerFilterChange wasn't modifying the filter's current SearchValue with the new Value.
- On the demo itself, both the inputs weren't correctly bound to the value.
- I made the FilterTemplate take in the Filter property instead of the FilterContext property which seems to always have the correct updated value across the code.
=> Clear Filter Bug Fix: Filter Template usage

Source/Blazorise.Material/wwwroot/blazorise.material.js
Please change DateEdit Years and Month and enable selection.
I think that select years and months is very key feature.
I change JS for enable it by design.
I see this docs for [datepicker](http://daemonite.github.io/material/docs/4.1/material/pickers/)
=> Material DateEdit - Years and Month selectable

Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor, Source/Extensions/Blazorise.Snackbar/SnackbarOptions.cs, Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor, Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs, docs/_docs/extensions/snackbar.md
SnackbarStack selecting the notification life interval when calling the Push method.
Add IntervalBeforeClose to SnackbarInfo and SnackbarOptions;
Use SnackbarInfo.IntervalBeforeClose instead of SnackbarInfo.Interval in SnackbarStack.razor;
Rename SnackbarStack Interval to DefaultInterval;
Changed documentation for intervals.
=> SnackbarStack selecting the notification life interval when calling the Push method

Source/Blazorise.AntDesign/BarDropdownItem.razor, Source/Blazorise.AntDesign/BarLink.razor, Source/Blazorise.AntDesign/BreadcrumbLink.razor, Source/Blazorise.Bulma/BreadcrumbLink.razor, Source/Blazorise/Components/Bar/BarDropdownItem.razor, Source/Blazorise/Components/Bar/BarLink.razor, Source/Blazorise/Components/Breadcrumb/BreadcrumbLink.razor, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor, Tests/Blazorise.Tests/Components/BarLinkComponentTest.cs, Tests/Blazorise.Tests/TestServices/TestNavigationManager.cs
I've added a simple `Clicked` event firing.
As you can see I've had to add `TestNavigationManager` class to Tests. It was because the `Link` component has `NavigationManager` injected using `@Inject` and there wasn't any registered. My implementation of `TestNavigationManager` was based on Microsoft implementation in Blazor test. You can find it [here](https://github.com/dotnet/aspnetcore/blob/2588e246e5ca469603d3253225a5dcecda45a1cd/src/Components/WebAssembly/WebAssembly.Authentication/test/WebAssemblyAuthenticationServiceCollectionExtensionsTests.cs#L440).
=> BarLink clicked event fired

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor.cs
When RenderFragment is passed as a parameter and it is `null` it will raise an exception. This PR fixes it.
@David-Moreira I noticed it only on production 😅
=> Fix bug when ButtonRowTemplate is null

Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs, Source/Blazorise/wwwroot/blazorise.js, Tests/BasicTestApp.Client/NumericEditComponent.razor, Tests/Blazorise.E2ETests/NumericEditTest.cs
resolves #1737
With this feature now it is possible to write any valid number but once input loses focus it revalidate against Min and Max and then adjust the value.
It works good but the only problem with this solution is that `ValueChanged` will be called two times. This is something that can be fixed sometime in the future in case it is much of a problem.
=> NumericEdit Min and Max fix

Source/Blazorise/Components/Link/Link.razor.cs
fixes #1780 Preview4 to Preview8: Invalid URI: The hostname could not be parsed.
=> Add rule for mailto links to Link component

Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
fixes #1853 NumericEdit ValueChanged fires twice and sets value back to zero
=> Fix NumericEdit reset value when Min and Mix are not used

Source/Blazorise/Base/BaseInputComponent.razor.cs, Source/Blazorise/Components/Validation/ValidationRule.cs, Source/Extensions/Blazorise.Components/Autocomplete.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs, docs/_docs/extensions/autocomplete.md
resolves #1350 AutoComplete validation works off text rather than value
Usage:
```cshtml
<Autocomplete TItem="MySelectModel"
Data="@myDdlData"
TextField="@((item)=>item.MyTextField)"
ValueField="@((item)=>item.MyTextField)"
SelectedValue="@selectedSearchValue"
SelectedValueChanged="@MySearchHandler"
Placeholder="Search..." Filter="AutocompleteFilter.StartsWith"
Validator="IsValidValue">
@code{
void IsValidValue( ValidatorEventArgs e )
{
Console.WriteLine( e.Value );
e.Status = !string.IsNullOrEmpty( e.Value?.ToString() ) && myDdlData.Any( x => x.MyTextField == e.Value.ToString() )
? ValidationStatus.Success
: ValidationStatus.Error;
if ( e.Status == ValidationStatus.Error )
{
e.ErrorText = "ERROR";
}
else
{
e.ErrorText = "OK";
}
}
}
```
=> Add validation to Autocomplete component

Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs
=> RichTextEdit - Catch exception when try to destroy editor in Server side blazor after user closes window.

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/EventArguments.cs, Source/Extensions/Blazorise.DataGrid/PaginationContext.cs
Hello @stsrki 
Here's the changes I have suggested. Including the idea of a Cancellation token to be able to issue cancellations.
You can test it on the DataGrid Demo Page it now has a random delay on ReadData (when Large Data is selected). If you switch between pages or page sizes, it should always only display the latest operation whereas before, it would update the UI with all the queued operations.
Just let me know if you agree with this idea or not.
=> Datagrid: Introduced async / await on missing events. Introduced a Cancellation Token to issue a cancellation on page changed / page size changed

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
@stsrki 
Like we talked. There were two events that we noticed that weren't being unsubscribed on DataGrid. 
I wasn't sure if these were gonna hang on memory or not. But better be safe then sorry. :)
=> DataGrid: Just making sure page handler events are unsubscribed.

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridMultiSelectAll.razor.cs
You're probably getting tired of my PRs right about now... xD
Ok so the indeterminate flag was wrong when changing to an empty page just like you had tested it.
When fixing that, also the check all wasn't correctly updating with the currently DisplayData that was selected when switching back and forth between already visited pages.
Also made the logic a bit clearer by removing the expression body in favor of a simple method.
DisplayData was changed from Protected to Internal as I needed to access this information, that should be okay, but just tell me otherwise.
=> Datagrid multi selection fixes

Source/Blazorise/Components/Validation/Handlers/DataAnnotationValidationHandler.cs, Source/Blazorise/Components/Validation/Handlers/PatternValidationHandler.cs, Source/Blazorise/Components/Validation/Handlers/ValidatorValidationHandler.cs, Source/Blazorise/Components/Validation/Validation.razor.cs
Validation no longer remembers the last received value. This was problematic because in some cases the validation would not be raised even though the input real value has changed.
=> Optimized Validation to always use new validation value

Source/Blazorise/Base/BaseAfterRenderComponent.cs
So this wasn't easy to reproduce... But I had it happen.
You basically have to switch between pages/components really fast and it may happen.
I could reproduce it often when clicking these pages on the Demo: 
Nested Forms / Nested Validations and Misc really fast, like within a second.
I could then faithfully reproduce by adding this code:
`            ExecuteAfterRender( () => Task.Delay( 2500 ) );`
```
protected override async Task OnAfterRenderAsync( bool firstRender )
{
Rendered = true;
ExecuteAfterRender( () => Task.Delay( 2500 ) );
if ( executeAfterRenderQueue?.Count > 0 )
{
while ( executeAfterRenderQueue.Count > 0 )
{
var action = executeAfterRenderQueue.Dequeue();
await action();
}
}
await base.OnAfterRenderAsync( firstRender );
}
```
**So Dispose runs while AfterRender is still …
=> BaseAfterRenderComponent Null Bug Fix

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Closes #1913 
I was thinking if it made sense to show when loading, maybe the user could have a button to cancel the ongoing loading... but I left that as it was for now.
=> Datagrid: Is pager visible when button row is on and grid is Empty with an EmptyTemplate set

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/wwwroot/blazorise.datagrid.css, Source/Extensions/Blazorise.DataGrid/wwwroot/blazorise.datagrid.js
Closes #1928 
So here I was thinking the fix would be as easy as to preventPropagation on the resizable click... Oh damn, I was so wrong...
Well that did solve most of it, but resizing and leaving the mouse on top of the adjacent parent column, would still trigger the column mouseup event and corresponding click.
As soon as mouseup event is triggered there's no way to stop the click event. So I've had to try a few things to avoid triggering the mouseup event when resizing on top of the column, 
- I tried setting the pointer-Events to none, which actually worked, but then the mouse would loose the resize look... no good.
- There was also a way to wrap the column itself in a div and stop the click from propagating below, but that would be changing the table's HTML, which could eventually …
=> Datagrid Resize : Ignore clicks from resizer triggering sort or other click events.

Source/Extensions/Blazorise.DataGrid/_DataGridMultiSelectAll.razor.cs
Closes #1947 
I also noticed while testing, that clicking Delete triggers the RowClick, which means it will change SelectedRow / SelectedRows... This should only potentially be a problem with static data. But so far I haven't seen complaints about this which is strange. Not sure if we sould look at this in the future?
Personally, I just unselect SelectedRow myself when doing certain operations on the DataGrid. Since I use Grids that depend on the SelectedRow of other Grids.
=> DataGrid: MultiSelectAll: BugFix When only one row, not unchecking the multi select all checkbox

Source/Blazorise/Utilities/IDGenerator.cs, docs/_docs/meta/releases.md
The use of `string.Create` reduces the overhead of copying character buffers around, and eliminates the need for thread-local storage.
=> Optimize the IdGenerator class.

Source/Extensions/Blazorise.DataGrid/wwwroot/blazorise.datagrid.js
Closes #2008 
this check seemed to be enough
```
if (table !== null) {
cols = table.querySelectorAll('tr:first-child > th');
}
```
but I added whenever we're accessing the table, just in case.
Also removed 
`cols.forEach(x => x.classList.add('b-datagrid-resizing'));`
`cols.forEach(x => x.classList.remove('b-datagrid-resizing'));`
I have no idea why we had those in. Maybe commited by mistake.
Retested BS/Ant/Bulma/Material.
By the way have you noticed this on Ant? I don't really know the provider, but does not seem normal to me, for a dropdown to not show the selected value until clicked. Happens on other places on the demo with dropdowns.
=> Datagrid : Resizable : Fix js trying to access inexisting element when Datagrid has already been disposed.

Source/Extensions/Blazorise.Sidebar/SidebarLink.razor, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor.cs
fixes #2066 SideBarNavigation doesn't display drop down arrow with upgrade of Blazorise.Bootstrap and Blazorise.Icons.FontAwesome.
=> Fix Sidebar missing collapse icons

Source/Blazorise/Base/BaseTypographyComponent.cs
resolves #2155 Typography components should not default to the text-align left
=> Default typography TextAlignment set to none

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs, Source/Extensions/Blazorise.DataGrid/Delegates.cs, Source/Extensions/Blazorise.DataGrid/FilterContext.cs, Source/Extensions/Blazorise.DataGrid/Models/DataGridColumnInfo.cs, docs/_docs/extensions/datagrid.md
resolves #1966 Multisearch in the same column
resolves #1978 Datagrid: Filter method by column // Enhancing Filter
I have added `CustomFilter` function on the DataGridColumn that can be used to override the internal filter method on per-column basis. Also, I have refactored the existing `SearchValue` from the `string` into an `object` so that it can accept any object type that later is used in the `CustomFilter` function. The downside is that it is a breaking change but I think it is not much of a problem since users only need to add `?.ToString()` to the existing SearchValue usages.
@David-Moreira What do you think? Do you have any ideas for improvements?
=> Adds CustomFilter function on the DataGridColumn

Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor, Source/Blazorise/Components/Tooltip/Tooltip.razor.cs, Source/Blazorise/Enums/TooltipTrigger.cs, Source/Blazorise/wwwroot/blazorise.js, docs/_docs/components/tooltip.md, docs/_docs/helpers/enums.md
resolves #1313 Tooltip on focus
=> Add Trigger option on Tooltip component

Source/Blazorise/Base/BaseInputComponent.razor.cs
resolves #1823 TextEdit FocusAsync "Event is already tracked" exception
=> Add Task.Yield workaround for FocusAsync bug

Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Hello, I think I found a small bug in Bulma theme generator. Bulma alerts are styled like this `.notification.is-primary` and not like this `.notification-primary`. So the styles inside ThemeAlertOptions where not applied to the Alert component. Now it works.
=> Bulma GenerateAlertVariantStyles fix

Demos/Blazorise.Demo/Pages/Tests/ProgressBarsPage.razor, Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.AntDesign/AntDesignStyleProvider.cs, Source/Blazorise.AntDesign/Progress.razor, Source/Blazorise.AntDesign/Styles/_mixins.scss, Source/Blazorise.AntDesign/Styles/_progress.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css, Source/Blazorise.Bootstrap/BootstrapClassProvider.cs, Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Blazorise.Bulma/BulmaStyleProvider.cs, Source/Blazorise.Bulma/Config.cs, Source/Blazorise.Bulma/Progress.razor, Source/Blazorise.Bulma/ProgressBar.razor, Source/Blazorise.Bulma/Styles/_mixins.scss, Source/Blazorise.Bulma/Styles/_progress.scss, Source/Blazorise.Bulma/Styles/_variables.scss, Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css, Source/Blazorise/Components/Progress/Progress.razor, Source/Blazorise/Components/Progress/Progress.razor.cs, Source/Blazorise/Components/Progress/ProgressBar.razor, Source/Blazorise/Components/Progress/ProgressBar.razor.cs, Source/Blazorise/Interfaces/IClassProvider.cs, Source/Blazorise/Providers/ClassProvider.cs, Source/Blazorise/Providers/EmptyClassProvider.cs, Source/Blazorise/States/ProgressState.cs, docs/_docs/components/progress.md, docs/_posts/2021-03-24-release-notes-094.md
resolves #1622 Simplify usage of progress component
**Done**
- Progress can now be used without ProgressBar
- Background replaced with Color
- Fixed Bulma and AntDesign
- Added support for Bulma multiple value bars
- Update demo and docs
=> Simplify usage of progress component

Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs, Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs, Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Hi, in the latest preview of Blazorise there is a small bug, caused by the addition of flatpicker styles in `ThemeGenerator`. When there is no Primary color defined in `Theme.ColorOptions` an exception is thrown.
This PR fixes this problem by checking if `theme.ColorOptions?.Primary` is null or empty before trying to apply the theme styles.
=> GenerateInputStyles fix

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
fixed #2413 DataGrid inline edit mode forgets text alignment settings
=> Fix DataGrid cell text alignment

Source/Extensions/Blazorise.Charts/ChartData.cs
fixes #2395 Line charts throw error if dateset contains NaN data value
=> Rule for NaN json serializer

Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Blazorise.Bulma/BulmaStyleProvider.cs
To be able to derive custom provider from existing Bulma provider.
=> Make Bulma provider classes public

Source/Blazorise/Base/BaseAfterRenderComponent.cs, Source/Blazorise/Base/BaseComponent.cs, Source/Extensions/Blazorise.DataGrid/BaseDataGridComponent.cs
Hello, all Blazorise base components are using `Blazorise` namespace except BaseAfterRenderComponent which uses `Blazorise.Base`. So, just a small refactor for consistency.
=> move BaseAfterRenderComponent to Blazorise namespace

Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
fixes #2393 DataGrid Button row disappears on small screens
=> ButtonRow incorrect mediaquery breakpoint

Source/Extensions/Blazorise.Charts/ChartData.cs
resolves #1611 ChartJS (LineChart)Dataset: the ability to add series (Datasets) that are initially not displayed (hidden)
=> Add Hidden flag on chart dataset

Source/Blazorise.Bootstrap/NumericEdit.razor, Source/Blazorise/BlazoriseOptions.cs, Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridNumericColumn.cs, Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor, Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor, Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridCellEditValidation.razor, docs/_docs/components/numeric.md
resolves #2316 NumericEdit cannot disable numeric stepping from keyboard up/down
- adds `EnableStep` parameter
- renames `ShowSpinButtons` into `ShowStepButtons`
=> Adds EnableStep parameter on NumericEdit

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
fixes #2413 DataGrid inline edit mode forgets text alignment settings
=> Fix missing TableRow on DataGrid inline edit

Source/Blazorise.Bootstrap/BarDropdownMenu.razor, Source/Blazorise.Bootstrap/Config.cs, Source/Blazorise/wwwroot/blazorise.js
The horizontal menu was wrongly placed inside of empty div and it would break the Bootstrap structure.
I also make the closing of closable components only with the left mouse button.
=> Horizontal Dropdown fix

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Fixes tiny bug introduced in #2558
- Fixed Wrong boolean case on MultiSelect Column Filter
=> Fixed Wrong boolean case on MultiSelect Column Filter

Source/Blazorise/Components/Bar/Bar.razor.cs, Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs, Source/Blazorise/Components/Button/Button.cs, Source/Blazorise/Components/DatePicker/DatePicker.razor.cs, Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs, Source/Blazorise/Components/FileEdit/FileEdit.razor.cs, Source/Blazorise/Components/Modal/Modal.razor.cs, Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs, Source/Blazorise/Components/TextEdit/TextEdit.razor.cs, Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
to avoid the catch and re-throw when !task.IsCanceled
so we only swallow  when ( task.IsCanceled )
=> Use catch when

Source/Blazorise.AntDesign/Styles/_table.scss, Source/Blazorise.AntDesign/Table.razor, Source/Blazorise.AntDesign/Table.razor.cs, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Fixes #2621 
Certainly you were trying to get the native's AntDesign fixed header to work. 
https://ant.design/components/table/#components-table-demo-fixed-header
Problem is they separate **Header** From **Body** on FixedHeader feature, unlike us. And I believe we would need to slightly redesign our table to be able to have a collection of TableHeaderRows vs TableBodyRows, so we could do the native implementation. 
This PR should serve as a workaround to get it working for the time being.
=> AntDesign - Table Fixed Header Fix

Source/Blazorise/wwwroot/blazorise.js
#2622 Bugfix | ResizeHandler not being called on FixedHeader Init
=> #2622 Bugfix | ResizeHandler not being called on FixedHeader Init

Blazorise.sln, Source/Blazorise/Extensions/ArrayExtensions.cs, Tests/Blazorise.Benchmark/Blazorise.Benchmark.csproj, Tests/Blazorise.Benchmark/Program.cs, Tests/Blazorise.Tests/Extensions/ArrayExtensions.cs
Added Benchmark project with 
https://benchmarkdotnet.org/articles/guides/getting-started.html
so we can easily do some simple benchmarking.
Since we walked about `SequenceEquals` vs the Blazorise `AreEqual`, I compared them.
**Results (Mean is what matters most as it's the metric you can look at for performance, in nanoseconds here):**
After doing some unit tests for `AreEqual`, I noticed `SequenceEquals` does not handle nulls.
Refactored `AreEqual` to handle the nulls and use `SequenceEquals` internally for the comparision behind the scenes.
**Results (Mean is what matters most as it's the metric you can look at for performance, in nanoseconds here):**
**Legend:**
=> Benchmark project | ArrayExtensions AreEqual refactor

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, docs/assets/css/main.scss
Closes #2658
Tested the grid's null start with main variants.
```
<DataGrid TItem="Animal"></DataGrid>
<DataGrid TItem="Animal" Virtualize="true"></DataGrid>
<DataGrid TItem="Animal" ReadData="@((x) => null)"></DataGrid>
<DataGrid TItem="Animal" Virtualize="true" ReadData="@((x) => null)"></DataGrid>
```
=> Datagrid: BugFix : When data is null on init, set internal viewdata to empty list

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Unfortunately 
Causes a bug... since setter value and data will pretty much always be equal. We would need to keep a copy of the old data and compare... I'm not sure it would be worth it at all... we could still take a look in the future.
Fixes #2675
=> Datagrid: Revert "Dirty only when data changed"

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Fixes #2676
Since Datagrid on 0.9.4 does not refresh every single time due to alot of internal parameter passage between components being removed. 
There should be a way for a child to notify the parent that there have been changes that may affect other children. 
(Like, in the case of this issue, recalculating the style of other rows, when a row is clicked/selected)
=> DataGrid : Internally have datagrid's child component's notify of a statechanged

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Reason why we didn't catch this on testing, is because our datagrid demo has a lot of parameters and still calls StateHasChanged. I had a gut feeling we should call it when we were reworking the Datagrid's internal params... but it was working... O.O
So, to reproduce need a minimal Datagrid.
Closes #2722
Code from Dashboard, I had sitting here used to reproduce:
```
@page "/"
<Heading Size="HeadingSize.Is1" Margin="Margin.Is3.FromBottom">Blazorise</Heading>
<Button Clicked="AddItem" Color="Color.Primary">Add Item</Button>
<Heading>Blazorise DataGrid</Heading>
<DataGrid TItem="Animal" Data="@forecasts" Editable="true" EditMode="DataGridEditMode.Popup" Responsive="true" PageSize="100" Sortable="true">
<DataGridCommandColumn TItem="Animal" />
<DataGridColumn Editable="true" …
```
=> Make sure methods that mutate the Datagrid state call StateHasChanged.

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Fixes #2734 
- Made Selection Changed only be called on setter. No idea why it was calling on every OnAfterRender... Retested and everything okay.
- Fixed the bug found on #2734 | When SelectionModeChanged is triggered internally, and SelectionMode is Multiple and there's a SelectedRow, make sure the SelectedRow is in the Data collection before adding it to the SelectedRows collection.
=> Selection Changed Bugfix

Source/Blazorise.AntDesign/Styles/_extensions.scss, Source/Blazorise.AntDesign/Styles/blazorise.antdesign.scss, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css, Source/Blazorise.Bootstrap/Styles/_extensions.scss, Source/Blazorise.Bootstrap/Styles/blazorise.bootstrap.scss, Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css, Source/Blazorise.Material/Styles/_extensions.scss, Source/Blazorise.Material/Styles/blazorise.material.scss, Source/Blazorise.Material/wwwroot/blazorise.material.css
fixes #2752 Bootstrap+Material-Demo: Left-Algined Snackbar hidden behind sidebar-menu
=> Use native z-index for notifications

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor, Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs, Source/Extensions/Blazorise.DataGrid/Utils/RecursiveObjectActivator.cs, Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridCellEditValidation.razor.cs
fixes #2785 
In this PR I have used `FormatterServices.GetUninitializedObject` instead of `Activator.CreateInstance`. The reason is that FormatterServices creates an empty object without the need for any parameterless constructor. And an empty object is what we want to have.
Source: https://stackoverflow.com/questions/390578/creating-instance-of-type-without-default-constructor-in-c-sharp-using-reflectio
Note: Test data in the demo should be removed once we make it work!
@David-Moreira Now the problem is in `FunctionCompiler.CreateValidationExpressionGetter`. When an access field is null it cannot generate member access. Can you also have a look?
=> DataGrid initializer fix

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
Closes #2777
Like we've talked, the Popup / Form / Edit do not have the exact same logic to display the validation error messages.
We've decided to give freedom to the developer, meaning that even if the Validation status isn't invalid, but there are error messages, they will display across all modes. This allows for the developer to set error messages at different stages.
Once ShowValidationsSummary is set to true, we keep the ValidationSummary hidden, because it has to run the constructor and listen to the Validator changes (`validationsStatusChangedEventHandler`). 
The **flag** to display the Validation Errors Summary is either:
- Validator has invalid validation status (which means there may be validator error messages) or
- there are error messages set at DataGrid level.
=> DataGrid : Show Validation Errors | Same Logic on Popup / Form / Edit

Source/Blazorise.Bootstrap/Styles/_buttons.scss, Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Closes #2795
Setting opacity to 1 is a good enough fix maintaining the original selected color for active+disabled buttons.
**Only happened on bootstrap:**
**Does not happen on:**
Material:
Bulma:
Ant:
**Code used to test:**
```
<RadioGroup Size="Size.None" TValue="SubType" @bind-CheckedValue="@SubTypeValue" Buttons="true"  >
<Radio @bind-Disabled="disabled" TValue="SubType" Value="@SubTypeValue1"  >Тип1</Radio>
<Radio @bind-Disabled="disabled" TValue="SubType" Value="@SubTypeValue2">Тип2</Radio>
</RadioGroup>
<RadioGroup Size="Size.None" TValue="SubType" @bind-CheckedValue="@SubTypeValue" Buttons="false">
<Radio @bind-Disabled="disabled" TValue="SubType" Value="@SubTypeValue1" >Тип1</Radio>
<Radio @bind-Disabled="disabled" TValue="SubType" Value="@SubTypeValue2">Тип2</Radio> …
```
=> RadioButtons on Bootstrap, set opacity to 1 when active + disabled

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Fixes #2800 
When data provided is null + Dirty Filter being set(Pager calls TotalItems Getter) + statehaschanged call on the Filtering method caused infinite loop.
Fixed Dirty Filter to be reset also when the data is null.
Code used to reproduce bug & test:
```
<DataGrid ElementId="ColoniesGrid-DataGrid-0" TItem="Employee" Data="@colonies" Striped="true" Bordered="true" Editable="true"ShowPager="true" Narrow="true" Resizable="true" ResizeMode="TableResizeMode.Columns"  RowSelectable="@(v => false)">
<DataGridColumn ElementId="ColoniesGrid-DataGridColumn-0" TItem="Employee" Field="FirstName" Caption="FirstName" />
</DataGrid>
@code {
public class Employee
{
public int Id { get; set; }
public string FirstName { get; set; }
}
private IEnumerable<Employee> colonies;
}
```
=> Fixes Dirty Filter not being reset upon null data use case

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Fixes #2809 
Removes `DataGridColumn` from ParentDataGrid if disposed.
It is of note that the `DataGridColumn` component was being disposed asynchronously, meaning that when invoking the regular Dispose (which was invoked from base component), the flag disposing was set to false, and not running the correct disposal of the component.
I personally have no idea as to the criteria of .NET invoking async or sync disposal, but we should keep this current quirk of our disposal proccess in mind going forward.
**Code used to reproduce & test:**
```
<DataGrid ElementId="ColoniesGrid-DataGrid-0" TItem="Employee" Data="@colonies" Striped="true" Bordered="true" Editable="true" ShowPager="true" Narrow="true" Resizable="true" ResizeMode="TableResizeMode.Columns" RowSelectable="@(v => false)"> …
```
=> Removes DataGridColumn from ParentDataGrid if disposed.

Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor
Fixes #2860
Click was actually being called twice on row.
On chrome it would call once with Detail = 1 that is handled as a single click.
The second one would be called with Detail = 0, which would have no effect.
On firefox both were called as Detail = 1 that would provoke a state reset.
Added a preventDefault to the outter container preventing a two clicks trigger.
=> DataGrid : MultiSelect Fix Click being called twice.

Demos/Blazorise.Demo/Pages/Dashboard.razor, Demos/Blazorise.Demo/Pages/Tests/RichTextEditPage.razor, Demos/Blazorise.Demo/Pages/Tests/VerticalAlignPage.razor, Source/Blazorise.AntDesign/BarDropdownItem.razor, Source/Blazorise.AntDesign/BarLink.razor, Source/Blazorise.AntDesign/BreadcrumbLink.razor, Source/Blazorise.Bulma/BreadcrumbLink.razor, Source/Blazorise/Components/Bar/BarDropdownItem.razor, Source/Blazorise/Components/Bar/BarLink.razor, Source/Blazorise/Components/Breadcrumb/BreadcrumbLink.razor, Source/Blazorise/Components/Link/Anchor.razor, Source/Blazorise/Components/Link/Anchor.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor
resolves #2875 Rename Link component
Instead of renaming the Link component, I have decided to leave it in hope that Microsoft will one day fix the issue with their razor engine.
So I have added a new Anchor component that is basically just inherited from Link.
=> Anchor component that inherits from Link

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/_DataGridNewCommand.razor.cs
Fixes #2930
So with some performance improvements we had done in 0.9.4, we stopped passing most inner datagrid's components parameters through regular `Parameter` usage, and changed to the `CascadingParameter` Datagrid.
Reason why this specific component no longer knows how to refresh itself, is because, in the previous release, it was always being re-rendered due to the regular `Parameter` usage method, particulary the `Eventcallback New`. With this removal, it no longer knows it should refresh.
This behaviour was re-introduced fixing the reported issue.
However we should take a look at changing the `CascadingValue` `IsFixed` of the Datagrid to false, so we can notificate the inner components of the parent's changes... I attempted this as an alternate solution to fix this issue and it …
=> Reintroduce New Parameter to _BaseDataGridNewCommand tricking it into refreshing itself.

Source/Extensions/Blazorise.Charts/JS.cs
fixes #2920 Mixed Chart without Line fill on chart redraw
ChartJS have some weird data object usages so we need to box it and then unbox it. This will trick the serializer to properly pass data to JS.
=> Fix Chart data serialization

Build/Blazorise.props
resolves #2944 Support for .NET 6 RC1
=> Update Blazorise to use .Net 6 RC1

Demos/Blazorise.Demo/Pages/Tests/ButtonsPage.razor, Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.Bootstrap/BootstrapClassProvider.cs, Source/Blazorise.Bootstrap/Config.cs, Source/Blazorise.Bootstrap/DropdownToggle.razor, Source/Blazorise.Bootstrap/Styles/_dropdown.scss, Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css, Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs, Source/Blazorise.Bootstrap5/DropdownToggle.razor, Source/Blazorise.Bootstrap5/Styles/_dropdown.scss, Source/Blazorise.Bootstrap5/wwwroot/blazorise.bootstrap5.css, Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Blazorise.Material/Styles/_dropdown.scss, Source/Blazorise.Material/wwwroot/blazorise.material.css, Source/Blazorise/Components/Dropdown/Dropdown.razor.cs, Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs, Source/Blazorise/Interfaces/IClassProvider.cs, Source/Blazorise/Providers/ClassProvider.cs, Source/Blazorise/Providers/EmptyClassProvider.cs
This PR adds several improvements
- Places sub-Dropdown on the same level as sibling DropdownItem
- Custom CSS to adjust submenus next to the toggle button
- No need for `Direction="Direction.Right"`
I probably need to remove `.dropdown-submenu` but I will leave it until we settle for the final version.
Example
```cshtml
<Dropdown>
<DropdownToggle Color="Color.Primary">Level 1</DropdownToggle>
<DropdownMenu>
<DropdownItem>Item 1.1</DropdownItem>
<Dropdown Direction="Direction.Right">
<DropdownToggle>Level 2</DropdownToggle>
<DropdownMenu>
<DropdownItem>Item 2.1</DropdownItem>
<DropdownItem>Item 2.2</DropdownItem>
<Dropdown Direction="Direction.Right">
<DropdownToggle>Level 3</DropdownToggle>
<DropdownMenu>
<DropdownItem>Item 3.1</DropdownItem>
<DropdownItem>Item 3.2</DropdownItem> …
```
=> Diferent structure for dropdown submenus

Documentation/Blazorise.Docs/Components/DocsAttributes.razor, Documentation/Blazorise.Docs/Components/DocsAttributesItem.razor, Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/Code/ModalBindingExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/Code/ModalClosingExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/Examples/ModalBindingExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/Examples/ModalClosingExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/ModalPage.razor, Documentation/Blazorise.Docs/Pages/News/2021-10-17-release-notes-095.razor, Source/Blazorise.AntDesign/ModalContent.razor, Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.js, Source/Blazorise.Bootstrap/Modal.razor, Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js, Source/Blazorise.Bootstrap5/Modal.razor, Source/Blazorise.Bootstrap5/wwwroot/blazorise.bootstrap5.js, Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js, Source/Blazorise.Material/wwwroot/blazorise.material.js, Source/Blazorise/Components/MessageAlert/MessageAlert.razor.cs, Source/Blazorise/Components/Modal/Modal.razor.cs, Source/Blazorise/EventArguments/ModalOpeningEventArgs.cs
closes #2810 Modal Closing is an Action instead of an EventCallback
closes #1359 Modal - Show event
I have refactored the `Visible` parameter and `Closing` event. Instead of doing all the logic in the `Visible` setter, I have moved it to the `SetParametersAsync` lifecycle.
- The benefit of this is that the `Closing` event can now be properly awaited.
- The disadvantage is that `Visible` is used only as a hint for us that the parameter was received by the Blazot lifecycle. It should never be used directly as that would leave it in a bad state, eg. `modal.Visible = true`.
This will also come in handy for #1359
=> Refactor Modal Visible parameter and state management

Source/Blazorise/wwwroot/blazorise.js
fixes #2975 Empty Tooltip should not show
=> Don't show empty tooltips

Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs, Source/Blazorise/wwwroot/blazorise.js
resolves #2876 Numeric value does not handle values too low or too high for type TValue
This PR tries to resolve the problem when we type a numeric value that is larger or smaller than the TValue can hold, eg. for `int` max value is 2147483647. The problem is that we handle numeric validations in JS and even if it passes, it will fail on the C# part once we try to parse it. Thing is, we shouldn't be able to write anything above max or min.
My approach is to handle the min and max of the actual type in JS. And if it fails it will prevent the input and replace the entered value with the min or max, depending on what failed. I'm still not sure if this is the right way but I don't have any other idea at the moment.
It is still ugly as it is just a concept. All unit tests are passing so in …
=> Numeric Min and Max of TValue

Source/Extensions/Blazorise.Snackbar/Snackbar.razor.cs
Because of #3037 
However I noticed Validations also suffers of mem leak... I was going to do it all on same PR, but seems more complex... I'm still figuring it out, will submit separate PR.
=> Fix Snackbar unreleased resources by providing missing DisposeAsync

Build/Blazorise.Client.props, Build/Blazorise.Demo.props, Build/Blazorise.Docs.props, Build/Blazorise.Server.RC.props, Build/Blazorise.Server.props, Build/Blazorise.props, Demos/Blazorise.Demo/Blazorise.Demo.csproj, Tests/BasicTestApp.Client/BasicTestApp.Client.csproj, Tests/BasicTestApp.Server/BasicTestApp.Server.csproj, Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj
closes #3088 Update to latest .Net 5.0.x
All projects update to `5.0.11`. We still have some things on `5.0.0` but it seems that MS didn't provide any never version for these packages.
=> Update project to use .Net 5.0.11

Source/Blazorise.Bootstrap/Modal.razor, Source/Blazorise.Bootstrap5/Modal.razor, Source/Blazorise/Components/Modal/Modal.razor
Closes #3069
Removing it from the DIV does fix the problem. Don't see any problem with removing it. Tabbing keeps working normally. 
Also applying -1 seems pretty close to not having the attribute set at all, both ways make it so it's not tab targetable.
https://developer.mozilla.org/pt-BR/docs/Web/HTML/Global_attributes/tabindex
=> Fix Autocomplete inside modal loosing focus on dropmenu scroll click

Source/Blazorise/Themes/ThemeGenerator.cs, Tests/Blazorise.Benchmark/Blazorise.Benchmark.csproj, Tests/Blazorise.Benchmark/Blazorise/ThemeBenchmark.cs, Tests/Blazorise.Benchmark/Program.cs, Tests/Blazorise.Tests/ThemeGeneratorTest.cs
Closes #3133 
Didn't have time to finish yet.
Need to test Regex.Matches vs our version as I am not 100% it's 100% logically equivalent. If it is, then it's way faster.
Also need to do some reading up on https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices as static method `Regex.IsMatch` might also be worth considering...
**Edit:** I'm not sure if additional steps need to be taken to actually take advantage of `RegexOptions.Compiled` ?
Also consider using Span in the future to do internal optimizations in string manipulation... might be worth it for 1.0.0
A good resource: 
https://www.youtube.com/watch?v=FM5dpxJMULY&ab_channel=NickChapsas
=> Extract hex digits cache regex

Source/Blazorise/wwwroot/table.js
=> Fix Table THead Query Selector to target only first THead

Source/Blazorise/Base/BaseTextInput.razor.cs, Source/Blazorise/Themes/ThemeGenerator.cs, Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs
=> Unused vars

Source/Blazorise/Components/Carousel/Carousel.razor.cs
Closes #3157
Couldn't reproduce it again after this change.
.NET is weird sometimes... O.O
=> Avoid an System.ObjectDisposedException due to the timer being disposed

Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor.cs
Closes #3149
This one has probably been there for a while haha. Problem only with Datagrid internal modal which wasn't going through the Modal.Hide/Close pipeline on Cancel button press.
=> DataGrid : Fixes Modal Closing not being called correctly on Cancel.

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor, Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor.cs
=> DataGrid : Makes sure to close the modal with explicit CloseReason.UserClosing, if Save ran to success

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Fixes Bug introduced recently on PR #3245
Closes #3249
=> CheckMultipleSelectionSetEmpty Missing Null Check If Reference Type

Source/Extensions/Blazorise.Markdown/Enums.cs, Source/Extensions/Blazorise.Markdown/Providers/MarkdownActionProvider.cs
EasyMDE has three actions not described in the [readme](https://github.com/Ionaru/easy-markdown-editor#toolbar-icons), yet.
They are in the code:
https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js#L1614-L1626 (undo/redo)
https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js#L1553-L1558 (upload-image)
Undo/Redo is already available through shortcuts.
(Another approach to support this would be to allow custom actions that are passed through to EasyMDE - currently that's restricted by the internal [MarkdownActionProvider](https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Markdown/Providers/MarkdownActionProvider.cs)).
=> Markdown: add missing actions

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Make sure SelectedRow/SelectedRows changes are always notificated to DatagridRow by re-setting them up as parameters.
I think there was one more issue related to this but I can't seem to find it now.
Closes #3386
**Code used for testing:** 
(Basically select rows, then mutate the SelectedRows...  see if it propagates successfully.)
```
<DataGrid 
@ref="dataGridRef"
TItem="string" Data="@dataList" Narrow="true" FixedHeader="true" Virtualize="false"
VirtualizeOptions="@(new Blazorise.DataGrid.Configuration.VirtualizeOptions() { DataGridHeight="calc(-8px + 70vh) !important", DataGridMaxHeight="calc(-8px + 70vh) !important" })"
Striped="true" Bordered="true" Filterable="true" Sortable="false" SelectionMode="DataGridSelectionMode.Multiple"
Responsive="true"
SelectedRows="@myList" …
```
=> Make sure SelectedRow/SelectedRows changes are always notificated to DatagridRow

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Edited Datagrid component to allow a SortTemplate to render when `column.CurrentDirection == SortDirection.Default`. Additionally, columns that are sortable will now display the FontAwesome Sort icon `IconName.Sort`.
Passed all unit tests, visually inspected performance in the Bootstrap 5 Demo Client. Works as intended.
Resolves #3455
=> Allow Sort Template when There is No Sort Direction, and Display a Default Sort Icon on Sortable Columns

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/Code/ChartComplexDataExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/Examples/ChartComplexDataExample.razor, Source/Extensions/Blazorise.Charts/Data/ChartDataset.cs, Source/Extensions/Blazorise.Charts/Options/ChartOptions.cs, Source/Extensions/Blazorise.Charts/Options/ChartParsing.cs
closes #2317
This introduces the parsing options needed for complex types to work with the charts. To make it work I had to remove `JsonNumberHandling` from the `Data` in the `ChartDataset` object. I'm not sure what this change might introduce so I would investigate more.
@Luk164 any idea?
Test code:
```cshtml
<LineChart @ref="lineChart" TItem="WatcherEvent" Options="@lineChartOptions" />
```
```cs
private LineChart<WatcherEvent> lineChart;
LineChartOptions lineChartOptions = new()
{
Parsing = new ChartParsing
{
XAxisKey = "sector",
YAxisKey = "count",
}
};
private string[] Labels = { "Red", "Blue", "Yellow", "Green", "Purple", "Orange" };
private List<string> backgroundColors = new() { ChartColor.FromRgba( 255, 99, 132, 0.2f ), ChartColor.FromRgba( 54, 162, 235, 0.2f ), …
```
=> Chart Parsing options

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Code/NumericPickerIntegerExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Code/NumericPickerMinMaxExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Examples/NumericPickerIntegerExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Examples/NumericPickerMinMaxExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/NumericPickerPage.razor, Source/Blazorise.Bootstrap/NumericPicker.razor, Source/Blazorise.Bootstrap5/NumericPicker.razor, Source/Blazorise.Bulma/NumericPicker.razor, Source/Blazorise.Material/NumericPicker.razor, Source/Blazorise/Base/BaseDebounceTextInput.cs, Source/Blazorise/Components/NumericPicker/NumericPicker.razor, Source/Blazorise/wwwroot/numericPicker.js, Source/Blazorise/wwwroot/utilities.js
Adds a null check function for null and undefined in JS. the problem with `||` was that `0` would also fail as a value.
=> Fix NumericPicker null checks and Immediate mode

Source/Extensions/Blazorise.Components/Autocomplete.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
closes #3420
closes #3536
Adds a simple null check to not invoke `TextField` if the item is null.
=> Autocomplete: Null check in GetItemText and GetItemValue

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
closes #3530
This PR reverts the empty sort icon for DataGrid while still allowing to use `SortDirectionTemplate`. The change was introduced by #3495 but it was too obtrusive for general users. In the future, we will ad an opt-in parameter for the sort icon.
=> DataGrid: don't show default sort icon

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Closes #3637
Somehwere in time `Reload`  substitued the explicit ReadData for code reuse. Well it does not make sense to `Reload` in the cases of static data, it will set the dirty flag again for apparently no reason.
=> DataGrid : Static data filter data only once on first load

Source/Blazorise.AntDesign/AntDesignClassProvider.cs, Source/Blazorise.AntDesign/Dropdown.razor.cs, Source/Blazorise.Bootstrap/BootstrapClassProvider.cs, Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs, Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Blazorise.Bulma/Config.cs, Source/Blazorise.Bulma/Dropdown.razor.cs, Source/Blazorise/Components/Dropdown/Dropdown.razor.cs, Source/Blazorise/Interfaces/IClassProvider.cs, Source/Blazorise/Interfaces/Modules/IJSDropdownModule.cs, Source/Blazorise/Modules/JSDropdownModule.cs, Source/Blazorise/Providers/ClassProvider.cs, Source/Blazorise/Providers/EmptyClassProvider.cs, Source/Blazorise/wwwroot/dropdown.js, Source/Blazorise/wwwroot/observer.js, Tests/Blazorise.Tests/Components/DropdownComponentTest.cs
Closes #3682
FIxes RightAligned parameter no longer being considered, since we've introduced popper to handle dropdown menu positioning.
And like we've talked also sets up better popper overflow/out of bounds detection, moving the menu accordingly.
=> Dropdown Fix RightAligned

Source/Blazorise/Components/Validation/EditContextValidator.cs, Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs
Allows custom validators to use service provider to get more stuff.
=> Add ServiceProvider to ValidationContext

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Closes #3704
`GetRowInfo` was returning a `RowInfo` that is in the process of being disposed. 
When `RowInfo` is first created, use it straight up as a parameter for `DataGrid.ToggleDetailRow`, no point in doing another lookup.
Change `GetRowInfo` to grab the last row instead, making it safer to grab an actual non stale row if something similar could happen.
Also this does happen because the row is being re-rendered (Disposed of && re-Initialized), in this case it was just a filter so it probably should have kept the same row instance, instead of rendering a new one... going to open an issue so we can take a look if there's some optimization we can do here, we do have `@key="@item"` but it might not be working in certain cases, due to conditional renderings. Not sure if we can do …
=> DataGrid : ToggleDetailRow : Fix stale/disposed row info being used on ToggleDetailRow logic

Source/Blazorise/Components/FileEdit/FileEdit.razor.cs, Source/Blazorise/Utilities/IO/RemoteFileEntryStream.cs
Closes #3739
User was doing a `WriteToStreamAsync` followed by a `OpenReadStream` on the same file. 
Progress wasn't reset when starting `OpenReadStream`. I was going to suggest to do `FileEdit.Reset` as a temporary workaround, but also found that it does not reset the internal progress, since it clears the files it also makes sense to reset the internal progress.
=> FileEdit : Fix Missing UpdateFileStartedAsync on OpenReadStream + reset progress

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Closes #3795
- Added an escape on `Reload` if DataGrid is already in Loading state.
- Added a new `OnAfterRenderAsync` first render condition to make sure to `Reload` the `DataGrid` if `VirtualizeManualReadMode` is set to obtain the data, since `EmptyTemplate` would fight over the `Virtualize` render since no data would still exist.
- On `IsEmptyTemplateVisible`/`IsEmptyFilterTemplateVisible` Prefer `IsLoading` over `IsLoadingTemplateVisible` as whenever the DataGrid is loading makes sense to not display this template.
- On `IsEmptyTemplateVisible`/`IsEmptyFilterTemplateVisible` add `Rendered` condition to make sure it's only ever true after the first rendering process has happened.
=> DataGrid : Fix : Virtualize not reading data when EmptyTemplate is set.

Source/Blazorise/Adapters/CloseableAdapter.cs
I tested with all providers with backdrop visible & hidden and compared VisibleChanged events and CloseReason states and the fix does not appear to effect the behavior.
=> Fix for Modal double-click infinite loop.

Source/Blazorise/Base/BaseInputComponent.razor.cs, Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Closes #3798
DatePicker's internal value is an array. So when `value.IsEqual( InternalValue )` was used in the base class, it would always fail. I have introduced a new API in the base input class, to be able to override the compare function. Currently, only DatePicker uses it. I think a `Select` should also benefit from it because it too uses an array internally.
=> DatePicker: compare array values to prevent duplicate change events

Source/Blazorise.Bootstrap/Modal.razor, Source/Blazorise.Bootstrap5/Modal.razor, Source/Blazorise/Adapters/CloseableAdapter.cs, Source/Blazorise/Components/Modal/Modal.razor, Source/Blazorise/Components/Modal/Modal.razor.cs
Through testing I found that the full duration delay in the ClosableAdapter is not necessary when transitioning to a visible state. I also found that the modal backdrop fade can be restored by decoupling it from the parent modal visible state and only changing the backdrop visibility before or after the animation.
I tested with all providers and it seems to work well.  It definitely feels more snappy without the delay.
=> Modal: Fix Animations

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Closes #3926
Already fixed over at master branch, https://github.com/Megabit/Blazorise/pull/3856/commits/9210f74384f158d671f9eb1e30f716a0a49cccf9
Apply same change.
=> AutoComplete : Remove Clear from Close (Not sure why this was here)

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Closes #2996
By adding an `Loading` flag, we tell that `NotFoundContent` should only display if the `AutoComplete` isn't in a loading state.
`AutoComplete` will be in a loading state, while `SearchChanged` EventCallback is running.
In the next release, we should make sure that the flag also includes the new `ReadData` feature, #3856
Code used to test:
```
<Autocomplete TItem="string"
Data="@data"
TextField="@(( item ) => item)"
ValueField="@((item) => item)"
Placeholder="Search..."
Filter="AutocompleteFilter.StartsWith"
SearchChanged="SearchChanged"
>
<NotFoundContent> Sorry... @context was not found! :( </NotFoundContent>
@code{
List<string> data = new();
public async Task SearchChanged(string value )
{
await Task.Delay(2000);
if (value.StartsWith("a")) …
```
=> AutoComplete : Loading Flag

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Closes [#3516](https://github.com/Megabit/Blazorise/issues/3516)
I couldn't find a better fix. `Virtualize` `ManualReadMode` binds to the `VirtualizeItemsProviderHandler` that expects data to be returned. This data depends upon the `Data` parameter, which in this case, like the user reported, would use stale data, due to `SetParametersAsync` not have been run yet.
I have wondered this before, and `ReadData` does work great. 
But generally, for these apis, and just like in the `Virtualize` component, they tell you to return the data (instead of basically mutating it "externally") and then they do the work internally, do you remember why the choice of `EventCallback` over the "handler" approach? Or was it not considered at the time?
=> Virtualize ManualReadMode : Workaround for Stale parameter 

Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/DragDropPage.razor
Removed string property as type is actually `Func<TItem, bool>`
Associated Issue #3997
=> Bug - Removed redundant property

Source/Blazorise/Base/BaseAfterRenderComponent.cs, Source/Blazorise/ComponentActivator.cs, Source/Blazorise/ComponentDisposer.cs, Source/Blazorise/Config.cs, Source/Blazorise/Properties/AssemblyInfo.cs, Source/Blazorise/Utilities/ExpressionCompiler.cs, Tests/Blazorise.Benchmark/Program.cs, Tests/Blazorise.Tests/Components/DropZoneTest.cs, Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs, Tests/Blazorise.Tests/Mocks/MockButton.cs
References to disposed components were being held by the service provider forever, causing a memory leak. This will clean up already disposed components from the service provider, allowing the GC to clean up all unreferenced controls
Closes #4100
=> Remove Disposed Component References

Source/Blazorise/Components/Pagination/PaginationLink.razor.cs
Added check before invoke Clicked to check if parent Pagination Item is Disabled.
https://github.com/Megabit/Blazorise/issues/4122
=> Fix when PaginationItem is disable PaginationLink not call to Clicked

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs
While investigating issue #4093.
Noticed that the current `DisplayableColumns` check makes it so `DataGridMultiSelectColumn` / `DataGridCommandColumn` would always show even if `Displayable="false"`. 
This does not seem appropriate behaviour. User should still be able to hide them if he wants to. Only real mandatory case, is when the `EditMode` is set to inline, and user needs the `CommandColumn` to display the Save/Cancel buttons. 
This has been tested on our demo DataGridPage with the use of `CommandMode.Default`, which helps having access to the Edit command through the ButtonRow if Command Column is hidden (`Displayable="false"`).
=> DataGrid : Adjust IsDisplayable check. 

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs, Source/Blazorise.Bootstrap5/Bootstrap5ThemeGenerator.cs
Fixes: https://github.com/Megabit/Blazorise/issues/4125
Removed `box-shadow` from disabled buttons on `BootstrapThemeGenerator` and `Bootstrap5ThemeGenerator`. This issue does not appear on the other providers.
=> Removed shadow from disabled buttons

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Closes #4195
User could not set an empty String in a bound SelectedText.  Still had a workaround of using the `Clear` method.
However in the previous release we did have it working like that, and it does make sense. 
Testing code : 
```
<Autocomplete TItem="Test"
TValue="string" Data="data"
FreeTyping TextField="@((item) => item.Name)"
ValueField="@((item) => item.Id)"
@bind-SelectedText="_test.Name">
<ItemContent>
@if ( context.Item.Name != null )
{
<Paragraph>@String.Format("{0} ({1})", context.Text, context.Item.Name)</Paragraph>
}
else
{
<Paragraph>@context.Text</Paragraph>
}
</ItemContent>
<Button Clicked="SetValue">Set Value</Button>
@code {
private List<Test> data = new() { new() { Id = "1", Name = "Test" }, new() { Id = "2", Name = "Test2" } };
private Test _test = …
```
=> AutoComplete: On SelectedText parameter change : Propagate Empty String

Source/Blazorise/Utilities/IO/RemoteFileEntryStreamReader.cs
Closes #4213
So when implementing the new 
**stream-from-javascript-to-net**
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#stream-from-javascript-to-net
in **WriteToStreamAsync**, we made the assumption that the provided buffer would be fully filled from the js stream. This is not true, and occasionally it might send less bytes read back. This PR fixes the wrong assumption. Also you couldn't tell from looking at file sizes since it would create still an equal sized file, just that the content would be corrupt.
Also took the time and tested `OpenReadStream` just to be sure, here it is working correctly.
Bug happens with images with a few hundred of kbs.
Code used to test:
```
<FileEdit @ref="@fileEdit" …
```
=> FileEdit Fix WriteToStreamAsync skipping bytes

Source/Blazorise/Base/BaseInputComponent.razor.cs
closes #4162
I have left our implementation because we already use the same `utilities.focus` from several places inside of the JS modules. And also, our implementation has the benefit that the element can be retrieved by ElementRef and ElementId, a kinda a fallback in some cases. So all in all it's better to leave it.
=> Remove focus workaround

Source/Blazorise/Base/BaseTextInput.razor.cs, Source/Blazorise/Utilities/ValueDebouncer.cs
Some simple changes seem to be enough to keep it in sync. I'm happy that hopefully we finally get to fix this feature.
**To test:**
Add to Blazorise global config:
```
options.Debounce = true;
options.DebounceInterval = 300;
```
Test by going to `Autocomplete` and `Datagrid` and see that you can write in increments of 300ms and only then it updates the component internal value triggering the `Datagrid` Filtering or the `Autocomplete` search for example...
If you have any other ideas to test the implementation, say so.
Seems to work just fine even, with 100ms for example, didn't bother to test less then that, would beat the purpose of the feature. :)
Other implementations that I tought off, but apparently we might not need to explore:
- CancellationToken based
- Use `PeriodicTimer` to …
=> Fix Debounce

Documentation/Blazorise.Docs/Pages/Docs/Components/Files/FilePickerPage.razor
Closes #4263
`FilePicker` has been specifically made with `AutoReset="false"` by default.
=> Docs : Fix FilePicker AutoReset default to false

.gitignore, Blazorise.sln, Source/Blazorise/Blazorise.csproj, Source/Blazorise/Themes/Theme.cs, Source/Blazorise/Themes/ThemeCache.cs, Source/Blazorise/Themes/ThemeGenerator.cs, Source/SourceGenerators/Blazorise.Generator.Features/Blazorise.Generator.Features.csproj, Source/SourceGenerators/Blazorise.Generator.Features/GenerateEqualityAttribute.cs, Source/SourceGenerators/Blazorise.Generator.Features/GenerateIgnoreEqualityAttribute.cs, Source/SourceGenerators/Blazorise.Generator/Blazorise.Generator.csproj, Source/SourceGenerators/Blazorise.Generator/EqualitySourceGenerator.cs, Source/SourceGenerators/Blazorise.Generator/Properties/launchSettings.json, Source/SourceGenerators/README.md, Tests/Blazorise.Tests/ThemeCacheTest.cs
Closes #4254
- Introduced Blazorise.SourceGenerator 
- Used a Blazorise.SourceGenerator.Features project to allocate the common Attributes for the generation detection
- Theme is now partial and has Equality / HashCode methods generated. 
- Like we've talked, the problem here was that the event field was messing up the `GetHashCode` from the `Dictionary`, so on this version at least, it was never caching anything, just wasting memory if multiple themes were used (and not cleaning up either)
- The tests that we have are good, but unfortunately missed the event field, giving a false sense of being ok.
- I did not see a reason for the triple variables for caching, and I have reduced the implementation to 1.
I still need to do a bit more testing later today, but all in all seems like it is …
=> Fix theme caching issue

Source/Blazorise.Bulma/BulmaClassProvider.cs, Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
Fixes reported issue at https://support.blazorise.com/issues/76/DataGrid-Pagination-Customization
where certain breakpoints would have no effect and would not hide certain datagrid pagination structures.
According to Bulma docs, the correct way to use the breakpoint helper for display `none`, is actually `hidden`.
https://bulma.io/documentation/helpers/visibility-helpers/
Additionally the Pagination Display breakpoint was just slightly changed by adding `OnMobile`, so it does not cause css rule conflict.
Tests were done on every provider.
`AntDesign` has the same problem and we should investigate in the future, but it is a Provider with not as much priority and there's a few other issues with it, so we'll leave it for now and we'll work on improving `AntDesign` issues when we have more …
=> Bulma fix display none helper // Breakpoint (Responsive helper)

Demos/Blazorise.Demo/Pages/Tests/MarkdownPage.razor, Source/Extensions/Blazorise.Markdown/Markdown.razor.cs
Closes #4084
Added the same lifecycle logic as in #4315. We're postponing `ExecuteAfterRender` after the component is fully rendered and initialized and then forwarding it all to execution.
PS. we can consider implementing the same logic in a centralized way so that it can be reused by other components. We need to do this in `master.`
=> Markdown: wait for the first render to execute methods

Documentation/Blazorise.Docs/Layouts/DocsLayout.razor
The rest of the extensions are sorted by name, the last 2 weren't. I've sorted them by name.
=> Sort extensions by name

Build/Blazorise.Demo.props, Demos/Blazorise.Demo.Bootstrap.Server/Controllers/WeatherForecastController.cs, Demos/Blazorise.Demo.Bootstrap.Server/Startup.cs, Shared/Blazorise.Shared/Models/WeatherForecast.cs, Source/Blazorise/Base/BaseAfterRenderComponent.cs, Source/Blazorise/Base/BaseComponent.cs, Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs, Source/Extensions/Blazorise.Markdown/Markdown.razor.cs, Source/Extensions/Blazorise.RichTextEdit/BaseRichTextEditComponent.cs, Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.cs
**Test for #4075** 
This test can be run only on Blazorise.Demo.Bootstrap.Server because it only has the controller with the endpoint `weatherforecast/getforecast"`.
```razor
@using Flurl;
@using Flurl.Http;
@using System.Text.Json.Serialization;
<Row>
<Column>
<Field>
<NumericPicker Decimals="0" SelectAllOnFocus="true" @bind-Value="@Forecast.TemperatureC" />
</Field>
</Column>
</Row>
@code {
[Inject] NavigationManager NavMgr { get; set; }
private WeatherForecast Forecast = new();
protected override async Task OnAfterRenderAsync( bool firstRender )
{
await base.OnAfterRenderAsync( firstRender );
if ( firstRender )
{
Forecast = await NavMgr.BaseUri.AppendPathSegment( "weatherforecast/getforecast" ).GetJsonAsync<WeatherForecast>();
await InvokeAsync( StateHasChanged );
}
}
}
```
---
**Test …
=> Implement delayed execution in BaseAfterRenderComponent

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridFullColumnSpanRow.razor.cs
Closes #4289
Closes #4280
Problem:
- Virtualize + ReadData would get jumpy or just act all weird and doing alot of requests, specially when navigating further down the table.
Solution:
- The placeholder for the rows would be half the size the actual rows, messing up the Virtualize calculations, so we've inserted a blank space so it can calculate the same space, this seems like a fine solution I would say.
Additionally implemented the same delay as in Quickgrid's as it removes redudants calls. Copied same note, as the suggestion seems implementation worthy.
`Virtualize` seems smoother with the changes, specially on Blazor.Server.
=> DataGrid: Virtualize fixes and optimizations

Source/Extensions/Blazorise.Markdown/Markdown.razor.cs
Closes #4299
> 1— Allow to set file upload url after upload was completed. I.e receive url from api upload call.
> 2— 'null' exception
This **PR** Fixes number 2 problem.
However for number **1**, I can only think of a solution for now, which we would have to schedule for **1.2** if you agree.
Introduce a new bool `Parameter NotifyImageUploadStatusAuto`, that the user can set to `false`. 
Introduce methods that wrap the `JSModule.NotifyImageUploadSuccess` , `JSModule.NotifyImageUploadError`
And handle himself, this part, this way he can do it himself with a bit more code.
=> Markdown: NotifyImageUploadSuccess prefer string.Empty over null as mde throws on null

Source/Extensions/Blazorise.Markdown/Markdown.razor.cs, Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.cs
Continuation from #4331
I have noticed on our https://support.blazorise.com/ that when I try to post a comment, I can't get the result from the `Markdown` by invoking the `GetValueAsync`. The problem was that I had made it so that #4331 would only return the result if the rendered component. I only noticed it because we wrapped `Markdown` in a separate `MarkdownEditor` component, so the Clicked event didn't get triggered on an IssuesPage.
`return await ExecuteAfterRenderAsync( async () => await JSModule.GetValue( ElementId ) );`
So this PR solves it by returning the result immediately if the component it already being rendered without waiting for the new render to complete.
=> Markdown and RichTextEdit: Invoke immediately if Rendered

Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs, Source/Blazorise/Utilities/Converters.cs
Closes https://support.blazorise.com/issues/43/NumericPicker-with-too-high-Integer-values
It's not the cleanest solution, but it works. To test the code:
```razor
<Field>
<FieldLabel ColumnSize="ColumnSize.Is3">Short</FieldLabel>
<FieldBody>
<NumericPicker TValue="short" @bind-Value="@pickerValueShort" Decimals=0 Min="1" Max="100" autocomplete=off></NumericPicker>
</FieldBody>
</Field>
<Field>
<FieldLabel ColumnSize="ColumnSize.Is3">Int</FieldLabel>
<FieldBody>
<NumericPicker TValue="int" @bind-Value="@pickerValueInt" Decimals=0 Min="1" Max="100" autocomplete=off></NumericPicker>
</FieldBody>
</Field>
<Field>
<FieldLabel ColumnSize="ColumnSize.Is3">Long</FieldLabel>
<FieldBody>
<NumericPicker TValue="long" @bind-Value="@pickerValueLong" Decimals=0 Min="1" Max="100" …
```
=> NumericPicker: check for large number values

Source/Blazorise/wwwroot/dropdown.js
We changed the strategy to `absolute` in #3699. But one of our commercial clients reported an issue. It affects the scrollbars when the menu is shown, even though it has enough room on the screen.
Changing it to `fixed` seems to fix the problem. I have tested all our dropdowns on the demo app, and it seems to be working.
=> Dropdown: use fixed strategy

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Fixes 
https://support.blazorise.com/issues/84/Autocomplete-Selection-with-Enter-Error
- Fixed trying to get an item when there's no data.
- Fixed MinLength = 0 + Multiple, would hide Dropdown on selection. 
- Fixed ActiveItemIndex being higher then the actual Data if the last item was selected
- Fixed Removing a multiple value by pressing backspace for example and not refreshing the data, this would be very apparent when MinLength = 0
Test Code:
```
<Blazorise.Components.Autocomplete TItem="Author" TValue="Author"
Data="@AuthorList"
TextField="@(item => item.Name)"
ValueField="@(item => item)"
Multiple
MinLength="0"
CloseOnSelection="false" />
@code {
private List<Author> AuthorList = new() { new() { Name = "A" }, new() { Name = "AB" }, new() { Name = "AC" }, new() { Name = "AD" } }; …
```
=> Autocomplete fixes // MinLength = 0

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Fixes
https://support.blazorise.com/issues/82/DataGridReadDataEventArgs-Cancellationtoken-when-filtering
Testing code:
```
<Blazorise.DataGrid.DataGrid TItem="Author"
Data="@AuthorList"
ReadData="@OnReadData"
Filterable>
<DataGridCommandColumn />
<DataGridColumn TItem="Author" Field="@nameof(Author.Name)" Caption="Name"></DataGridColumn>
<DataGridColumn TItem="Author" Field="@nameof(Author.Age)" Caption="Age"></DataGridColumn>
<DataGridColumn TItem="Author" Field="@nameof(Author.BookTitle)" Caption="Title"></DataGridColumn>
</Blazorise.DataGrid.DataGrid>
@code {
private List<Author> AuthorList = new() { new() { Name = "A" }, new() { Name = "AB" }, new() { Name = "AC" }, new() { Name = "AD" } };
private class Author
{
public string Name { get; set; }
public string Age { get; set; }
public …
```
=> Datagrid: Introduce CancellationTokenSource and corresponding cancellation on filter changes

Demos/Blazorise.Demo/Pages/Tests/DragDropPage.razor, Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/Code/BasicDragDropExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/Code/DragDropReorderingExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/Examples/BasicDragDropExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/Examples/DragDropReorderingExample.razor, Source/Blazorise/Components/Droppable/DropContainer.razor.cs, Source/Blazorise/Components/Droppable/DropZone.razor, Source/Blazorise/Components/Droppable/DropZone.razor.cs, Source/Blazorise/Components/Droppable/_Draggable.razor.cs, Tests/BasicTestApp.Client/DropZoneReorderComponent.razor, Tests/Blazorise.Tests/Components/DropZoneTest.cs
Closes https://support.blazorise.com/issues/80/Reordering-Items-in-DropContainer-Takes-1-minute-to-Complete
Optimizes DropZone so that items are calculated and fetched only when requested. Also added a bunch of `key` attributes to the draggable elements.
=> DragDrop: optimizations

Source/Blazorise/Base/BaseAfterRenderComponent.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Tests/BasicTestApp.Client/DataGridComponent.razor, Tests/Blazorise.Tests/Components/DataGridComponentTest.cs
Closes #4390
It was actually a combination of 8a605f5af766c0eaacdc83b3fdda04cf7bb8d470 messing with the `Rendered` flag since Datagrid does not call `await base.OnAfterRenderAsync( firstRender );` when it is first rendered.
There was two possible fixes here,
- We could make sure to call the `await base.OnAfterRenderAsync( firstRender ); `
- Make sure the Rendered flag is set on our `BaseAfterRenderComponent` even if firstRender was never true;
We decided to take the second route, as it is how it was working before from a more general pespective. From a `Datagrid` perspective we decide to not call `await base.OnAfterRenderAsync( firstRender );` just like it was previously, as to avoid any unintended/unexpected side effects.
And the 4ae8aa8909a9893a67a0a13d75968c3cc8531b87 (#3800)
Where the …
=> Datagrid fix empty template not rendering

Source/Blazorise/wwwroot/closable.js
Found a bug introduced in https://github.com/Megabit/Blazorise/commit/35849a1794b380f4f947770b41192ac5f8078b2a. Fixes https://github.com/Megabit/Blazorise/issues/4379.
I imagine this may have caused issues elsewhere as well.
=> Fix closable.js find index functions.

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs, Tests/BasicTestApp.Client/AutocompleteMultipleReadDataComponent.razor, Tests/Blazorise.Tests/Components/AutoCompleteMultipleComponentTest.cs, Tests/Blazorise.Tests/Components/AutocompleteMultipleReadDataComponentTest.cs, Tests/Blazorise.Tests/Components/Base/AutocompleteBaseComponentTest.cs
Closes #4372
I believe the commits should be self descriptive, just let me know if you have any doubts.
------
I believe we should investigate making the `List<>` Parameters we exposed, actually `IEnumerable<>`. This will probably make it easier to handle changes internally, since users won't be able to mutate the collection by calling `.Add` and `.Remove` directly.
But I'm not entirely sure it would cover all cases. 
And I believe we wouldn't need the triplet parameter thing glutio came up with. I only noticed today, that we're actually keeping an additional collection in memory with 
precisely because of these mutations which can't be easily detected && compared without creating new references in memory.
**Example:** User does : `SelectedValues.Add("1")`=> When it gets to …
=> Autocomplete multiple values sync

Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataInMemoryPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs, Source/Extensions/Blazorise.DataGrid/ExtensionMethods.cs
This is a simple improvement with a small impact on the existing functions.
This improvement adds the property FirstClickSortDirection InverseSorting gives the ability of the developer to select which will be sort direction on the first click, instead of always being ASC and after that, on the second click be DESC.
Closes #4431
=> #4431 DataGrid: Added ability to inverse sort direction

Source/Blazorise.AntDesign/AntDesignStyleProvider.cs, Source/Blazorise.Bootstrap/BootstrapStyleProvider.cs, Source/Blazorise.Bootstrap5/Bootstrap5StyleProvider.cs, Source/Blazorise.Bulma/BulmaStyleProvider.cs, Source/Blazorise.Tailwind/TailwindStyleProvider.cs, Source/Blazorise/Components/Modal/Modal.razor.cs, Source/Blazorise/Components/Modal/ModalSharedContext.cs, Source/Blazorise/Components/Modal/_ModalBackdrop.razor.cs, Source/Blazorise/Config.cs, Source/Blazorise/Interfaces/IStyleProvider.cs, Source/Blazorise/Providers/EmptyStyleProvider.cs, Source/Blazorise/Providers/StyleProvider.cs, Source/Blazorise/States/ModalState.cs, Source/Blazorise/Utilities/StyleBuilder.cs, Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs
Closes #3878
The ZIndex is calculated based on the difference between zindex of the modal and backdrop. The difference is then raised based on the open index to ensure the new index is always higher than the previous one.
Also, I fixed some minor bugs with the styles `;` delimiter.
=> Modal: dynamically calculate ZIndex

Source/Extensions/Blazorise.DataGrid/ExtensionMethods.cs
Improvements into NextDirection() to keep again the sort direction sequence:
- "Non sorting -> asc -> desc -> non sorting" 
or
- "Non sorting -> desc -> asc -> non sorting".
[#4460](https://github.com/Megabit/Blazorise/issues/4460)
=> #4460 Datagrid Sort behaviour regression

Source/Blazorise/Utilities/IO/FileEntry.cs, Source/Blazorise/Utilities/IO/IFileEntry.cs, Source/Extensions/Blazorise.Markdown/Markdown.razor.cs
Closes #4335
As a brief reminder, the problem here, is that when uploading images on `Markdown`, you can't set the `File.UploadUrl` before the internal `JSModule.NotifyImageUploadSuccess` (notifies markdown of image success + url) occurs, since it occurs as part of the final process of our file write operations (`FileEndedEvent`).
I don't think there's a good way to do this without introducing any new api. You could probably do some tricks with delays, etc...? But that doesn't seem right. Better have an explicit api in my opinion.
Do you like this one? As long as we properly document it isn't too hard for the user to use. Also, was this where you were going with the `TaskCompletionSource`? I couldn't find another way.
Testing code:
```
<Markdown ImageUploadChanged="Changed" …
```
=> Markdown - Able to provide uploadUrl after the actual Upload has happened

Source/Blazorise/Components/Switch/Switch.razor.cs
Closes #4583
**Test code**
```razor
<Button Color="Color.Primary" Clicked="@(()=>chk = !chk)">TOGGLE</Button>
<Switch @bind-Checked="@chk" />
@code {
bool chk;
}
```
=> Switch: DirtyClasses when Checked is changed programmatically

Source/Blazorise/Base/BaseComponent.cs, Source/Extensions/Blazorise.Charts.DataLabels/ChartDataLabels.razor.cs
Closes #4585
With this PR, we fix the update of the DataLabels that were being static and only defined once per initialization. We check it the data was changed and then update if needed.
=> DataLabels: fix update from parameters

Source/Blazorise/wwwroot/datePicker.js
Closes #4581
A fix for the problem https://github.com/flatpickr/flatpickr/issues/2861
**Test code:**
```razor
<Button Color="Color.Primary" Clicked="@(()=> _selectedDate = DateTime.Today)">
SET VALUE
</Button>
<DatePicker Date="@_selectedDate"
@ref="_datePicker"
DateChanged="@OnDateChangedAsync"
InputMode="DateInputMode.Month" TValue="DateTime?"
Min="@DateTimeOffset.MinValue" Max="@DateTimeOffset.Now" />
@code {
private DatePicker<DateTime?> _datePicker;
private DateTime? _selectedDate;
private Task OnDateChangedAsync( DateTime? date )
{
_selectedDate = date;
StateHasChanged();
return Task.CompletedTask;
}
}
```
=> DatePicker: hack to fix the disabled month rendering

Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs
Closes #4618 
Fixes the spacing of the command cell when the table content is too large. The downside is now that the users cannot override the default spacing of the inlined `div`.
=> DataGrid: place command buttons inside of inline div

Source/Extensions/Blazorise.DataGrid/DataGrid.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridFullColumnSpanRow.razor.cs
https://blazorise.com/support/issues/96/DataGrid-LoadingTemplate-not-displayed-during-OnReadData
Missing `StateHasChanged` after `IsLoading` is set to true.
However, from my tests an async execution would still trigger the `LoadingTemplate` correctly. So Blazor was still smart in that regard. (Otherwise we'd certainly have more open issues because of `LoadingTemplate` not working)
Only way I could reproduce the **LoadingTemplate** not working was to block the async thread by appling a `Thead.Sleep`.
I guess the developer should make sure he's writting correct async code.
But by adding `Task.Yield` after `StateHasChanged` call we can force it to be definitely displayed for good measure. 
I'd rather not touch `HandleVirtualizeReadData` as it seems to be working fine and with no complaints.
=> DataGrid : Add StateHasChanged after IsLoading is set to true

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Closes #4622 
I am having issues with the user pressing the Confirm key when the dropdown is not visible and it auto assigns the "hidden" selected item/text the code has stored (behind the scene so to speak).
I just noticed I was supposed to create a new branch first (Sorry).
=> Autocomplete ConfirmKeys handled when the Dropdown is closed

.github/workflows/cla.yml
Let's go ahead and update the cla assistant, see if it gets better.
One recurring issue is that it seems that recheck is not working properly. We always have to manually retrigger the action after the contributor has signed.
=> Update CLA assistant to 2.2.1

Source/Blazorise/Components/Modal/IModalSharedContext.cs, Source/Blazorise/Components/Modal/Modal.razor.cs, Source/Blazorise/Config.cs, Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs
=> Add IModalSharedContext interface and make it public

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
In order to make the Autocomplete pop the whole list on click (like a normal select list), you need to set MinLength to 0. It took me a long time to figure that out. A simple docs update will make it more clear for future developers.
I hope my branch name is appropriate.
=> Docs update for Autocomplete dropdown functionality

Source/Blazorise/Base/BaseDraggableComponent.cs
We noticed that after using the `DropContainer`/`DropZone` component all pages having (large) tables became very slow. As soon as the JS module has been initialized all table rows call the destroyThrottledDragEvents method (drapDrop.js:37) on `DisposeAsync`. If the table has 200 rows, the method is called at least 200 times (via RPC/SignalR Blazor server side <-> Browser).
The problem persists until the user opens a new session - reason: `JSDragDropModule` is registered as a scoped service and therefore holds state.
=> Prevent large performance hits after using the DropContainer/DropZone component

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Code/ITextLocalizerServiceExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Examples/ITextLocalizerServiceExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/LocalizationPage.razor, Tests/Blazorise.Tests/Components/DataGridComponentTest.cs
Fixes the recurring issue where our docs application would keep the language state application wide by changing our example to not set the default thread culture to the selected language/culture.
Added a note about this in the docs.
=> Fix Docs ITextLocalizerService changing the culture application wide

Source/Blazorise/wwwroot/fileEdit.js
Reason was because an operation that generated a js change event, would notify blazor of new ids for existing files, making it so any state was lost instead of kept.
This fixes the issue where state wasn't kept by just assigning new ids to files without id.
Issue was in the `FileEdit`, but it was more noticeable in `FilePicker` since it's more likely to be used with multiple files.
This is the kind of code user reported was not working as expected, but the issue could also be seen by going to the `FilePicker` page, adding various files, upload them all, and seeing, that for example, when a file was removed, the other files would loose state.
```
<Field>
<FilePicker @ref=filePicker Multiple Upload="OnFileUpload" ShowMode="FilePickerShowMode.List" />
</Field>
<Button …
```
=> FileEdit | Prefer to coalesce file ids so file ids persist

Documentation/Blazorise.Docs/Pages/Docs/Components/Dropdowns/DropdownPage.razor, Documentation/Blazorise.Docs/Pages/News/2023-08-16-release-notes-130.razor, Source/Blazorise/Components/Dropdown/Dropdown.razor.cs, Source/Extensions/Blazorise.Components/Autocomplete.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Well I had to introduce an anchorid to tell it to anchor off the input. What do you think?
=> Autocomplete: Fix dropdown menu being anchored incorrectly

Build/Blazorise.props, Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Code/CustomLanguageExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Examples/CustomLanguageExample.razor
It seems like there was another place where users could mutate the server thread culture, no wonder it was in polish.
=> Prevent Server Thread Culture from being mutated in docs example

Documentation/Blazorise.Docs/Layouts/DocsLayout.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Fixed the issue by pre generating the Id instead.
`Position.Absolute` strategy was removed from the docs menu and left the default instead.
=> Autocomplete: Fix DropdownMenuTargetId race condition by pre allocating elementId on Initialization

Source/Extensions/Blazorise.Components/Autocomplete.razor, Tests/BasicTestApp.Client/Autocomplete_5038Component.razor, Tests/Blazorise.E2E.Tests/Tests/Extensions/Autocomplete/Autocomplete_5038_Tests.cs
Code provided by user which is also found on the added test:
```
<h3>AutocompleteTest</h3>
<Autocomplete TItem="string"
Data="@colors"
Placeholder="Search..."
Filter="AutocompleteFilter.StartsWith"
FreeTyping=true
TextField="@(( item ) => item)"
ValueField="@(( item ) => item)">
<FreeTypingNotFoundTemplate>
Sorry... @context was not found! :(
</FreeTypingNotFoundTemplate>
@code {
private List<string> colors = new List<string>
{
"Red",
"Orange",
"Yellow",
"Bright Green",
"Dark Green",
"Sky Blue",
"Blue",
"Purple",
"Hot Pink",
"Black",
"White",
"Gray"
};
}
```
=> Autocomplete | Fix FreeTypingNotFoundTemplate not showing

Source/Extensions/Blazorise.RichTextEdit/JSRichTextEditModule.cs
We see from time to time some RTE errors in or logging and I traced it back to JS disconnects. I changed the JS calls to safe invocations and also made the initialize routine safe
=> RichTextEdit: Safe loading and invocation

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs, Source/Extensions/Blazorise.DataGrid/DataGridSelectColumn.cs
Code to test:
```
<DataGrid TItem="Employee" Data="@employeeList" PageSize="5" Responsive Editable Filterable EditMode="DataGridEditMode.Popup">
<DataGridSelectColumn TItem="Employee" Field="@nameof( Employee.Role )" Caption="Gender" Editable
Data="RolesNamesSource" ValueField="(x) => ((UsersRoles)Enum.Parse(typeof(UsersRoles), (string)x))" TextField="(x) => (string)x" />
<DataGridCommandColumn />
</DataGrid>
@code {
private List<Employee> employeeList = new List<Employee>() { new Employee( UsersRoles.Standard ), new Employee( UsersRoles.Premium ), new Employee( UsersRoles.Admin ) };
private List<string> RolesNamesSource = Enum.GetNames( typeof( UsersRoles ) ).ToList();
protected override void OnInitialized()
{
base.OnInitialized();
}
class Employee
{
public Employee( UsersRoles role )
{ …
```
=> DataGridSelectColumn: SetValue, consider ValueField if set

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Code/DataGridVirtualizeExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Examples/DataGridVirtualizeExample.razor
Does not fully close the issue, as user mentioned an additional issue where `DataGridHeight` & `DataGridMaxHeight` would not work. We await further feedback pertaining that issue as these seem to be working correctly.
=> Docs : DataGrid Virtualize Example | Set a fixed row height

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/DataGridApi.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Closes #5184
The culprit was not in #5184 example, but I'm just referencing it so that we can close the ticket.
As far as I was able to figure, the problem could be in the client possibly not having full-trust on their runtime objects. So DeepClone would fail. You can read about it on https://github.com/force-net/DeepCloner?tab=readme-ov-file#limitation
This PR introduces a new `CloneItemCreator` API. I am aware that we usually don't allow adding new APIs into existing versions but this time it was needed. I was able to test it on the client code and the change is working. On their side I just implement it as
```cs
MulticastAllocationEntry OnCloneItemCreator(MulticastAllocationEntry item)
{
return item.ShallowClone();
}
```
=> DataGrid: introduce CloneItemCreator parameter

Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
closes #5188 
Here, I have tried everything I know to fix it, so when I put these classes in the theme provider, they are not added, even though by all logical parameters they should be added to the ant-menu... when I manually add these same classes inside scss -a, everything works without problems, take a look and give me some advice because I really don't see what the problem is with this approach
=> ThemeProvider: Fix generator for Bar background color

Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor, Source/Extensions/Blazorise.DataGrid/_DataGridCellNumericEdit.razor
Readding the entries for the dynamic numeric inputs. I'm not sure why we removed it, I think it was a mistake, because people might still use `DataGridColumn` with a numeric value as opposed to a `DataGridNumericColumn`
=> DataGridCellEdit | ReAdd entries for dynamic numeric inputs

Source/Blazorise.Bulma/CarouselSlide.cs, Source/Blazorise.Bulma/Config.cs, Source/Blazorise.Material/CarouselSlide.cs, Source/Blazorise.Material/Config.cs, Source/Blazorise.Tailwind/CarouselSlide.cs, Source/Blazorise.Tailwind/Config.cs, Source/Blazorise/Components/Carousel/Carousel.razor.cs, Source/Blazorise/Components/Carousel/CarouselSlide.razor.cs
From my tests, this greatly improves responsiveness when switching between slides. The problem was that we were only setting the Animation to being ended after 2s. I'm not sure why we decided on that, seems like an oversight.
Notes:
- **AntDesign** is blocked from testing due to https://github.com/Megabit/Blazorise/issues/5222
- **Bulma** seems to have no animations, I'm not sure if it's intended or not, but it doesn't affect the viability of this PR. For now we made it so it considers bulma as having no animation, so it is very snappy when switching between slides with no animation.
- https://github.com/Megabit/Blazorise/issues/5223
=> Carousel | Improve previous/next slide transition responsiveness

Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Basically this fixes an issue where if `RowSelectable` evaluated to false, then `DetailRowTrigger` would not happen. 
`RowSelectable` should only affect whether the row is selectable or not as the naming implies.
As for the feature the user requested, **Trigger only DetailRow upon RowClick and not upon MultiSelect click**
- There is currently no way to know in the `DetailRowTriggerEventArgs` whether it was a multi select click or just a regular row click. We can think of introducing a new `DetailRowTriggerType.MultiSelectClick` in the next version.
- Other than that a workaround will be provided to the user.
**Test Code:**
```
<DataGrid TItem=PositionAllocationViewModel Data=data SelectionMode="DataGridSelectionMode.Multiple" @bind-SelectedRows=SelectedPositions …
```
=> Fix DetailRowTrigger not triggering when RowSelectable evaluates to false

Source/Blazorise/wwwroot/fileEdit.js, Source/Blazorise/wwwroot/filePicker.js
`FilePicker` should now handle disabled and not allow the drop of files.
I did not make any changes to `ReadOnly`, as currently it seems the `ReadOnly` has no effect on the input file, and still allows regular click to browse files.
=> FileEdit / FilePicker handle fileinput disabled

Documentation/Blazorise.Docs/Pages/Docs/Components/Tables/TablePage.razor, Documentation/Blazorise.Docs/Pages/News/2024-03-31-release-notes-150.razor, Source/Blazorise/Components/Table/TableRowCell.razor, Source/Blazorise/Components/Table/TableRowCell.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
It seems we have removed mistakenly the stopPropagation attribute before when implementing a new feature.
Razor components do not support having both @onlick, @onlick:stopPropagation so you need to use an actual Parameter and set it on the html element.
=> DataGrid : Column Preventrowclick does not work anymore 

Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs
Issue was that `IntervalBeforeClose` was being summed with null and being turned into null
=> SnackbarInfo Initialize IntervalBeforeClose correctly

Source/Blazorise/Interfaces/IModalService.cs, Source/Blazorise/Services/ModalService.cs
More info is found in the github issue.
Added where `TComponent : notnull, IComponent` to the `TComponent` version. While it is in theory a breaking change. If users use a non `IComponent` it will just throw an exception as it's not valid for blazor rendering.
What's notable is that we specifically capture the parameters setter provided by the user:
=> Modalprovider loses parameter reference when closing popup

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
This should keep the autocomplete open when unselecting items.
This does not seem necessary for Multiple at all. Since the selection is applied to badges and not the input/text itself.
=> Autocomplete: Only ResyncText if not Multiple

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs
The problem is that item references get updated between tabbing. 
And Batch Edit works such that a batch edit item is patched through to the row.
The solution is not pretty, we just reattempt to get the correct reference before the item is updated each time. 
But hey... it works...
=> Datagrid: Fix Batch Edit With CellEdit

Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataGridPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/DataGridApi.razor, Documentation/Blazorise.Docs/Pages/News/2024-02-15-release-notes-150.razor, Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs, Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor
Although it's redundant for most columns since `DisplayTemplate` already exists in the `AggregateColumn`.  
This best allows to configure each column individually including the Command and multi select columns and any additional special column we might introduce.
Maybe in the future we could consider in removing the `Aggregate` Column `DisplayTemplate` instead? 
What do you think? 
Even the AggregateColumns definition could possibly be moved to the DataGridColumn, making the definition more centralized. 
However I have to say I personally do like the separation.
=> DataGridColumn: Add AggregateTemplate

Documentation/Blazorise.Docs/Pages/News/2024-02-15-release-notes-150.razor, Source/Extensions/Blazorise.RichTextEdit/RichTextEditOptions.cs
Closes #5032
It seems there are no breaking changes for the features that we use, according to https://quilljs.com/guides/upgrading-to-2-0
@njannink would you be available for a quick test of this update?
=> RichTextEdit: update to latest QuillJS

Source/Blazorise/wwwroot/datePicker.js
First of all thanks for maintaining this library!
When updating from Blazorise 1.3.3 to the newest 1.4.3, we started to notice the following error logs in the console:
```
datePicker.js?v=1.4.3.0:118 Uncaught ReferenceError: flatpickrWrapper is not defined
at ClassWatcher.successClassAddHandler [as classAddedCallback] (datePicker.js?v=1.4.3.0:118:17)
at MutationObserver.mutationCallback (observer.js?v=1.4.3.0:90:30)
```
The component behavior seems to still be as excepted though.
I suspect that this is because in #5093 the successClassAddHandler functions were moved outside of the scope where the flatpickrWrapper is available. In the PR I unfortunately wasn't able to see why this was changed. The PR seems to me a bit unrelated to those functions.
I'm very open to change the PR if my …
=> DatePicker: Fix flatpickrWrapper is not defined error

Demos/Blazorise.Demo/Pages/Tests/TreeViewPage.razor, Demos/Blazorise.Demo/Pages/Tests/TreeViewPage.razor.cs, Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Extensions/TreeView/Code/TreeViewContextMenuExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Extensions/TreeView/Examples/TreeViewContextMenuExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/TreeView/TreeViewPage.razor, Documentation/Blazorise.Docs/Pages/News/2024-02-15-release-notes-150.razor, Source/Extensions/Blazorise.TreeView/EventArguments/TreeViewNodeMouseEventArgs.cs, Source/Extensions/Blazorise.TreeView/Internal/_TreeViewNode.razor, Source/Extensions/Blazorise.TreeView/Internal/_TreeViewNode.razor.cs, Source/Extensions/Blazorise.TreeView/TreeView.razor, Source/Extensions/Blazorise.TreeView/TreeView.razor.cs
Closes #5353
I used the MouseEventArgs instead of BLMouseEventArgs because I think we must abandon BLMouseEventArgs in the long run.
=> TreeView: Context Menu API

.github/workflows/dev-release.yml
Might as well delete the 1.5 dev package versions as they are no longer required.
=> Increment dev release version

Source/Blazorise/Components/Select/Select.razor.cs
Code to reproduce/test : 
```
<SelectList TItem="string"
Data="@(new List<string>{"1,9", "4", "78,4"})"
Multiple
TextField='@((item)=>item)'
ValueField="@((item)=>item)"
@bind-SelectedValues="@aux"
Class="form-select" />
<Text>@string.Join( ',', aux )</Text>
@code
{
IReadOnlyList<string> aux = new List<string>();
}
```
=> Select: Change MULTIPLE_DELIMITER to |~|

Demos/Blazorise.Demo/Pages/Tests/DataGrid/GroupMultiplePage.razor, Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor
To test just go to the https://localhost:5001/tests/datagrid/group/multiple page. 
There's grouping + nesting enabled + aggregates.
=> DataGrid: Fix AggregateRow missing group indentation

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/DataGridApi.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
To Test:
User is now able to disable the feature and make his own dynamic implementation at will.
```
<Button Color="Color.Primary" Clicked="AddColumns">Add dynamic columns</Button>
<DataGrid TItem="Book"
Data="@Books"
Responsive
ShowPager
ShowPageSizes
AutoGenerateColumns=false>
@if ( Columns != null )
{
@foreach ( var column in Columns )
{
<DataGridColumn TItem="Book" Field="@column.Key" Caption="@column.Value">
</DataGridColumn>
}
}
</DataGridColumns>
</DataGrid>
@code {
public class Book
{
public string Name { get; set; }
public string Author { get; set; }
}
List<Book> Books = new();
Dictionary<string, string> Columns;
Task AddColumns()
{
Columns = new Dictionary<string, string>
{
{ nameof(Book.Name), "Name" },
{ nameof(Book.Author), "Author" }
};
return …
```
=> DataGrid: Add AutoGenerateColumns parameter

Source/Blazorise/Base/BaseComponent.cs, Source/Blazorise/Licensing/BlazoriseLicenseChecker.cs, Source/Blazorise/Licensing/BlazoriseLicensePrintResult.cs, Source/Blazorise/Licensing/BlazoriseLicenseProvider.cs, Source/Blazorise/Licensing/WebAssemblyRsaExtensions.cs
I decided to add a separate `BlazoriseLicensePrintResult` so we don't mix logic as much
=> Licensing messages based on license state

Source/Extensions/Blazorise.Video/wwwroot/video.js
Closes #5478
Test code:
```
<Video Source="@("https://cdn.bitmovin.com/content/assets/art-of-motion_drm/mpds/11331.mpd")"
StreamingLibrary="StreamingLibrary.Dash"
ProtectionType="VideoProtectionType.Widevine"
ProtectionServerUrl="https://cwip-shaka-proxy.appspot.com/no_auth" />
```
=> Video: omit X-AxDRM-Message if httpRequestHeaders are undefined

Documentation/Blazorise.Docs/Pages/News/2024-07-15-release-notes-160.razor, Source/Blazorise.AntDesign/Components/CardLink.razor, Source/Blazorise.Tailwind/Components/_BarOnlyLink.razor, Source/Blazorise/Base/BaseLinkComponent.cs, Source/Blazorise/Components/Bar/BarLink.razor.cs, Source/Blazorise/Components/Breadcrumb/BreadcrumbLink.razor.cs, Source/Blazorise/Components/Card/CardLink.razor, Source/Blazorise/Components/Link/Anchor.razor, Source/Blazorise/Components/Link/Link.razor
Closes #5565
ChatGPT explained it better
When setting the Target attribute of a link to _blank in the Blazorise Link component, it is crucial to include the rel attribute to prevent potential security risks and improve SEO. The options provided are:
- rel="nofollow noreferrer"
- rel="noopener noreferrer nofollow"
- rel="noopener noreferrer"
Here's an analysis of each option:
- nofollow: Tells search engines not to follow the link, preventing the transfer of SEO value to the linked page.
- noreferrer: Prevents the browser from sending the referrer information to the target site.
- noopener: Ensures that the new page runs in a separate process, which prevents the new page from being able to access the window.opener property and potentially gain control over the original page.
- noreferrer: …
=> Link: automatically add rel tag

Documentation/Blazorise.Docs/Pages/Docs/Components/Links/LinkPage.razor, Source/Blazorise.AntDesign/Components/BarLink.razor, Source/Blazorise.Tailwind/Components/BarLink.razor, Source/Blazorise/Components/Bar/BarLink.razor, Source/Blazorise/Components/Bar/BarLink.razor.cs, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor, Source/Extensions/Blazorise.Sidebar/SidebarLink.razor.cs
Closes #5567
I also added the same on SidebarLink.
=> BarLink: add missing CustomMatch parameter

Documentation/Blazorise.Docs/Pages/Docs/Components/Buttons/ButtonPage.razor
Closes #5590
small typo on the docs page about the buttons
=> Fixed typo in ButtonPage.razor

Source/Extensions/Blazorise.Charts.Streaming/ChartStreamingOptions.cs
the type of the Delay property of ChartStreamingOptions from int? to long?
Closes #5615
=> ChartStreamingOptions: Change delay from int? to long?

Source/Blazorise/Licensing/BlazoriseLicenseChecker.cs, Source/Blazorise/Licensing/BlazoriseLicenseLimitsHelper.cs, Source/Blazorise/Licensing/BlazoriseLicenseProvider.cs, Source/Extensions/Blazorise.Charts/BaseChart.cs, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs, Source/Extensions/Blazorise.Components/ListView.razor.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Source/Extensions/Blazorise.TreeView/TreeView.razor.cs
Well it is not the first time we hear about someone complaining about a null in `BlazoriseLicenseChecker`.
Although typically this should not be null as per our standard **Blazorise** registration.
This should make sure that users can't try to game the system by removing the service from the DI Container, by assuming the user as unlicensed if `BlazoriseLicenseChecker` is null.
Also gives the flexibility for users to initialize the services themselves, and if they happen to not initialize the `BlazoriseLicenseChecker`, then we still don't throw an exception, but still apply our limits.
The naming of the class can change if you wish, I went back and forth with a few but ultimately, stating that the purpose of it is related to `BlazoriseLicenseLimits` seems fine, the suffix can change if you …
=> BlazoriseLicenseChecker: Null checks and apply defaults for unlicensed limits

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
The problem was that `DisplayableColumns` was now binding a different reference each time, and the `DataGridRow` is only aware of the first reference that is bound : 
By using yield return we should basically get the same reference and the columns just adjust accordingly.
**Testing code :** 
```
<DataGrid TItem="Employee"
Data="inMemoryData"
ShowPager
ShowPageSizes
ShowHeaderGroupCaptions
ShowColumnChooser>
<DataGridColumn DisplayOrder=2 TItem="Employee" Field="@nameof( Employee.LastName )" HeaderGroupCaption="PersonalInfo" Caption="Last Name" />
<DataGridColumn TextAlignment="TextAlignment.Center" TItem="Employee" Field="@nameof( Employee.Id )" Caption="#" Width="60px" />
<DataGridColumn TItem="Employee" Field="@nameof( Employee.FirstName )" …
```
=> DataGrid: fix HeaderGroupCaption and Displayable not working properly together

Source/Extensions/Blazorise.Components/TransferList.razor.cs
- Fixes an issue where if the user provides `Items` and both **start** and **end** lists are **empty**. Then the Items was assigned by reference to `ItemsStart` causing it to mutate on internal changes.
=> TransferList: Do not mutate the Items collection

Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor, Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
This should make it so that when the field is left or committed our internal check does not reset the value because it does not find a matching value.
So basically now we have a `GetItemValues` and `GetItemsByText` so we can get multiple items / values out of a single text.
**Testing Code:**
```
<Row>
<Column ColumnSize="ColumnSize.IsFull.OnMobile.IsHalf.OnTablet">
<Card Margin="Margin.Is4.OnY">
<CardHeader>
<CardTitle>Autocomplete</CardTitle>
</CardHeader>
<CardBody>
<Field Horizontal JustifyContent="JustifyContent.End">
<FieldLabel ColumnSize="ColumnSize.Is2">Select Value</FieldLabel>
<FieldBody ColumnSize="ColumnSize.Is10">
<Autocomplete TItem="Country"
Data="@Countries"
TextField="@(( item ) => item.Name)"
ValueField="@((item) => item.Iso)" …
```
=> Autocomplete: Allow repeated texts

Source/Extensions/Blazorise.Cropper/wwwroot/blazorise.cropper.js
Properly destroy Cropper in javascript
- `.destroy()` from cropper.js
- remove blazorise js event listeners
=> Cropper: Properly destroy and unregister events

Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/ValidationPage.razor, Source/Blazorise/Components/Validation/ValidationRule.cs
Closes #5690
I have, by mistake, added some validation helper APIs that are not supported.
=> Remove validator APIs that are not supported

Source/Blazorise/Base/BaseComponent.cs, Source/Blazorise/Base/BaseInputComponent.razor.cs, Source/Blazorise/Base/BaseTextInput.razor.cs, Source/Blazorise/Components/Check/Check.razor.cs, Source/Blazorise/Components/ColorEdit/ColorEdit.razor.cs, Source/Blazorise/Components/ColorPicker/ColorPicker.razor.cs, Source/Blazorise/Components/DateEdit/DateEdit.razor.cs, Source/Blazorise/Components/DatePicker/DatePicker.razor.cs, Source/Blazorise/Components/InputMask/InputMask.razor.cs, Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs, Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs, Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs, Source/Blazorise/Components/Radio/RadioGroup.razor.cs, Source/Blazorise/Components/Select/Select.razor.cs, Source/Blazorise/Components/Slider/Slider.razor.cs, Source/Blazorise/Components/Switch/Switch.razor.cs, Source/Blazorise/Components/TextEdit/TextEdit.razor.cs, Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs, Source/Blazorise/Components/TimePicker/TimePicker.razor.cs, Source/Blazorise/Extensions/ParameterExtensions.cs, Source/Blazorise/Models/ComponentParameterInfo.cs
A refactor of the input component lifecycle was used during the initialization process. I have made use of the prototype from https://github.com/Megabit/Blazorise/pull/4308 that was meant to keep track of parameters. 
So far all tests are passing and there are no issues as far as see. If all goes as planned, I will merge it into the larger API refactor branch.
=> Refactor input components initialization

Demos/Blazorise.Demo/Pages/Tests/ChartsPage.razor.cs, Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor, Source/Extensions/Blazorise.Charts/Options/ChartPlugins.cs, Source/Extensions/Blazorise.Charts/Options/ChartPointStyle.cs, Source/Extensions/Blazorise.Charts/Options/ChartTooltip.cs, Source/Extensions/Blazorise.Charts/Options/ChartTooltipCallbacks.cs, Source/Extensions/Blazorise.Charts/Options/ChartTooltipItemContext.cs, Source/Extensions/Blazorise.Charts/wwwroot/charts.js
Closes #5741
Added all callbacks from https://www.chartjs.org/docs/3.7.1/configuration/tooltip.html#tooltip-callbacks
As in other parts of the code I have used `LambdaConverter` that converts C# to JS code. For simple tasks it seems to work as expected. 
```cs
ChartOptions chartOptions = new()
{
AspectRatio = 1.5,
Plugins = new ChartPlugins()
{
Tooltip = new ChartTooltip()
{
Enabled = true,
UsePointStyle = true,
Callbacks = new ChartTooltipCallbacks
{
Title = ( items ) => "Custom title: " + items[0].Parsed,
Label = ( item ) => "Custom label: " + item.Parsed,
}
}
}
};
```
The only problem is that the `Parsed` of the `ChartTooltipItemContext` can only be defined as `object` type. We cannot do something like `Title = ( items ) => "Custom title: " + items[0].Parsed.x,` because `object` is …
=> Chart: add callbacks to tooltip options

Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor, Source/Blazorise.AntDesign/Providers/AntDesignClassProvider.cs, Source/Blazorise.Bootstrap/Providers/BootstrapClassProvider.cs, Source/Blazorise.Bootstrap5/Providers/Bootstrap5ClassProvider.cs, Source/Blazorise.Bulma/Providers/BulmaClassProvider.cs, Source/Blazorise.FluentUI2/Providers/FluentUI2ClassProvider.cs, Source/Blazorise.Tailwind/Providers/TailwindClassProvider.cs, Source/Blazorise/Fluent/FluentFlex.cs, Source/Blazorise/Interfaces/IClassProvider.cs, Source/Blazorise/Providers/ClassProvider.cs, Source/Blazorise/Providers/EmptyClassProvider.cs
I wanted to define some special flex rules while trying to improve our docs, but I realized it wasn't working.
**Example:**
`<Div Flex="Flex.Default.OnDesktop.Flex.ReverseRow.OnDesktop.JustifyContent.Between.AlignItems.Center">`
After some investigation, I found the problem. The breakpoint was defined on a flex definition level. Not on a flex rule itself. This made it very hard to do work with. So I went and refactor internals of flex utilities to allow.
- Multiple flex types
- Breakpoint for each flex type
- New `IFluentFlexAll Default` alias for default flex type
=> Flex utilities: improve breakpoint rules

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/NewFilesToBuild.txt, Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Code/DatePickerEnabledDatesExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/DatePickerPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Examples/DatePickerEnabledDatesExample.razor, Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor, Source/Blazorise/Components/DatePicker/DatePicker.razor.cs, Source/Blazorise/wwwroot/datePicker.js, Source/Blazorise/wwwroot/utilities.js
Enabled dates in DatePicker.
Few consideration:
- Empty array means "no dates are enabled". For changing from "some enabled dates" to "enable all dates" we need to set the EnabledDates param to null (there are workarounds).. Which will eventually run this code 
```js
//datepicker.js
picker.set("_enable", undefined);
```
which sets the internal property to undefined. Which is kind of hackie solution (others didn't work), but I didn't noticed any side effects.. Other option is to make all the dates enabled, but this will mess up the dotnet-js synchronization. Note that this code will only run when you set the EnabledDates to null and they were previously set to non-null array. 
- In release notes I fixed heading for my previous PR. Doesn't belong here, but is just a small update. 
Closes …
=> DatePicker: add EnabledDates parameter

Documentation/Blazorise.Docs/Components/Commercial/PlansComparer.razor, Documentation/Blazorise.Docs/Components/LicenseLimitationAlert.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartDataLabels/ChartDataLabelsPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartStreaming/ChartStreamingPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartTrendline/ChartTrendlinePage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartsAnnotation/ChartAnnotationPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartsZoom/ChartsZoomPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Index.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/LicenseLimitation.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/ListView/ListViewPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/TreeView/TreeViewPage.razor, Source/Blazorise/Licensing/BlazoriseLicenseProvider.cs
Closes #5797
- Alert in every limited component
- pricing table uses the constants from `BlazoriseLicenseProvider` (these should be in sync). Thus the table has changed its values. New table:
- the `TransferList` has not the constant in `BlazoriseLicenseProvider` and its limitation doesn't appear to be enforced. So:
- (a) Remove the TransferList from pricing table.
- (b) Create the constant and enforce the limitation.
=> Docs: Components which require a Blazorise license

Source/Blazorise.AntDesign/Providers/AntDesignClassProvider.cs, Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
- partially solves #5375 - the paginator problem.
- first is fix for ant design, that's why this is in dev not in support. Prior to this - Ant Design had wrong display on xs. Which resulted for example in: 
https://github.com/user-attachments/assets/1587e9a3-4e98-4973-9089-edb33ffe08c0  
(pages in paginator disappears between xs-sm, but again appear under xs)
- the not centered number are solved by `justify-content:center;`  this is because of the container being `inline-flex`.
=> DataGrid: Fix paginator items alignment

Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor.cs
**Testing Code:**
```
@page "/"
@inject IVersionProvider VersionProvider
<h3>DetailRowPage - Displayable</h3>
<p>On this page we use the Displayable="false" attribute on the "Status" column, as you can see when openening the detailrow the Grid collapses...</p>
<DataGrid @ref="gridRef"
TItem="ExampleVMDisplayable"
Data="ExampleVMs"
PageSize="200"
Filterable=true
FilterMethod="DataGridFilterMethod.Contains"
Responsive
SortMode="DataGridSortMode.Single"
FixedColumns
DetailRowTrigger="@((context) => OnDetailRowTrigger(context, ExpandedSubrowsForVanId))"
Class="table-max-width">
<DataGridSelectColumn Field="@nameof(ExampleVMDisplayable.Id)"
Filterable=false
Sortable=false
Width="33px"
FixedPosition="TableColumnFixedPosition.Start">
<DisplayTemplate>
@if …
```
=> DataGrid: DataGridDetailRow | Consider only Displayable columns for ColumnSpan 

Source/Extensions/Blazorise.Markdown/Markdown.razor.cs, Source/Extensions/Blazorise.Markdown/MarkdownJSOptions.cs
=> Markdown: add missing ToolbarButtonClassPrefix JS option

Source/Blazorise/wwwroot/table.js
Closes #5907, #5904, #5216
While trying to come up with a solution to resizing in responsive mode, I noticed that we just need to define `minWidth` and `maxWidth` to make it work. After that I added a check to disable resizing if the user had explicitly defined min/max width.
**Pros**: it works as expected now
**Cons**: for fixed columns, the user should explicitly define HeaderCellStyle
**Test code:**
```
<DataGrid TItem="Employee"
Data="@employeeList"
@bind-SelectedRow="@selectedEmployee"
Responsive
Resizable
ResizeMode="TableResizeMode.Columns">
<DataGridCommandColumn />
<DataGridColumn Field="@nameof(Employee.Id)" Caption="#" Sortable="false" Width="400px" CellStyle="@((item)=>"min-width:400px;max-width:400px;")" HeaderCellStyle="min-width:400px;max-width:400px" />
<DataGridColumn …
```
=> Table: fix resizing of columns in responsive mode

Source/Extensions/Blazorise.PdfViewer/Extensions/EnumExtensions.cs
Closes #5899
The rotation on landscape was `-90`, but it should be `90`.. I tested on different landscape pdf. But I am not sure if there was something behind the minus initially..(??) 
Maybe would be interesting to add `ReversePortrait` and `ReverseLandscape` orientations too. For the cases where orientation is somehow messed up by default... or maybe even the autorotate (as most of the pdf viewers have) - the underlying lib should support that.
=> PdfViewer: Landscape orientation fix

Source/Blazorise/Components/Table/TableHeaderCell.razor, Source/Blazorise/Components/Table/TableHeaderCell.razor.cs, Source/Blazorise/Components/Table/TableRowCell.razor, Source/Blazorise/Components/Table/TableRowCell.razor.cs, Source/Blazorise/wwwroot/table.js
Closes https://blazorise.com/support/issues/238/help-understanding-datagrid-column-sizing
In my previous fix I have only disabled resizing of columns that have `min-width` and `max-width`. With this fix, I also disabled resizer for columns that have FixedPosition defined.
=> Table: don't resize columns with FixedPosition

Source/Blazorise.Bootstrap5/wwwroot/modal.js
Closes #5911  
When a modal is opened, the scrollbar on the body is removed. The emphasis here is on "on the body," as many sites, including [blazorise.com](https://blazorise.com), the demo sites, and numerous other web pages, don’t use the body as the main scrolling element. 
Currently, the solution is implemented for Bootstrap 5, but I need clarification on a few points before proceeding with other providers.  
The scrollbar-hiding functionality is based on Bootstrap's [scrollbar.js](https://github.com/twbs/bootstrap/blob/main/js/src/util/scrollbar.js). It seems that Blazorise already has parts of this functionality implemented in `modal.js` for the Bootstrap 5, Bootstrap, and Tailwind providers.  
Most of the code in [modal.js](https://github.com/Megabit/Blazorise/blob/458799c524ca5f1f0 …
=> Modal: Hides scrollbar on modal.Show()

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/Code/AutocompleteVirtualizeAndReadDataExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/Examples/AutocompleteVirtualizeAndReadDataExample.razor
=> Docs: Virtualize and ReadData example for Autocomplete

.github/workflows/blazorise-ci-basic.yml, Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Code/DataGridDetailRowTemplateExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Examples/DataGridDetailRowTemplateExample.razor
Closes #4745
Adds sample code that demonstrates two functionalities:
- How to distinguish between an opened and a closed detail row.
- How to indicate when a detail row can be expanded.
While the implementation works, it may not fully address the original discussion, `Datagrid check if detailrow is displayed`.
Currently, there is no straightforward way to achieve this. The current solution relies on tracking "which rows have been clicked," which is indirectly tied to the detail row display. This approach is fragile and can easily break, especially when manual triggers for detail rows are added.
A better solution could involve exposing `DataGridRowInfo.HasDetailRow` by making `DataGrid.GetRowInfo` public and optimizing its performance.
???
=> Docs: DetailRow samples update

Source/Blazorise/wwwroot/memoEdit.js
Fixes problem with auto size showing the scrollbar
> Another question: We have the issue that a memoedit with Autosize=”true” shows a scrollbar. Its height is a few pixels too small. This is especially a problem because the scrollbar hides the green check-mark of a validation in the top right corner. I saw this has been an issue in an earlier version of Blazorise and has been fixed. Is it possible this issue has been re-introduced in 1.7?
Test code:
```razor
<Div>
<MemoEdit Text="@memoText"
Size="Size.Small"
TextWeight="TextWeight.Light"
ReplaceTab="true"
AutoSize="true"
Overflow="Overflow.Auto"
ReadOnly="false">
</MemoEdit>
</Div>
<Button Clicked="SetText">Set Text</Button>
@code {
private string memoText;
private void SetText()
{
var emp = new Employee { Id = 1, FirstName = "Alexander …
```
=> MemoEdit: include border size when autosizing

Source/Blazorise/Utilities/Formatters/Parsers.cs
Closes #5953
Fixes the date parser by adding the seconds part.
```
<Div>
<Paragraph>
<DateEdit TValue="DateTime?" InputMode="DateInputMode.DateTime" @bind-Date="@DateValue" />
</Paragraph>
<Paragraph>
@DateValue
</Paragraph>
</Div>
<Div>
<Paragraph>
<DateEdit TValue="DateTime?" InputMode="DateInputMode.Date" @bind-Date="@Date" />
</Paragraph>
<Paragraph>
@Date
</Paragraph>
</Div>
@code {
private DateTime? DateValue { get; set; } = DateTime.Today.Add(new TimeSpan(18, 03, 24));
private DateTime? Date { get; set; } = DateTime.Today.Add(new TimeSpan(18, 03, 24));
}
```
=> DateEdit: properly parse the seconds part

.github/workflows/blazorise-ci-basic.yml, Tests/Blazorise.Tests/DataGrid/Utils/FunctionCompilerTests.cs
Original problem: https://github.com/Megabit/Blazorise/pull/5940#issuecomment-2601019373
The error was this:
```
Assert.Equal() Failure: Strings differ
↓ (pos 19)
Expected: "12/31/9999 11:59:59 PM"
Actual:   "12/31/9999 11:59:59 PM"
↑ (pos 19)
```
Explanation:
```
At position 19, the space before "PM" is different:
The expected value has a regular space (U+0020).
The actual value has a narrow no-break space (U+202F), which looks visually similar but is a different Unicode character.
```
It is culture dependent. I don't exactly know why that was happening in ubuntu 24 not 22...
This  fix makes the tests more deterministic.
I re-discovered the issue by an accident. And fixing it till it's in fresh memory...
=> Devops: fix action for ubuntu-latest and invariant culture in tests

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Markdown/MarkdownPage.razor, Source/Extensions/Blazorise.Markdown/wwwroot/markdown.js
Closes #5961
This effectively fixes the issue. The previous implementation overwrote the `_blazorFilesById` dictionary, which resulted in [this error](https://github.com/Megabit/Blazorise/blob/bd5b05a8e27a51861b7b6476e42a6930598ff1fe/Source/Blazorise/wwwroot/io.js#L46)  
when calling `await file.WriteToStreamAsync(memoryStream);`
The fix works, but there are plenty of areas for improvement.
- As @linkdotnet pointed out in the issue, files are processed one by one, even though `FileChangedEventArgs` supports multiple files at once. This behavior originates from the underlying Easy Markdown Editor and its `imageUploadFunction`, which handles only one file at a time. The relevant implementation is here:  
[EasyMDE source](https://github.com/Ionaru/easy-markdown-editor/blob/fe680f09f66357243db …
=> Markdown: ImageUploadChanged with multiple files fix

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs, Source/Extensions/Blazorise.DataGrid/wwwroot/datagrid.js
Closes #5978
In the end just acknowledging the escape in focus handling was enough
=> DataGrid: refocus to cell when pressed Escape in RapitEdit mode

Source/Blazorise/Components/FileEdit/FileEdit.razor.cs, Source/Blazorise/Components/FilePicker/FilePicker.razor, Source/Blazorise/Components/FilePicker/FilePicker.razor.cs, Source/Blazorise/Interfaces/Modules/IJSFileModule.cs, Source/Blazorise/Modules/JSFileModule.cs, Source/Blazorise/Utilities/IO/IFileEntryOwner.cs, Source/Blazorise/Utilities/IO/RemoteFileEntryStreamReader.cs, Source/Blazorise/wwwroot/fileEdit.js, Source/Blazorise/wwwroot/io.js, Source/Extensions/Blazorise.Markdown/Markdown.razor.cs, Source/Extensions/Blazorise.Markdown/wwwroot/markdown.js
Further improves on #5980
I have changed how `removeFileEntry` is called. Now, it removes all entries when the component is destroyed and when the file(s) is changed. If there were previous file entries, then it will remove them.
I have also deleted `RemoveFileEntry` as it didn't make sense to keep it.
=> FilePicker and Markdown: Remove file entries on destroy and file change event

Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor, Source/Extensions/Blazorise.PdfViewer/PdfViewer.razor.cs
Hello, thank you for taking the time to read this. Thought about raising this as an issue for discussion first but as implementation was simple, thought I'd just get straight to the point.
Currently, the PdfViewer component provides a callback as a parameter for the following events:
- `Loaded`
- `PageNumberChanged`
- `ScaleChanged`
However, it does not provide a callback that can be invoked when the document is requested to be printed.
This adds a `PrintRequested` Eventcallback parameter to `PdfViewer`.
We have an application that uses `PdfViewer` in combination with `PdfViewerToolbar`. As a result, the user uses the toolbar's print button rather than a custom button that invokes `Print` directly on a reference to the PdfViewer component. Since we're not doing the latter, we can't invoke …
=> PdfViewer: Introduce PrintRequested EventCallback

Source/Extensions/Blazorise.Charts/BaseChart.cs
Race condition during initialization of the chart and setting the data might cause the chart not to render correctly. In the init routine always call the Update method to ensure that the chart is updated then it's dirty.
Closes #4317
=> Chart: fix race condition during initialization

Source/Extensions/Blazorise.Charts.Zoom/ChartZoom.razor.cs
Closes #6006  
A simple null check will prevent a null reference exception in case the loading of the parent chart is slow for some reason. More explanation is available in the related issue.  
I consider this a hotfix. Other places (for example, `ChartDataLabels`) suffer from a similar condition. However, there are many more such "suffering conditions" that might be worth fixing together.
=> Chart.Zoom: add null check to JSModule

Source/Extensions/Blazorise.Cropper/Cropper.razor.cs
Closes #6004
The `Value` was attempted to be read on null object, this just sends null when the options is not defined
=> Cropper: fix when InitialCoverage options is null

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/BindingData/DynamicPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Examples/DataGridDynamicAutoGenerateExample.razor, Source/Blazorise/Utilities/Formatters/Formaters.cs, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs, Tests/Blazorise.Tests/Utils/FormatersTests.cs
Closes #6000
Fixes the issue by changing the logic (order) of obtaining the item to discover columns. The `First` item from `Data` may have a column with a null value, which could result in the column not being displayed at all. This fix applies the `NewItemCreator` first, where the user can ensure non-null values.
=> DataGrid: Dynamic data does not create a column when value is null in the first row

Source/Blazorise/Components/FileEdit/FileEdit.razor.cs, Source/Blazorise/Utilities/IO/FileEntryStreamReader.cs, Source/Blazorise/Utilities/IO/IFileEntryOwner.cs, Source/Blazorise/Utilities/IO/RemoteFileEntryStreamReader.cs, Source/Extensions/Blazorise.Markdown/Markdown.razor.cs
Closes #5991
Now the IFileEntryOwner uses the interface IFileEntry.
I went through the code, but I don't see a reason for keeping the interface. Only the one implementation exists and it worked just fine with it. 
What's the reason to keep the interface - is there any upcoming feature that would utilize it?
The failing test isn't related to this change. It was already in here: https://github.com/Megabit/Blazorise/pull/5993/checks . Any idea?
=> IFileEntryOwner: FileEntry to IFileEntry

Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor, Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Closes #5996
Introduces the `AddItemToBatchChanges` method, enabling programmatic insertion of items into the batch edit collection when batch editing is enabled.  
It addresses the original request:  
> **"DataGrid: Functionality to clone a given row without changing the source data."**  
Rather than duplicating rows directly, this approach adds items to the batch collection, allowing them to be saved or discarded like any other batch edit change.  
Users can insert a new instance of `TItem` into the batch edit collection as shown:  
```csharp
<Button Clicked="OnAddNewRowClicked">Add new row</Button>
private async Task OnAddNewRowClicked(MouseEventArgs obj)
{
var newEmployee = new Employee
{
FirstName = "John", 
LastName = "Doe", 
Email = "john.doe@example.com",
Salary = 50000, 
Id = …
```
=> DataGrid: Add New method overload

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
This PR fixes the behavior of the `CellValueIsEditable` property in the **DataGrid** component.
- **For edit modes other than `DataGridEditMode.Cell`**: it preserves the previous behavior, ensuring no unexpected changes.  
- **For `DataGridEditMode.Cell`**: it maintains the current functionality, allowing cell-level edits as intended.  
Closes #5976.
---
Tested using the demo pages with the following properties:  
- `CellsEditableOnNewCommand="false"`  
- `CellsEditableOnEditCommand="false"`  
Validated across different `DataGridEditMode` configurations to ensure correct behavior.
---
**Bug fix** (non-breaking change that resolves the issue)
=> DataGrid: Fix CellsEditableOn behavior for edit modes other than 'Cell'

Source/Blazorise/Components/FileEdit/FileEdit.razor.cs, Source/Blazorise/Components/FilePicker/FilePicker.razor.cs, Source/Blazorise/Utilities/IO/IFileEntryOwner.cs, Source/Extensions/Blazorise.Markdown/Markdown.razor.cs
Closes #6029
Tested with Demo App
=> IFileEntryOwner: Prevent ConstructorContainsNullParameterNames when AOT Compiled

Documentation/Blazorise.Docs/Models/Snippets.cs, Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/Examples/GlobalLocalizationExample.snippet
Closes #6038
The snippet form Snippets.cs was moved into its own file, otherwise the compiler didn't pick it up for `*Code.html` generation.
=> Docs: Code block not visible on Validations page global options localization fix

Source/Blazorise.AntDesign/Components/Radio.razor, Source/Blazorise.Bootstrap/Components/Radio.razor, Source/Blazorise.Bootstrap5/Components/Radio.razor, Source/Blazorise.Bulma/Components/Radio.razor, Source/Blazorise.FluentUI2/Components/Radio.razor.cs, Source/Blazorise.Tailwind/Components/Radio.razor, Source/Blazorise/Components/Radio/Radio.razor.cs
The radio button was not properly handled in the active state when used within RadioGroup. This PR fixes it.
=> Radio: add IsActive flag

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/NewFilesToBuild.txt, Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Code/DatePickerShowWeekNumbersExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/DatePickerPage.razor, Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Examples/DatePickerShowWeekNumbersExample.razor, Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor, Source/Blazorise/Components/DatePicker/DatePicker.razor.cs, Source/Blazorise/Modules/JSOptions/DatePickerJSOptions.cs, Source/Blazorise/wwwroot/datePicker.js
Closes #6063
adds `ShowWeekNumbers`, docs and relase notes
=> DatePicker: ShowWeekNumbers

Documentation/Blazorise.Docs/Models/Snippets.generated.cs, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Code/BasicMessageServiceExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Code/MessageServiceChooseExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Code/MessageServiceConfirmExampleCode.html, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Examples/BasicMessageServiceExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Examples/MessageServiceChooseExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Examples/MessageServiceConfirmExample.razor, Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/MessagePage.razor, Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor, Source/Blazorise/Components/MessageAlert/MessageAlert.razor, Source/Blazorise/Components/MessageAlert/MessageAlert.razor.cs, Source/Blazorise/Components/MessageAlert/MessageProvider.razor, Source/Blazorise/Enums/MessageType.cs, Source/Blazorise/EventArguments/MessageEventArgs.cs, Source/Blazorise/Interfaces/IMessageService.cs, Source/Blazorise/Models/MessageOptions.cs, Source/Blazorise/Models/MessageOptionsChoice.cs, Source/Blazorise/Services/MessageService.cs
While working on the Scheduler component, I needed to have a confirmation dialog with multiple choices. So this PR solves it. 
It adds:
- `Choose` method that awaits the result from the user
- new `MessageOptionsChoice` that holds the information about the buttons on the dialog
- New examples in the docs
- Release notes
The only problem is that I had to change `TaskCompletionSource<bool> Callback` into `TaskCompletionSource<object> Callback`. I'm not sure if this parameter is even used by anyone, considering that `IMessageService` is used to give all information to the component.
=> MessageService: add Choose method

Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor, Source/Blazorise/Localization/ITextLocalizer.cs, Source/Blazorise/Localization/TextLocalizer.cs
Closes #6015
Adds `GetString`, `GetStrings` and relevant indexer.
The issue also asks about exposing current culture though `TextLocalizerService`, but it's already there as `SelectedCulture` property.
=> Localization: Add culture-specific overloads for text localization APIs

Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor, Source/Extensions/Blazorise.Charts/Options/Specifics/DoughnutChartOptions.cs, Source/Extensions/Blazorise.Charts/Options/Specifics/PieChartOptions.cs
Closes #6009
My first idea was to just add the JSON property name, but since this field is already wrong, it shouldn't affect anyone. So I have just renamed it. And to make it more flexible, I made it an `object` so that it can accept string and number as per chartjs specs.
=> Chart: fix Cutout option

Source/Blazorise.AntDesign/Components/Check.razor, Source/Blazorise.Bootstrap/Components/Check.razor, Source/Blazorise.Bootstrap5/Components/Check.razor, Source/Blazorise.Bulma/Components/Check.razor, Source/Blazorise.FluentUI2/Components/Check.razor, Source/Blazorise.Tailwind/Components/Check.razor
Closes #5955
**Test code**
```razor
<Card Margin="Margin.Is4.OnY">
<CardHeader>
<CardTitle>Test checkboxes</CardTitle>
</CardHeader>
<CardBody>
<Check TValue="bool" Size="Size.Medium" @bind-Checked="@IsNew">test ordinal</Check>
<Paragraph>
@IsNew
</Paragraph>
@code {
private bool IsNew { get; set; }
}
</CardBody>
<CardBody>
<Check TValue="bool" Size="Size.Medium" ReadOnly="true" @bind-Checked="@IsNew2">test readonly</Check>
<Paragraph>
@IsNew2
</Paragraph>
@code {
private bool IsNew2 { get; set; }
}
</CardBody>
<CardBody>
<Check TValue="bool" Size="Size.Medium" Disabled="true" @bind-Checked="@IsNew3">test disabled</Check>
<Paragraph>
@IsNew3
</Paragraph>
@code {
private bool IsNew3 { get; set; }
}
</CardBody>
</Card>
```
=> Check: add onclick:preventDefault for ReadOnly state
