Source/Extensions/Blazorise.Components/Base/BaseSelectList.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Tests/Blazorise.Demo/Pages/Tests/ComponentsPage.razor

fix: First time selection from SelectList

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/Enums.cs
Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
Tests/Blazorise.Demo/Pages/Tests/DataGridPage.razor

Dev082 grid rowdetail

---

Source/Extensions/Blazorise.Charts/BarChart.razor
Source/Extensions/Blazorise.Charts/BarChart.razor.cs
Source/Extensions/Blazorise.Charts/Chart.razor
Source/Extensions/Blazorise.Charts/Chart.razor.cs
Source/Extensions/Blazorise.Charts/ChartAdapter.cs
Source/Extensions/Blazorise.Charts/ChartModel.cs
Source/Extensions/Blazorise.Charts/DoughnutChart.razor
Source/Extensions/Blazorise.Charts/DoughnutChart.razor.cs
Source/Extensions/Blazorise.Charts/EventArguments.cs
Source/Extensions/Blazorise.Charts/JS.cs
Source/Extensions/Blazorise.Charts/LineChart.razor
Source/Extensions/Blazorise.Charts/LineChart.razor.cs
Source/Extensions/Blazorise.Charts/PieChart.razor
Source/Extensions/Blazorise.Charts/PieChart.razor.cs
Source/Extensions/Blazorise.Charts/PolarAreaChart.razor
Source/Extensions/Blazorise.Charts/PolarAreaChart.razor.cs
Source/Extensions/Blazorise.Charts/RadarChart.razor
Source/Extensions/Blazorise.Charts/RadarChart.razor.cs
Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js
Tests/Blazorise.Demo/Pages/Tests/ChartsPage.razor

added support for click and hover events

feat: chart events support

---

Source/Blazorise/Button.razor.cs
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js

feat: adds a support for preventDefault on submit button

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

fix: sort by underlined column type in datagrid

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

fix: autocomplete value different than string

---

Source/Blazorise/Config.cs

Correction in the `AddClassProvider` extension method (incorrect interface).

Fix custom class provider registration

---

Source/Blazorise/BaseInputComponent.razor.cs
Source/Blazorise/CheckEdit.razor.cs
Source/Blazorise/DateEdit.razor.cs
Source/Blazorise/FileEdit.razor.cs
Source/Blazorise/MemoEdit.razor.cs
Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/SelectEdit.razor
Source/Blazorise/SelectEdit.razor.cs
Source/Blazorise/TextEdit.razor.cs
Tests/BasicTestApp.Client/Index.razor
Tests/BasicTestApp.Client/SelectEditNavigationsComponent.razor
Tests/Blazorise.UnitTests/SelectEditNavigationTest.cs

#251
The problem was mostly in function FormatValueAsString() in SelectEdit but I also had to refactor some other things to make it work. Test is also included just in case.

Dev087 fix selectedit two way binding

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

Added new `RowSelectable` attribute to the `DataGrid` component. It is used to handle the selection of every row. By default it always be _selectable_ if nothing is set.

feat: added RowSelectable handler to DataGrid

---

Source/Blazorise/IIconProvider.cs
Source/Blazorise/Icon.razor.cs
Source/Blazorise/Providers/BaseIconProvider.cs
Source/Extensions/Blazorise.Icons.FontAwesome/FontAwesomeIconProvider.cs
Source/Extensions/Blazorise.Icons.Material/MaterialIconProvider.cs

Possible solution to enable FontAwesome Icon Styles. Issue #343. [UNTESTED]

Possible solution to enable FontAwesome Icon Styles. Issue #343. [UNTESTED]

---

Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/Utils/Converters.cs
Tests/BasicTestApp.Client/NumericEditComponent.razor
Tests/Blazorise.UnitTests/NumericEditTest.cs

fix: NumericEdit  decimal separator

---

Build/Blazorise.Client.props
Build/Blazorise.Demo.props
Build/Blazorise.Server.RC.props
Build/Blazorise.Server.props
Build/Blazorise.props
NuGet/Blazorise.Bootstrap.nuspec
NuGet/Blazorise.Bulma.nuspec
NuGet/Blazorise.Charts.nuspec
NuGet/Blazorise.Components.nuspec
NuGet/Blazorise.DataGrid.nuspec
NuGet/Blazorise.Frolic.nuspec
NuGet/Blazorise.Icons.FontAwesome.nuspec
NuGet/Blazorise.Icons.Material.nuspec
NuGet/Blazorise.Material.nuspec
NuGet/Blazorise.Sidebar.nuspec
NuGet/Blazorise.Snackbar.nuspec
NuGet/Blazorise.nuspec
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Server/BasicTestApp.Server.csproj
Tests/Blazorise.UnitTests/Blazorise.UnitTests.csproj
docs/_docs/meta/releases-notes/release0872.md
docs/_docs/meta/releases.md

Dev0872 upgrade

---

Source/Blazorise.Bootstrap/BootstrapJSRunner.cs
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js
Source/Blazorise.Bulma/BulmaJSRunner.cs
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js
Source/Blazorise.Frolic/FrolicJSRunner.cs
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.js
Source/Blazorise.Material/MaterialJSRunner.cs
Source/Blazorise.Material/wwwroot/blazorise.material.js
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/Modal.razor
Source/Blazorise/Modal.razor.cs
Source/Blazorise/Providers/EmptyJSRunner.cs

fix: modal scroll not reseting when opened

---

Source/Blazorise.Bootstrap/Styles/_mixins.scss
Source/Blazorise.Bootstrap/Styles/blazorise.bootstrap.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css

fix: Tooltip on Button in ButtonGroup breaks ButtonGroup

---

Source/Blazorise/BaseComponent.cs
Source/Blazorise/BaseInputComponent.razor.cs
Source/Blazorise/Button.razor.cs
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js
Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor

feat: Focus method for Button and Input components

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Solve the problem in this issues. Like I comment in the issue.

 Problem in DataGrid when number of page more than 20 #329

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Dev088 datagrid paging

---

Source/Extensions/Blazorise.Snackbar/wwwroot/blazorise.snackbar.css

fix: snackbar location offset

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Material/MaterialThemeGenerator.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs

#346 
The checkbox color must be set through `CheckColor` property
```cs
Theme.InputOptions.CheckColor = value;
```

fix: checkbox color set through theme settings

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/BaseComponent.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/Enums.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Styles/blazorise.scss
Source/Blazorise/wwwroot/blazorise.css

#446 
Also cleaned a class provider.

feat: character casing

---

Source/Blazorise/Enums.cs
Source/Blazorise/IIconProvider.cs
Source/Blazorise/Icon.razor
Source/Blazorise/Icon.razor.cs
Source/Blazorise/Providers/BaseIconProvider.cs
Source/Extensions/Blazorise.Icons.FontAwesome/FontAwesomeIconProvider.cs
Source/Extensions/Blazorise.Icons.Material/Icon.razor
Source/Extensions/Blazorise.Icons.Material/MaterialIconProvider.cs

- Added new attribute IconStyle to Icon component
- Refactored icon provider so it can detect and remove duplicate icon style names from the icon name
#343

feat: added IconStyle to icon component

---

Source/Blazorise/Providers/BaseIconProvider.cs
Source/Extensions/Blazorise.Icons.FontAwesome/FontAwesomeIconProvider.cs
Source/Extensions/Blazorise.Icons.Material/MaterialIconProvider.cs

Fixed detection of icon style through it's name so now is possible to define custom style along with icon name.
#343

fix: better handling of icon style names

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Frolic/FrolicThemeGenerator.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs
Tests/Blazorise.Demo/Layouts/MainLayout.razor

Added `GradientBlendPercentage` to control the level of gradient applied to the element style.
#345

feat: control gradient level on theme generator

---

Source/Blazorise.Material/MaterialThemeGenerator.cs

fix: outline button color for material provider

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Frolic/FrolicThemeGenerator.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs

Calculates bar-brand color based on the it's background color.
#352

fix: calculate barbrand color based on background color

---

Source/Blazorise/EventArguments.cs
Source/Blazorise/Modal.razor.cs
Source/Blazorise/ModalBackdrop.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor

Fixed the bug with modal dialog messing with the scroll bar.
#296 
#435

fix: datagrid modal messing with the scroll

---

Source/Blazorise/wwwroot/blazorise.js

fix: allow enter key on NumericEdit keyPress

---

README.md
Tests/Blazorise.Demo.Bootstrap.RC/Pages/_Host.cshtml
Tests/Blazorise.Demo.Bootstrap/wwwroot/index.html
Tests/Blazorise.Demo.Frolic/wwwroot/index.html
docs/_docs/start.md
docs/_docs/usage/bootstrap.md

docs: links for latest fontawesome icons

---

.vscode/settings.json
README.md
docs/_docs/components.md
docs/_docs/components/alert.md
docs/_docs/components/bar.md
docs/_docs/components/button.md
docs/_docs/components/card.md
docs/_docs/components/check.md
docs/_docs/components/dropdown.md
docs/_docs/components/elements.md
docs/_docs/components/field.md
docs/_docs/components/figure.md
docs/_docs/components/memo.md
docs/_docs/components/numeric.md
docs/_docs/components/tab.md
docs/_docs/components/text.md
docs/_docs/components/validation.md
docs/_docs/extensions/chart.md
docs/_docs/extensions/datagrid.md
docs/_docs/extensions/sidebar.md
docs/_docs/faq.md
docs/_docs/helpers/enums.md
docs/_docs/helpers/utilities.md
docs/_docs/meta/licence.md
docs/_docs/start.md
docs/_docs/usage.md
docs/_docs/usage/bootstrap.md
docs/_docs/usage/bulma.md
docs/_docs/usage/material.md

Dev088 docs getting started

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapJSRunner.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Alert.razor
Source/Blazorise/Alert.razor.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/EventArguments.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/alert.md
docs/_examples/elements/alert-close-big.html
docs/_examples/elements/alert-close.html

Ability to show and hide Alert

---

Source/Blazorise.Bootstrap/BootstrapJSRunner.cs
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js
Source/Blazorise.Bulma/BulmaJSRunner.cs
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js
Source/Blazorise.Frolic/FrolicJSRunner.cs
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.js
Source/Blazorise.Material/MaterialJSRunner.cs
Source/Blazorise.Material/wwwroot/blazorise.material.js
Source/Blazorise/Button.razor.cs
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/TextEdit.razor.cs
Source/Blazorise/Tooltip.razor.cs
Source/Blazorise/wwwroot/blazorise.js

clean: reorder jsinterop function parameters

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/EventArguments.cs
Source/Extensions/Blazorise.DataGrid/Models/DataGridColumnInfo.cs

feat: added ReadData event handler to DataGrid

---

Source/Blazorise/BaseTextComponent.cs
Source/Blazorise/CardSubtitle.razor.cs
Source/Blazorise/CardText.razor.cs
Source/Blazorise/CardTitle.razor.cs
Source/Blazorise/Enums.cs
Source/Blazorise/Paragraph.razor.cs
Source/Blazorise/Text.razor.cs

#481 
Added to:
- `<Paragraph>`
- `<CardText>`
- `<CardTitle>`
- `<CardSubtitle>`

feat: text transformations for text-based components

---

Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/Utils/Converters.cs

fix: missing numeric data-type convertes

---

Source/Blazorise/Button.razor.cs

feat: support for MVVM command on Button component

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Tests/Blazorise.Demo/Pages/Tests/DataGridPage.razor

I have added PrevButtonTemplate and NextButtonTemplate to BaseDataGrid and made it available at DataGrid.

Add templates for pre and next button of data grid

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Implemented a multi-sort is necessary to change the  ReadData handle to  take the multi-columns to sort.

Implemented DataGrid Multi-Sort.

---

Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/Utils/Converters.cs
Source/Blazorise/wwwroot/blazorise.js

#509 
Added support to define Min and Max value. If left to default it will be determined based on the supplied value type.

feat: min and max value for NumericEdit

---

Source/Blazorise.Bootstrap/CheckEdit.razor
Source/Blazorise.Bootstrap/Config.cs
Source/Blazorise.Bulma/CheckEdit.razor
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Frolic/CheckEdit.razor
Source/Blazorise.Frolic/Config.cs
Source/Blazorise/CheckEdit.razor
Source/Blazorise/CheckEdit.razor.cs
Source/Blazorise/ComponentMapper.cs
Source/Blazorise/IComponentMapper.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor
Tests/Apps/TodoApp/TodoItem.razor
Tests/Apps/TodoApp/TodoItems.razor
Tests/Blazorise.Demo/Layouts/MainLayout.razor
Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor
Tests/Blazorise.Demo/Pages/Tests/ValidationsPage.razor

#502 
removed NullableChecked attribute(s)

refactor: CheckEdit converted to generic component

---

Source/Blazorise/Bar.razor.cs
Source/Blazorise/BarDropdown.razor.cs
Source/Blazorise/BarDropdownMenu.razor.cs
Source/Blazorise/BarDropdownToggle.razor.cs
Source/Blazorise/BarMenu.razor.cs
Source/Blazorise/BarToggler.razor.cs
Source/Blazorise/Button.razor.cs
Source/Blazorise/Dropdown.razor.cs
Source/Blazorise/DropdownMenu.razor.cs
Source/Blazorise/DropdownToggle.razor.cs
Source/Blazorise/EventArguments.cs
Source/Blazorise/ModalBackdrop.razor.cs
Source/Blazorise/Tab.razor.cs
Source/Blazorise/TabPanel.razor.cs
Source/Blazorise/Tabs.razor.cs
Source/Blazorise/TabsContent.razor.cs
Tests/BasicTestApp.Client/TabsComponent.razor
Tests/Blazorise.Demo/Pages/Tests/TabsPage.razor
docs/_docs/components/tab.md

refactor: usage of closable components

---

docs/_docs/components/check.md
docs/_docs/components/validation.md

docs: mention of TValue for CheckEdit

---

Tests/Blazorise.Demo/Pages/Tests/ElementsPage.razor

fix: dismisable alerts in demo app

---

Source/Blazorise/Alert.razor.cs

fix: alert visibility state

---

Source/Blazorise/Table.razor
Source/Blazorise/TableBody.razor
Source/Blazorise/TableFooter.razor
Source/Blazorise/TableHeader.razor
Source/Blazorise/TableRowHeader.razor

fix: missing style attribute to table components

---

README.md
docs/_docs/meta/releases-notes/release0882.md
docs/_docs/meta/releases.md

docs for 0.8.8.8

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.razor.cs
Source/Extensions/Blazorise.DataGrid/EventArguments.cs

fix: DataGrid default sorting not applied

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Bulma/Select.razor
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Select.razor
Source/Blazorise/Select.razor.cs
Source/Blazorise/SelectItem.razor.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Tests/BasicTestApp.Client/Index.razor
Tests/BasicTestApp.Client/SelectComponent.razor
Tests/BasicTestApp.Client/SelectNavigationsComponent.razor
Tests/BasicTestApp.Client/ValidateSelectComponent.razor
Tests/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor
Tests/Blazorise.Demo/Pages/Tests/ValidationsPage.razor
Tests/Blazorise.UnitTests/SelectNavigationTest.cs
Tests/Blazorise.UnitTests/SelectTest.cs
Tests/Blazorise.UnitTests/ValidateSelectTest.cs
docs/_docs/components/field.md
docs/_docs/components/select.md

rename SelectEdit to Select

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

#570 
Converted all DataGrid events from `Action` to `EventCallback`. This is needed so that users can make asynchronous calls to determine the outcome of an event.

fix: convert all DataGrid event to EventCallback

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/BlazoriseOptions.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Slider.razor
Source/Blazorise/Slider.razor.cs
Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor
docs/_data/navigation.yml
docs/_docs/components/slider.md
docs/_examples/forms/slider-basic.html

feat: Slider component

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bootstrap/Config.cs
Source/Blazorise.Bootstrap/Switch.razor
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Bulma/Styles/blazorise.bulma.scss
Source/Blazorise.Bulma/Switch.razor
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Material/MaterialThemeGenerator.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/Control.razor.cs
Source/Blazorise/Enums.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Label.razor.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Switch.razor
Source/Blazorise/Switch.razor.cs
Tests/Blazorise.Demo/App.razor
Tests/Blazorise.Demo/Layouts/MainLayout.razor

feat: Switch component

---

Source/Extensions/Blazorise.Snackbar/Snackbar.razor
Source/Extensions/Blazorise.Snackbar/Snackbar.razor.cs
Source/Extensions/Blazorise.Snackbar/SnackbarAction.razor
Source/Extensions/Blazorise.Snackbar/SnackbarAction.razor.cs
Source/Extensions/Blazorise.Snackbar/SnackbarBody.razor
Source/Extensions/Blazorise.Snackbar/SnackbarBody.razor.cs
Tests/Blazorise.Demo/Pages/Tests/ElementsPage.razor

feat: Snackbar Closed event

---

Source/Blazorise/Container.razor.cs
Source/Blazorise/Tooltip.razor.cs
Source/Extensions/Blazorise.Sidebar/Sidebar.razor
Source/Extensions/Blazorise.Sidebar/SidebarData.cs
Source/Extensions/Blazorise.Sidebar/SidebarLink.razor
Source/Extensions/Blazorise.Sidebar/SidebarLink.razor.cs
Source/Extensions/Blazorise.Sidebar/SidebarSubItem.razor.cs
Tests/Blazorise.Demo/Layouts/MainLayout.razor
Tests/Blazorise.Demo/Pages/Tests/ElementsPage.razor
Tests/Blazorise.Demo/Pages/Tests/LayoutPage.razor

#586 
Fixed some left-overs from refactoring done by #536 
- Tooltip
- SidebarSubItem
- SidebarLink
- Container

Dev090 refactoring fixes

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/Divider.razor
Source/Blazorise/Divider.razor.cs
Source/Blazorise/Enums.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Styles/blazorise.scss
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs
Source/Blazorise/wwwroot/blazorise.css
docs/_data/navigation.yml
docs/_docs/components/divider.md
docs/_docs/helpers/enums.md
docs/_examples/elements/divider-dashed.html
docs/_examples/elements/divider-dotted.html
docs/_examples/elements/divider-text.html
docs/_examples/elements/divider.html
docs/assets/css/blazorise.css

feat: Divider component

---

Source/Blazorise/Blazorise.csproj
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs
Source/Extensions/Blazorise.Snackbar/Enums.cs
Source/Extensions/Blazorise.Snackbar/Snackbar.razor
Source/Extensions/Blazorise.Snackbar/Snackbar.razor.cs
Source/Extensions/Blazorise.Snackbar/SnackbarAction.razor.cs
Source/Extensions/Blazorise.Snackbar/Styles/_colors.scss
Source/Extensions/Blazorise.Snackbar/Styles/_functions.scss
Source/Extensions/Blazorise.Snackbar/Styles/_mixins.scss
Source/Extensions/Blazorise.Snackbar/Styles/_variables.scss
Source/Extensions/Blazorise.Snackbar/Styles/blazorise.snackbar.scss
Source/Extensions/Blazorise.Snackbar/Utils/Extensions.cs
Source/Extensions/Blazorise.Snackbar/compilerconfig.json
Source/Extensions/Blazorise.Snackbar/compilerconfig.json.defaults
Source/Extensions/Blazorise.Snackbar/wwwroot/blazorise.snackbar.css
Tests/Blazorise.Demo/Pages/Tests/ElementsPage.razor

#358 
Added support for color variants on Snackbar. Colors are calculated based on the settings in the theme options.

feat: Snackbar color variants

---

README.md
docs/_docs/start.md
docs/_docs/usage/bootstrap.md
docs/_docs/usage/bulma.md
docs/_docs/usage/material.md

#609 
#606 
Update release notes according to the specs for  .Net Core 3.2

docs: usages for .net core 3.2

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
docs/_docs/extensions/autocomplete.md

feat: autocomplete SearchChanged event

---

Source/Blazorise/TableHeaderCell.razor.cs
Source/Blazorise/TableRow.razor.cs
Source/Blazorise/TableRowCell.razor.cs
Source/Blazorise/TableRowHeader.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/EventArguments.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

feat: click and double click events on DataGrid row

---

Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Source/Extensions/Blazorise.Components/DropdownList.razor
Source/Extensions/Blazorise.Components/DropdownList.razor.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

#620 
Also added `Class` and `Style` properties.

feat: attributes splatting for extension components

---

docs/_docs/components.md

alphabetized Form and Components

sort docs/components list

---

CONTRIBUTING.md

First PR updating the contributing setup steps.

Updated contributing doc to include steps to setup development and testing environment.

---

Source/Blazorise.AntDesign/FileEdit.razor
Source/Blazorise.Bootstrap/FileEdit.razor
Source/Blazorise.Bulma/FileEdit.razor
Source/Blazorise/FileEdit.razor

#656 
`@Feedback` render fragment was missing

fix: FileEdit validation placeholder

---

Source/Blazorise/Navigation.razor.cs
Source/Blazorise/NavigationItem.razor.cs

fix: Navigation marked as obsolete

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor

fix: pagination item not active on DataGrid paging

---

Source/Extensions/Blazorise.DataGrid/BaseDataGridComponent.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridDetailRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor.cs

#529 
Added multiple different properties to handle custom classes and styles for rows, cells, headers and filters.
- RowClass
- RowStyle
- HeaderRowClass
- HeaderRowStyle
- FilterRowClass
- FilterRowStyle
- CellClass
- CellStyle
- HeaderCellClass
- HeaderCellStyle
- FilterCellClass
- FilterCellStyle

feat: DataGrid styling with custom classes and styles

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

#527 
Removed check for `ICollection` from the beginning of `OnSaveCommand` and moved it bellow to be used only for insert command.

fix: DataGrid not saving if Data is IQueryable

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_utilities.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/TableRowCell.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor

#491 
- Added TextAlignment for TableRowCell and DataGridColumn
- Fixed TextAlignment for Bulma provider
- New TextAlignment css utilities fro AntDesign provider

feat: TextAlignment for TableRowCell and DataGridColumn

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor

#490 
Added new properties to BaseDataGridColumn
- DisplayFormat
- DisplayCulture

feat: DisplayFormat and DisplayCulture properties for datagrid column

---

Source/Blazorise/Styles/_layout.scss
Source/Blazorise/wwwroot/blazorise.css
Source/Extensions/Blazorise.Sidebar/Sidebar.razor.cs
Source/Extensions/Blazorise.Sidebar/wwwroot/blazorise.sidebar.css

- Removed comment that was blocking sticky/fixed header from working
- Added styles for scrollable sidebar

fix: add back sticky header & scrollable sidebar

---

Source/Blazorise/BarDropdownToggle.razor.cs
Source/Blazorise/DropdownToggle.razor.cs
Source/Blazorise/ModalBackdrop.razor.cs

#662 Possible memory leak on Dispose

fix: undisposed dotNetObjectRef oc closable components

---

Source/Blazorise.AntDesign/Select.razor
Source/Blazorise.AntDesign/Select.razor.cs
Source/Blazorise.Bulma/Select.razor
Source/Blazorise/Select.razor
Source/Blazorise/Select.razor.cs

#657 Size-attribute conflict in `<Select>` component

feat: property MaxVisibleItems on Select component

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/FilterContext.cs
docs/_docs/extensions/datagrid.md

#394 Custom filtering for DataGrid

feat: CustomFilter handler for DataGrid

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Demos/Blazorise.Demo/Pages/Tests/ModalsPage.razor
Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Bulma/DateEdit.razor
Source/Blazorise/DateEdit.razor
Source/Blazorise/DateEdit.razor.cs
Source/Blazorise/Utils/Converters.cs
Source/Blazorise/Utils/Parsers.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor
Tests/BasicTestApp.Client/ElementIdComponent.razor
docs/_docs/components/date.md

#630 DateEdit `@bind-Date` not working with non-nullable dates

DateEdit converted to generic component

---

Demos/Blazorise.Demo/App.razor
Source/Blazorise/Styles/_animation.scss
Source/Blazorise/Styles/_positions.scss
Source/Blazorise/Styles/_variables.scss
Source/Blazorise/Styles/tooltip.scss
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs
Source/Blazorise/wwwroot/blazorise.css

#553 Fade Option in Tooltip as ThemeTooltipOptions
Added variables are:
- BackgroundColor
- BackgroundOpacity
- Color
- FontSize
- FadeTime
- MaxWidth
- Padding
- ZIndex

feat: Tooltip theme options

---

Source/Blazorise.AntDesign/Breadcrumb.razor
Source/Blazorise.Bulma/Breadcrumb.razor
Source/Blazorise.Frolic/Breadcrumb.razor
Source/Blazorise/Breadcrumb.razor
Source/Blazorise/Breadcrumb.razor.cs
Source/Blazorise/BreadcrumbItem.razor.cs
Source/Blazorise/BreadcrumbLink.razor
Source/Blazorise/BreadcrumbLink.razor.cs
Source/Blazorise/Enums.cs
docs/_docs/components/breadcrumb.md
docs/_docs/helpers/enums.md

#351 Automatically set Breadcrumb active state based on navigation url
- Added `BreadcrumbMode` to the `Breadcrumb` component
- If `Mode == BreadcrumbMode.Auto` all items will be activated based on navigation url
- Default mode is `None`

Dev090 breadcrumbs active

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Bulma/TimeEdit.razor
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/TimeEdit.razor
Source/Blazorise/TimeEdit.razor.cs
Source/Blazorise/Utils/Parsers.cs
docs/_data/navigation.yml
docs/_docs/components/date.md
docs/_docs/components/time.md
docs/_examples/forms/time.html

#365
- Added new generic `TimeEdit` component
- Supported `TValue` types are `TimeSpan` and `DateTime`

feat: TimeEdit component

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/ColorEdit.razor
Source/Blazorise/ColorEdit.razor.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_data/navigation.yml
docs/_docs/components/color.md
docs/_examples/forms/color.html

#366 Color picker
- New native component ColorEdit

feat: ColorEdit component

---

Build/Blazorise.Client.props
Build/Blazorise.Server.props
Demos/Blazorise.Demo.AntDesign/Program.cs
Demos/Blazorise.Demo.Bootstrap/Program.cs
Demos/Blazorise.Demo.Bulma/Program.cs
Demos/Blazorise.Demo.Frolic/Program.cs
Demos/Blazorise.Demo.Material/Program.cs
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Client/Program.cs
Tests/BasicTestApp.Server/BasicTestApp.Server.csproj
Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj

#745 
Updated all projects to use latest Blazor 3.2.0-preview4

update: Blazor 3.2.0-preview4

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Tab.razor
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Tab.razor
Source/Blazorise/Tab.razor.cs

feat: Disable property for Tab component

---

Source/Blazorise.AntDesign/DropdownToggle.razor
Source/Blazorise.Bulma/DropdownToggle.razor
Source/Blazorise.Frolic/Dropdown.razor
Source/Blazorise/Dropdown.razor
Source/Blazorise/DropdownToggle.razor
Source/Blazorise/DropdownToggle.razor.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Source/Extensions/Blazorise.Components/DropdownList.razor
Source/Extensions/Blazorise.Components/DropdownList.razor.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

#676 
Focus method added to:
- SelectList
- Autocomplete
- DropdownList

feat: Focus for extension components

---

Source/Extensions/Blazorise.Charts/ChartOptions.cs

#693 
Options added:
- Responsive
- MaintainAspectRatio
- ResponsiveAnimationDuration
- AspectRatio

feat: Added Responsive Chart options

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
Source/Blazorise.AntDesign/DropdownToggle.razor
Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Bulma/DropdownToggle.razor
Source/Blazorise.Frolic/Dropdown.razor
Source/Blazorise.Frolic/FrolicThemeGenerator.cs
Source/Blazorise/Dropdown.razor
Source/Blazorise/DropdownToggle.razor
Source/Blazorise/DropdownToggle.razor.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs
Source/Extensions/Blazorise.Charts/ChartOptions.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Source/Extensions/Blazorise.Components/DropdownList.razor
Source/Extensions/Blazorise.Components/DropdownList.razor.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

Revert "Dev091 breadcrumb color"

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Frolic/FrolicThemeGenerator.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs

#646
- Added Color to ThemeBreadcrumbOptions
- Fixed breadcrumb colors for AntDesign and eFrolic

feat: Theme color option for Breadcrumb

---

Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs

#686 Null reference exception when DataGridColumn Field is not set

fix: DataGrid must be specified

---

Source/Blazorise/Styles/_layout.scss
Source/Blazorise/wwwroot/blazorise.css

Overflow was not working correctly with sider inner layout

fix: layout issue for responsive design

---

Source/Blazorise/StyleBuilder.cs
Source/Extensions/Blazorise.Charts/BarChart.razor
Source/Extensions/Blazorise.Charts/Chart.razor
Source/Extensions/Blazorise.Charts/DoughnutChart.razor
Source/Extensions/Blazorise.Charts/HorizontalBarChart.razor
Source/Extensions/Blazorise.Charts/LineChart.razor
Source/Extensions/Blazorise.Charts/PieChart.razor
Source/Extensions/Blazorise.Charts/PolarAreaChart.razor
Source/Extensions/Blazorise.Charts/RadarChart.razor
Source/Extensions/Blazorise.Icons.FontAwesome/Icon.razor
Source/Extensions/Blazorise.Icons.Material/Icon.razor
Source/Extensions/Blazorise.Sidebar/Sidebar.razor
Source/Extensions/Blazorise.Sidebar/SidebarBrand.razor
Source/Extensions/Blazorise.Sidebar/SidebarContent.razor
Source/Extensions/Blazorise.Sidebar/SidebarFooter.razor
Source/Extensions/Blazorise.Sidebar/SidebarItem.razor
Source/Extensions/Blazorise.Sidebar/SidebarLabel.razor
Source/Extensions/Blazorise.Sidebar/SidebarLink.razor
Source/Extensions/Blazorise.Sidebar/SidebarNavigation.razor
Source/Extensions/Blazorise.Sidebar/SidebarSubItem.razor

#793 Attribute splatting for Charts
- Charts
- Icons
- Sidebar
- Fixed StyleBuilder

fix: charts attribute splatting

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_figure.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs

#790 Figure is not responsive
Fixed Bootstrap and AntDesign implementation

fix: Responsive Figure image

---

Source/Blazorise/Utils/Parsers.cs
Tests/Blazorise.Tests/DateEditTest.cs

fix: DateTime parser test failed

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

#807 Datagrid initial sort direction is not applied on initialization.

fix: DataGrid sorting initialization

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridRowStyling.cs
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
docs/_docs/extensions/datagrid.md

#436 
- Option to change row color, class and style
- Handlers to control the styles for each row
- Example added to docs

feat: Custom DataGrid row styling

---

Build/Blazorise.Client.props
Build/Blazorise.Server.props
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Server/BasicTestApp.Server.csproj
Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj

#814 Upgrade to Blazor 3.2 preview 5

upgrade all projects to Blazor 3.2 preview 5

---

Source/Blazorise.AntDesign/Switch.razor

#813 Bug switching switch in Ant

fix: AntDesign Switch not responding

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs

Addresses issues in #817 and #819

fix: Ant Design Layout offset builder

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
Source/Blazorise.AntDesign/Styles/_alert.scss
Source/Blazorise.AntDesign/Styles/_background.scss
Source/Blazorise.AntDesign/Styles/_badge.scss
Source/Blazorise.AntDesign/Styles/_buttons.scss
Source/Blazorise.AntDesign/Styles/_functions.scss
Source/Blazorise.AntDesign/Styles/_table.scss
Source/Blazorise.AntDesign/Styles/_tabs.scss
Source/Blazorise.AntDesign/Styles/_typography.scss
Source/Blazorise.AntDesign/Styles/_variables.scss
Source/Blazorise.AntDesign/Styles/blazorise.antdesign.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Bulma/Styles/_form.scss
Source/Blazorise.Bulma/Styles/_layout.scss
Source/Blazorise.Bulma/Styles/blazorise.bulma.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Select.razor.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs

#834 
- Added new default colors for AntDesign buttons, alerts, tables, bockground, texts, etc.
- Fixed bulma layout issues
- Fixed styles for Bulma slider and multi-select
- Modified ThemeGenerator default colors

fix: default colors and styling for providers

---

Source/Blazorise.Bootstrap/FileEdit.razor

fix: double ChildContent for FileEdit

---

Source/Extensions/Blazorise.Sidebar/Sidebar.razor

fix: sidebar item not collapsing

---

Source/Blazorise/BaseCheckComponent.cs

fix: RadioGroup not working for enums

---

Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor
Source/Blazorise/Validation.razor.cs
Source/Blazorise/Validations.razor.cs

#661 Auto Validation: Form Validation, error message is displayed on first load.
- Added flag `ValidateOnLoad` on `<Validations>`
- Default is set to `true `so it is back-compatible
- When page is loaded, validation will not run until user starts to change input values

feat: run validation on first change

---

Source/Extensions/Blazorise.Charts.Streaming/ChartStreaming.razor.cs
Source/Extensions/Blazorise.Charts.Streaming/ChartStreamingData.cs
Source/Extensions/Blazorise.Charts/ChartData.cs

#875 Streaming charts - howto assign specific "datastreams" to specific datasets
ChartStreamingData extended with two fields
- DatasetLabel
- DatasetIndex

feat: dataset Label and Index for live charts event argument

---

Source/Extensions/Blazorise.Sidebar/Sidebar.razor
Source/Extensions/Blazorise.Sidebar/SidebarData.cs
Source/Extensions/Blazorise.Sidebar/wwwroot/blazorise.sidebar.css
docs/_docs/extensions/sidebar.md

#871 Sidebar not colapsing on media breakpoints
#880 Databound Sidebar with Icons
- Fixed sidebar collapse on breakpoint
- Added Icon for dynamic sidebar
- Mention Icon in docs

fix sidebar

---

Source/Blazorise.AntDesign/AntDesignJSRunner.cs
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.js
Source/Blazorise.Bootstrap/BootstrapJSRunner.cs
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js
Source/Blazorise.Bulma/BulmaJSRunner.cs
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js
Source/Blazorise.Frolic/FrolicJSRunner.cs
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.js
Source/Blazorise.Material/MaterialJSRunner.cs
Source/Blazorise.Material/wwwroot/blazorise.material.js
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/Modal.razor.cs
Source/Blazorise/Providers/EmptyJSRunner.cs
docs/_docs/components/modal.md

#847 Modal scrolls to top of page
Added ScrollToTop property to Modal. Default value is `true`.

feat: Flag to control modal opening

---

Demos/Blazorise.Demo.Bootstrap.RC/Pages/_Host.cshtml
Demos/Blazorise.Demo.Bootstrap/wwwroot/index.html
Demos/Blazorise.Demo/Layouts/MainLayout.razor
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeProvider.razor.cs

#760 
- Updated demo apps to latest Bootstrap
- Added switch to control the theme
Visually controlled theme on all demo pages and there are no visible inconsistencies with latest version of Bootstrap.

Update to Bootstrap 4.5

---

Source/Blazorise.Material/Styles/_functions.scss
Source/Blazorise.Material/Styles/_grid.scss
Source/Blazorise.Material/Styles/_mixins.scss
Source/Blazorise.Material/Styles/_variables.scss
Source/Blazorise.Material/Styles/blazorise.material.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

#898 Column Width in Material
Copied scss from djibe material fork. This fix is just temporary until djibe finishes his material css.

fix: material columns for material provider

---

Build/Blazorise.Client.props
Build/Blazorise.Demo.props
Build/Blazorise.Server.RC.props
Build/Blazorise.Server.props
Build/Blazorise.props
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Server/BasicTestApp.Server.csproj
Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj

#913 Upgrade to the latest version of .NetCore and Blazor 3.2

Updated all projects to .Net Core 3.1.4 and Blazor 3.2

---

Source/Blazorise.Bootstrap/Config.cs

#908 RadioGroup-event or binding doesnt work when Buttons="true"

fix: removed attribute data-toggle for Bootstrap RadioGroup

---

docs/_docs/components/card.md
docs/_docs/components/field.md
docs/_docs/components/modal.md
docs/_docs/components/tooltip.md
docs/_docs/components/typography.md

And I wonder if this documentation for the **FieldLabel** is valid because I don't see these properties in the source code?

Fix documentation for some `Is***` (boolean) properties.

---

Demos/Blazorise.Demo/Pages/Dashboard.razor

#945 Could you please add source code in Blazorise Demo
Fixed demo source url.

fix: demo source url

---

Source/Blazorise.AntDesign/TableRowHeader.razor
Source/Blazorise/BarDropdownItem.razor.cs
Source/Blazorise/BarDropdownToggle.razor.cs
Source/Blazorise/BarLink.razor.cs
Source/Blazorise/Button.razor.cs
Source/Blazorise/CloseButton.razor.cs
Source/Blazorise/CollapseHeader.razor.cs
Source/Blazorise/DateEdit.razor.cs
Source/Blazorise/DropdownItem.razor.cs
Source/Blazorise/DropdownToggle.razor.cs
Source/Blazorise/Tab.razor.cs
Source/Blazorise/TableHeaderCell.razor
Source/Blazorise/TableHeaderCell.razor.cs
Source/Blazorise/TableRow.razor
Source/Blazorise/TableRow.razor.cs
Source/Blazorise/TableRowCell.razor
Source/Blazorise/TableRowCell.razor.cs
Source/Blazorise/TableRowHeader.razor
Source/Blazorise/TableRowHeader.razor.cs
Source/Blazorise/TimeEdit.razor.cs

#946 Unhandled Exception behavior in UI events

fix: all events handlers converted from void to Task

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Badge.razor
Source/Blazorise.AntDesign/Config.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/Styles/_badge.scss
Source/Blazorise.Bootstrap/Styles/blazorise.bootstrap.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Bulma/Badge.razor
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_badge.scss
Source/Blazorise.Frolic/Styles/blazorise.frolic.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise.Material/Styles/_badge.scss
Source/Blazorise.Material/Styles/blazorise.material.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css
Source/Blazorise/Badge.razor
Source/Blazorise/Badge.razor.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/badge.md

#281 Add ability to display close button on badge
- Added close button on badge
- it will be visible when CloseClicked is defined
- Example added to the documentation

Badge close button

---

Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Frolic/FrolicThemeGenerator.cs
Source/Blazorise/Theme.cs
Source/Blazorise/ThemeGenerator.cs

#413 Button colors
Added LuminanceThreshold to Theme options. This is used to control the brightness of text colors on button and other elements.

feat: added LuminanceThreshold to Theme options

---

Source/Blazorise.Material/MaterialThemeGenerator.cs

#430 Modal Footer Buttons do not follow theme

fix: Modal Footer Buttons do not follow theme

---

Source/Blazorise.AntDesign/AntDesignStyleProvider.cs
Source/Blazorise.Bootstrap/BootstrapStyleProvider.cs
Source/Blazorise.Bulma/BulmaStyleProvider.cs
Source/Blazorise.Frolic/FrolicStyleProvider.cs
Source/Blazorise/BaseComponent.cs
Source/Blazorise/Enums.cs
Source/Blazorise/IStyleProvider.cs
Source/Blazorise/Providers/EmptyStyleProvider.cs
Source/Blazorise/StyleProvider.cs

#955 Remove Visibility property
Better sooner than later. So instead of making it obsolete I have decided to remove Visibility completely. It is going to be documented anyway and I think it's not used that much anyways.

Remove Visibility property

---

docs/_docs/components/bar.md

Things I missed to mention for Vertical bar modes

docs: Updated Bar docs for more Vertical mode detailing

---

Source/Extensions/Blazorise.Snackbar/Enums.cs
Source/Extensions/Blazorise.Snackbar/EventArguments.cs
Source/Extensions/Blazorise.Snackbar/Snackbar.razor.cs
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs
Source/Extensions/Blazorise.Snackbar/Styles/blazorise.snackbar.scss
Source/Extensions/Blazorise.Snackbar/Utils/Extensions.cs
Source/Extensions/Blazorise.Snackbar/wwwroot/blazorise.snackbar.css
docs/_docs/extensions/snackbar.md

feat: SnackbarStack component

---

Source/Blazorise/wwwroot/blazorise.js

#1030 Role="TextRole.Email" cashes Validation

fix: problem with caret selection when input is not text type

---

Source/Blazorise/Enums.cs
Source/Blazorise/Extensions.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor

#1044 [Extension Autocomplete] Can we define the type of TextEdit

fix: mark Autocomplete input field as search type

---

docs/_docs/extensions/chart.md

- Stacked has been added
- Some properties+classes related to Chart are added, however not all, takes too much time to update all docs.

Docs for Chartjs

---

Source/Blazorise/Alert.razor.cs
Source/Blazorise/Bar.razor.cs
docs/_docs/components/alert.md

#1061 Alert visibility
- Added VisibleChanged event callback
- Enabled two-way binding
- Updated docs

Added VisibleChanged event callback to Alert component

---

Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor.cs

#1011 Text-Alignment on DataGridCommandColumn seems not to work

Fixed TextAlignment for DataGridCommandColumn

---

Source/Blazorise/ThemeGenerator.cs

Add support for theming with rgba css color

---

Source/Blazorise/Divider.razor.cs
Source/Blazorise/Theme.cs

#870 DividerType in Theme DividerOptions
-  `DividerType` added into Theme.DividerOptions
- `Type` property renamed to `DividerType?`

Added DividerType in Theme DividerOptions

---

Source/Blazorise.AntDesign/Styles/_form.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css

#1081 Addons with Select component not working for AntDesign

Fixed padding and borders for Select within Addons component

---

Source/Blazorise/BaseInputComponent.razor.cs
Source/Blazorise/BaseTextInput.razor.cs
Source/Blazorise/MemoEdit.razor.cs
docs/_docs/components/memo.md
docs/_docs/components/text.md

#998 Refactor the TextChanged mode for TextEdit and NumericEdit to be configured for each instance

Added ChangeTextOnKeyPress on input fields to be able to override global settings

---

Source/Blazorise.Frolic/Styles/_tabs.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise.Material/Styles/_tabs.scss
Source/Blazorise.Material/Styles/blazorise.material.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

#1120 Material and eFrolic tab buttons don't change cursor
- Fixed Material and eFrolic cursor not showing

Dev092 tabs cursor

---

docs/_docs/extensions/datagrid.md

Page button documentation

---

Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/Styles/_switch.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Material/Styles/_form.scss
Source/Blazorise.Material/Styles/_switch.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

Fixed the following issues:
Bootstrap
- Radio label is not centered vertically
- Switch label is not centered vertically
Material
- _Partially fixed:_ When you click on Switch, the shadow if slightly offset to the bottom
- Check and Radio still miss sizing

Updates to property unification

---

Source/Blazorise.Bulma/NumericEdit.razor
Source/Blazorise/NumericEdit.razor
Source/Blazorise/NumericEdit.razor.cs

Add VisibleCharacters to NumericEdit

---

Source/Blazorise.AntDesign/ListGroup.razor
Source/Blazorise/ListGroup.razor
Source/Blazorise/ListGroup.razor.cs
Source/Blazorise/ListGroupItem.razor
Source/Blazorise/ListGroupItem.razor.cs
Source/Blazorise/Stores/ListGroupStore.cs

#1185 ListGroupItem Clicked event is not working
- Implemented store for ListGroup
- Added `SelectedItem` property
- Better handling of active items
- Fixed Clicked event on ListGroupItem

Implemented store on ListGroup and fixed Clicked event on ListGroupItem

---

Source/Blazorise.AntDesign/Button.razor
Source/Blazorise.AntDesign/DropdownToggle.razor
Source/Blazorise.Bootstrap/Button.razor
Source/Blazorise.Bulma/Button.razor
Source/Blazorise.Bulma/DropdownToggle.razor
Source/Blazorise.Frolic/Button.razor
Source/Blazorise/BaseComponent.cs
Source/Blazorise/Button.razor
Source/Blazorise/Button.razor.cs
Source/Blazorise/Dropdown.razor.cs
Source/Blazorise/DropdownToggle.razor
Source/Blazorise/DropdownToggle.razor.cs
Source/Blazorise/Stores/DropdownStore.cs
docs/_docs/components/dropdown.md

#1205 Add Disabled property to Dropdown
- Added Disabled property to Dropdown
- Disabled property controls Button and DropdownToggle that are placed inside of Dropdown

Disabled property added to Dropdown component

---

Source/Blazorise/Radio.razor.cs
Source/Blazorise/RadioGroup.razor.cs

#1183 RadioGroup CheckedValue property change is not handled

Fixed two-way binding for RadioGroup

---

Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
docs/_docs/extensions/autocomplete.md

#1179 Autocomplete - add local ChangeTextOnKeyPress property

Add ChangeTextOnKeyPress and DelayTextOnKeyPress to Autocomplete

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

#1106 DataGrid access to FilteredData

Added FilteredDataChanged event to DataGrid

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/Column.razor.cs
Source/Blazorise/FluentColumn.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

#1262 Default column classname needs to be removed in some cases

fix: Default column classname needs to be removed in some cases

---

Source/Blazorise/Enums.cs
Source/Blazorise/ListGroup.razor.cs
Source/Blazorise/ListGroupItem.razor.cs
Source/Blazorise/Stores/ListGroupStore.cs

ListGroup should by default be a static list. This PR fixed that.

Fixed ListGroup selecting mode

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/BarToggler.razor
Source/Blazorise.AntDesign/Styles/_bar.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise/BarToggler.razor.cs

Fixes issues outstanding in #1042 after PR part 1 (#1287)
- AntDesign `BarToggler` fixes
- AntDesign nested `BarDropdownMenus`
- Summary comments in code for new parameters (e.g. Bar parameter for BarToggler, etc)

Vertical Bar fixes

---

docs/_docs/components/bar.md

@stsrki this is still a WIP. 
Feedback welcome!
Docs for new Bar features added by #1042

Bar docs for 0.9.2

---

Source/Blazorise/RadioGroup.razor.cs

Fix RadioGroup bindings.

---

Source/Blazorise.AntDesign/BarDropdownItem.razor
Source/Blazorise.AntDesign/BarLink.razor
Source/Blazorise.AntDesign/BreadcrumbLink.razor
Source/Blazorise.Bulma/BreadcrumbLink.razor
Source/Blazorise/BarDropdownItem.razor
Source/Blazorise/BarLink.razor
Source/Blazorise/BreadcrumbLink.razor

Added missing Attributes

---

Source/Blazorise/DateEdit.razor.cs

Fixed DateEdit click event called on Disabled mode

---

Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/Styles/_functions.scss
Source/Blazorise.Frolic/Styles/_utilities.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor

Fixed #1271 pagination layout since it was working properly only for Bootstrap provider.

Datagrid pager layout

---

README.md
docs/_docs/start.md

Updated docs to address commonly asked issue regarding JS file layouts in `index.html` (WASM) and `_Host.cshtml` (SS).

docs: JS layout for common issue

---

Demos/Blazorise.Demo/Pages/Tests/ChartsPage.razor
Source/Extensions/Blazorise.Charts/BaseChart.cs
Source/Extensions/Blazorise.Charts/JS.cs
Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js

Add function SetData on BaseChart to resolve part of [feature request: Chart Ability To Remove And Set Data On Datasets](https://github.com/stsrki/Blazorise/issues/1343)

Add SetData on BaseChart

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/Enums.cs
docs/_docs/extensions/datagrid.md
docs/_docs/helpers/enums.md

Addressed the feature request of #967. "It ain't much, but it's honest work" ;)

Added sort mode to data grid

---

Source/Blazorise/Validation.razor.cs
Source/Blazorise/Validations.razor.cs
docs/_docs/components/validation.md

#1371 
Specify EditContext explicitly on a Validations and ability to change the Model reference

Specify EditContext explicitly on a Validations

---

Build/Blazorise.Client.props
Build/Blazorise.Demo.props
Build/Blazorise.Server.RC.props
Build/Blazorise.Server.props
Build/Blazorise.props
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Server/BasicTestApp.Server.csproj
Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj

Updated all projects to .Net 5 RC 2

---

Source/Blazorise.AntDesign/BarLink.razor
Source/Blazorise.AntDesign/BreadcrumbLink.razor
Source/Blazorise.Bulma/BreadcrumbLink.razor
Source/Blazorise/BarLink.razor
Source/Blazorise/BarLink.razor.cs
Source/Blazorise/BreadcrumbLink.razor
Source/Blazorise/BreadcrumbLink.razor.cs
Source/Blazorise/Enums.cs
Source/Blazorise/Link.razor.cs
Source/Blazorise/Utils/LinkHelpers.cs
Source/Extensions/Blazorise.Sidebar/SidebarLink.razor
Source/Extensions/Blazorise.Sidebar/SidebarLink.razor.cs
docs/_docs/components/bar.md
docs/_docs/components/breadcrumb.md
docs/_docs/components/link.md
docs/_docs/helpers/enums.md

#1390 BarLink Still Ignores Attributes
- Added Target parameter to all link components
- Updated docs

Add Target parameter to all link components

---

Source/Blazorise/BaseCheckComponent.cs
Source/Blazorise/BlazoriseOptions.cs
Source/Blazorise/ColorEdit.razor.cs
Source/Blazorise/Config.cs
Source/Blazorise/DateEdit.razor.cs
Source/Blazorise/EditContextValidator.cs
Source/Blazorise/EventArguments.cs
Source/Blazorise/MemoEdit.razor.cs
Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/Select.razor.cs
Source/Blazorise/TextEdit.razor.cs
Source/Blazorise/TimeEdit.razor.cs
Source/Blazorise/Validation.razor.cs
Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs
docs/_docs/components/validation.md

#1371 Reinitialize EditContext on Validations
#1386 Validation localization
- Optimized the usage of `MessageLocalizer`
- Fixed bug with data-annotations when the model would change
- Updated docs

Validation optimizations and bug fixes

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/Tabs.razor.cs

#1384 nav-pills & nav-tabs should not be using together

Fixed nav-piils applied for nav-tabs

---

Demos/Blazorise.Demo/Pages/Tests/ChartsPage.razor
Source/Extensions/Blazorise.Charts/BaseChart.cs
Source/Extensions/Blazorise.Charts/ChartData.cs
Source/Extensions/Blazorise.Charts/JS.cs

#983 Add multiline labels support for ChartJS component

Chart labels converted from string to object

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Pages/Tests/ButtonsPage.razor
Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Demos/Blazorise.Demo/Pages/Tests/FigurePage.razor
Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Demos/Blazorise.Demo/Pages/Tests/ProgressBarsPage.razor
Demos/Blazorise.Demo/Pages/Tests/RichTextEditPage.razor
Demos/Blazorise.Demo/Pages/Tests/TabsPage.razor
Demos/Blazorise.Demo/Pages/Tests/TypographyPage.razor
Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor

#758 Optimize demo apps for mobile

Optimizations of demo app for mobile

---

Source/Blazorise.AntDesign/BarDropdownItem.razor
Source/Blazorise/BarDropdownItem.razor
Source/Blazorise/BarDropdownItem.razor.cs
Source/Blazorise/BarLink.razor.cs
Source/Blazorise/Link.razor.cs

resolve #1432 BarDropdownItem Ignores Target

Adds Target parameter to dropdown item

---

Source/Extensions/Blazorise.DataGrid/BaseDataGridComponent.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/PaginationContext.cs
Source/Extensions/Blazorise.DataGrid/PaginationTemplates.cs
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor.cs

Fixed DataGrid pagination

---

Source/Blazorise/FileEdit.razor.cs

Fixes FileEdit validation

---

Source/Blazorise.Bootstrap/Styles/_pagination.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Bulma/PaginationLink.razor

Fixes pagination item pointer form Bootstrap and Bulma providers

Dev092 pagination pointer

---

Source/Blazorise/Styles/_bar.scss
Source/Blazorise/wwwroot/blazorise.css

Fixes #1378
This could be a patch or new feature in 0.9.3

[Bug] Stop text highlighting on vertical bar

---

Source/Blazorise.AntDesign/Select.razor
Source/Blazorise.AntDesign/Select.razor.cs
Source/Blazorise.AntDesign/SelectItem.razor
Source/Blazorise.AntDesign/SelectItem.razor.cs
Source/Blazorise/Select.razor.cs
Source/Blazorise/SelectItem.razor.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

resolve #1473 Antdesign bugs on v0.9.2

Fixed and optimized AntDesign select component

---

Source/Blazorise/BaseTextInput.razor.cs
Source/Blazorise/DateEdit.razor.cs
Source/Blazorise/NumericEdit.razor.cs
Source/Blazorise/TextEdit.razor.cs
Source/Blazorise/TimeEdit.razor.cs
Source/Blazorise/Validation.razor.cs

resolve #1469 Updating TextEdit Pattern and triggering a revalidation doesn't have any effect.

Dynamic change of Validation pattern

---

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Source/Blazorise/Extensions.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
docs/_docs/extensions/autocomplete.md
docs/_docs/extensions/dropdownlist.md

resolve #1484 Allow Autocomplete to set value type

TValue added to Autocomplete component

---

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Source/Extensions/Blazorise.Components/DropdownList.razor
Source/Extensions/Blazorise.Components/DropdownList.razor.cs
docs/_docs/extensions/dropdownlist.md

resolve #1475 Typed value for DropDownList to match 0.9.2 changes to SelectList

TValue added to DropdownList component

---

Source/Blazorise/BarIcon.razor
Source/Blazorise/BarIcon.razor.cs
Source/Blazorise/Icon.razor.cs

resolve #1488 BarIcon IconStyle

IconStyle added to BarIcon

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/CellEditContext.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEditValidation.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCellEditValidation.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs

resolve #852 DataGrid EditTemplate get row data
resolve #1465

Added Item to CellEditContext

---

Source/Blazorise/RadioGroup.razor.cs

fix #1508 Validation NullReference Exception

Fixed RadioGroup validation

---

Source/Blazorise/RadioGroup.razor.cs

Revert "Fixed RadioGroup validation"

---

Source/Extensions/Blazorise.Charts/ChartData.cs

resolve #1490 Mix Bar Line Chart

Added Type field to ChartDataset

---

Source/Blazorise.AntDesign/Button.cs
Source/Blazorise.Bootstrap/Button.cs
Source/Blazorise.Bulma/Button.cs
Source/Blazorise.Frolic/Button.cs
Source/Blazorise/Button.cs

resolve #1516 Command no longer called upon clicking a button

Button not using Command handler

---

Build/Blazorise.props
docs/_posts/2020-11-21-release-notes-092-1.md

Chart :  Update argument from AddLabelsDatasetsAndUpdate to support object (multi-line labels)

Chart :  Update argument from AddLabelsDatasetsAndUpdate to support object (multi-line labels)

---

Demos/Blazorise.Demo/Pages/Tests/ModalsPage.razor
Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor
Source/Blazorise/BaseComponent.cs
Source/Blazorise/BaseInputComponent.razor.cs
Source/Blazorise/IFocusableComponent.cs
Source/Blazorise/Modal.razor.cs

resolve #1530 Autofocus for input components

Adds support for autofocus of input components

---

Demos/Blazorise.Demo.Bulma.Server/Properties/launchSettings.json
Demos/Blazorise.Demo.Bulma/Properties/launchSettings.json
Source/Blazorise.AntDesign/Styles/_animations.scss
Source/Blazorise.AntDesign/Styles/_bar.scss
Source/Blazorise.AntDesign/Styles/_dropdown.scss
Source/Blazorise.AntDesign/Styles/_modal.scss
Source/Blazorise.AntDesign/Styles/blazorise.antdesign.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/Styles/_animations.scss
Source/Blazorise.Bootstrap/Styles/_dropdown.scss
Source/Blazorise.Bootstrap/Styles/_modal.scss
Source/Blazorise.Bootstrap/Styles/blazorise.bootstrap.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Bulma/Styles/_animations.scss
Source/Blazorise.Bulma/Styles/_bar.scss
Source/Blazorise.Bulma/Styles/_dropdown.scss
Source/Blazorise.Bulma/Styles/_modal.scss
Source/Blazorise.Bulma/Styles/blazorise.bulma.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Material/Styles/_animations.scss
Source/Blazorise.Material/Styles/_dropdown.scss
Source/Blazorise.Material/Styles/_modal.scss
Source/Blazorise.Material/Styles/blazorise.material.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

https://github.com/abpframework/abp/issues/5600

Created animations for modals and dropdowns

---

Source/Blazorise.AntDesign/Check.razor
Source/Blazorise/Check.razor.cs
Source/Blazorise/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js
docs/_docs/components/check.md

resolve #1467 Support indeterminate property of the checkbox

Indeterminate parameter for Check component

---

Source/Blazorise/MemoEdit.razor

resolve #874 MemoEdit does not have Feedback Validation Erro

Feedback missing from MemoEdit

---

Source/Blazorise.Bootstrap/Field.razor.cs

resolve #1548 Blazorise emitting multiple col classes for fields

Emitting multiple col classes for Bootstrap fields

---

Source/Blazorise/BaseCheckComponent.cs
Source/Blazorise/Check.razor.cs
Source/Blazorise/Radio.razor.cs
Source/Blazorise/RadioGroup.razor.cs
Source/Blazorise/Switch.razor.cs

RadioGroup Validation not working

---

Source/Blazorise/Validation.razor.cs

Validation error message not shown

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/RadioGroup.razor
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/ClassProvider.cs
Source/Blazorise/IClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Source/Blazorise/RadioGroup.razor
Source/Blazorise/RadioGroup.razor.cs

resolve #1571 RadioGroup validation display issue

RadioGroup validation feedback

---

Demos/Blazorise.Demo/Pages/Tests/RichTextEditPage.razor
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs
Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js

Added events EditorFocus and EditorBlur for RichTextEdit

Added events EditorFocus and EditorBlur for RichTextEdit

---

Source/Extensions/Blazorise.Charts/ChartModel.cs

resolve #1600 ChartModels missing label property

Add mising Label property to chart models

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

resolve #1621 Datagrid SelectedRow default background color

DataGrid selected row contextual color

---

Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor

fix #1572 Page selector does not work and is disappeared on demo sites

Page selector not visible

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

resolve #1583 Add PageSizeChanged to DataGrid

Add PageSizeChanged event to DataGrid

---

Demos/Blazorise.Demo/Pages/Tests/ButtonsPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/DropdownItem.razor
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_dropdown.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Dropdown/DropdownItem.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

Add disabled state for DropdownItem

---

Source/Blazorise/Base/BaseInputComponent.razor.cs
Source/Blazorise/Components/TextEdit/TextEdit.razor.cs

fixed #1402 Empty TextEdit is Null instead of Empty String

TextEdit default value for empty input

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor

- Page selector only visible on mobile. Undo previous commit. https://github.com/stsrki/Blazorise/commit/ee2f09ea1da6cd54f720cc43fae1461b4476422a#commitcomment-45356723
- Fixed page selector not triggering either StateHasChanged or HandleReadData. #1572

Datagrid: fix page selector

---

Source/Blazorise/wwwroot/blazorise.js

fix #1597 FileEdit not removing file names after reset()

Fixes FileEdit reset

---

Demos/Blazorise.Demo.Bulma/wwwroot/index.html
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Field.razor.cs
Source/Blazorise.Bulma/Fields.razor
Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor

Bulma upgrade

---

docs/_docs/extensions/datagrid.md

Hello RowDetailTrigger should be DetailRowTrigger in docs

RowDetailTrigger should be DetailRowTrigger in docs

---

Source/Blazorise/Validation.razor.cs

fixes #1665 [BUG] Set e.ErrorText don't update ValidationError message

Validation notification status not changed

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

fixes #1609 Datagrid regression from 0.9.2.2 to 0.9.2.3 onwards

DataGrid - fix double ReadData

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs

fixes #1674 Not able to change primary text color

Added !important flag for Bootstrap text colors

---

Source/Blazorise.AntDesign/DropdownMenu.razor.cs
Source/Blazorise.Bootstrap/Styles/_dropdown.scss
Source/Blazorise.Bootstrap/Styles/_table.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Material/Styles/_dropdown.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css
Source/Blazorise/Components/Button/Button.cs
Source/Blazorise/Components/Dropdown/Dropdown.razor.cs
Source/Blazorise/Components/Dropdown/DropdownItem.razor.cs
Source/Blazorise/Components/Dropdown/DropdownMenu.razor.cs
Source/Blazorise/Stores/DropdownStore.cs

resolves #1657 DropdownItem should put the mouse pointer to "hand icon"
resolves #1709 Direction of Dropdown
fixes #1675 Dropdown stays behind of datagrid container

Dropdown fixes and optimizations

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Table.razor
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/Styles/_table.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Table.razor
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Dropdown/Dropdown.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs
Source/Blazorise/Components/Table/Table.razor
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

fix #1675
- reverted previous change
- fixed dropdown issue with a responsive table (Bootstrap)

Fix dropdown responsive table

---

Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs
docs/_docs/extensions/selectlist.md

Add MaxVisibleItems to SelectList

---

Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs

DataGrid FunctionCompiler work better with inherited members

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Trigger DataGrid reload mode externally

---

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/FilterContext.cs

Removed unnecessary FilterContext from DataGridColumn

---

Source/Blazorise/Base/BaseInputComponent.razor.cs
Source/Blazorise/Components/Validation/Handlers/DataAnnotationValidationHandler.cs
Source/Blazorise/Components/Validation/Handlers/PatternValidationHandler.cs
Source/Blazorise/Components/Validation/Handlers/ValidatorValidationHandler.cs
Source/Blazorise/Components/Validation/IValidation.cs
Source/Blazorise/Components/Validation/IValidationHandler.cs
Source/Blazorise/Components/Validation/IValidationHandlerFactory.cs
Source/Blazorise/Components/Validation/Validation.razor
Source/Blazorise/Components/Validation/Validation.razor.cs
Source/Blazorise/Components/Validation/ValidationHandlerFactory.cs
Source/Blazorise/Components/Validation/Validations.razor
Source/Blazorise/Config.cs
Tests/BasicTestApp.Client/DateEditComponent.razor
Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs
docs/_posts/2020-12-15-release-notes-093.md

resolves 
- #995
- #996
- #1029
- #1515

Validation handlers and other improvements

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Base/BaseCheckComponent.cs
Source/Blazorise/Base/BaseInputComponent.razor.cs
Source/Blazorise/Base/BaseTextInput.razor.cs
Source/Blazorise/Components/Check/Check.razor.cs
Source/Blazorise/Components/DateEdit/DateEdit.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Components/Radio/Radio.razor.cs
Source/Blazorise/Components/Switch/Switch.razor.cs
Source/Blazorise/Components/TextEdit/TextEdit.razor.cs
Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

resolve #1736 'form-control' class appended twice for Components that inherit BaseTextInput<TValue>

Input components duplicate classes

---

Source/Blazorise/Utilities/Converters.cs

Cast value directly in case ChangeType failed

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Source/Blazorise.Bulma/DateEdit.razor
Source/Blazorise/Components/DateEdit/DateEdit.razor
Source/Blazorise/Components/DateEdit/DateEdit.razor.cs
Source/Blazorise/Enums/DateInputMode.cs
Source/Blazorise/Enums/TextInputMode.cs
Source/Blazorise/Extensions/EnumExtensions.cs
Source/Blazorise/Utilities/Parsers.cs
docs/_docs/components/date.md
docs/_docs/helpers/enums.md
docs/_examples/forms/datetime.html

Add DateTime input support to DateEdit 

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs

fixes #1766 Dropdown Selected Element on Dark Colors

Fix DropdownItem active color

---

Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs

DataGrid: fix problem with nested fields

---

Source/Blazorise.AntDesign/Table.razor
Source/Blazorise.AntDesign/TableRowHeader.razor
Source/Blazorise.Bulma/Table.razor
Source/Blazorise/Base/BaseDraggableComponent.cs
Source/Blazorise/Components/Table/Table.razor
Source/Blazorise/Components/Table/Table.razor.cs
Source/Blazorise/Components/Table/TableBody.razor
Source/Blazorise/Components/Table/TableBody.razor.cs
Source/Blazorise/Components/Table/TableFooter.razor
Source/Blazorise/Components/Table/TableFooter.razor.cs
Source/Blazorise/Components/Table/TableHeader.razor
Source/Blazorise/Components/Table/TableHeader.razor.cs
Source/Blazorise/Components/Table/TableHeaderCell.razor
Source/Blazorise/Components/Table/TableHeaderCell.razor.cs
Source/Blazorise/Components/Table/TableRow.razor
Source/Blazorise/Components/Table/TableRow.razor.cs
Source/Blazorise/Components/Table/TableRowCell.razor
Source/Blazorise/Components/Table/TableRowCell.razor.cs
Source/Blazorise/Components/Table/TableRowHeader.razor
Source/Blazorise/Components/Table/TableRowHeader.razor.cs

Table drag and drop events

---

Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Bulma/Styles/_jumbotron.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css

fixes #1813 Primary Color Not Changing for Hero

Fixed Bulma Jumbotron color classnames

---

Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

fixes #1293 Autocomplete - Selection list does not close
fixes #1296 Autocomplete - If no matches are found, a small empty dropdown is shown.

Fixes Autocomplete focus and empty dropdown

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_form.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Radio.razor
Source/Blazorise.Bulma/Styles/_form.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_form.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise/Components/Button/Button.cs
Source/Blazorise/Components/Button/Buttons.razor.cs
Source/Blazorise/Components/Radio/Radio.razor.cs
Source/Blazorise/Components/Radio/RadioGroup.razor.cs
Source/Blazorise/Enums/Orientation.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/radio.md
docs/_docs/helpers/enums.md
docs/_posts/2020-12-15-release-notes-093.md

resolves #1224 RadioGroup vertical display
**Done:**
- Added Orientation mode to ButtonGroup
- Support for the vertical button where it was missing (Bulma)
- Update docs and release notes

Vertical RadioGroup

---

Source/Extensions/Blazorise.Charts/ChartData.cs
Source/Extensions/Blazorise.Charts/IndexableOption.cs
Source/Extensions/Blazorise.Charts/IndexableOptionsConverter.cs

resolves #1458 First Element in Chart grey on the hower
Done:
- added IndexableOption so that it's possible to define both single and array values for colors
- added converter for system text JSON serializer
- handle null values
This PR was the result of IndexableOption done by @Joelius300 so I would like to thank him!

Implemented IndexableOption and IndexableOptionConverter for chart extension

---

Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs

JSInterop fix

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Source/Blazorise.AntDesign/Radio.razor
Source/Blazorise.Bootstrap/Radio.razor
Source/Blazorise.Bulma/Radio.razor
Source/Blazorise.Frolic/Radio.razor
Source/Blazorise/Components/Radio/Radio.razor.cs
Source/Blazorise/Components/Radio/RadioGroup.razor.cs
docs/_docs/components/button.md
docs/_docs/components/radio.md

resolves #951 Theme options for Radio/RadioGroup
Done:
- Color parameter added to RadioGroup
- Theming is supported through the regular buttons color

RadioGroup color parameter

---

Source/Blazorise/Components/Bar/BarDropdownItem.razor.cs
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs

resolves #1849 BarDropdownItem padding

Add Indentation to BarDropdownItem and BarDropdownToggle

---

Source/Blazorise/Components/Divider/Divider.razor.cs

fixes #1195 DividerType in Theme.DividerOptions not working

Update Divider when Theme settings changes

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

resolves #437 Autocomplete show textvalue after selectchange

Show autocomplete text according to currently focused item

---

Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.css
Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs
Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js

Fix for [1861](https://github.com/stsrki/Blazorise/issues/1861)

RTE - Tooltips might (partly) disappear behind sidebar

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

MultiSelect: Fix checkbox uncheck and multiselectall uncheck, should unselect 'SelectedRow'
#1859

MultiSelect: Fix checkbox uncheck and multiselectall uncheck, should unselect 'SelectedRow'

---

Source/Blazorise.Bootstrap/Styles/_layout.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Material/Styles/_layout.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

Adjust bar header and bar footer z-index for Bootstrap

---

Source/Blazorise/Components/Bar/Bar.razor.cs

fixes #1617 Using Bar (vertical), first render as Visible = false

Only toggle Bar on first render if breakpoint is broken

---

Source/Blazorise/Components/Validation/IValidationInput.cs
Source/Blazorise/Components/Validation/Validation.razor.cs

fixes #1882 Validation is still being called when Disabled=true

Don't run validation if input is disabled

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridMultiSelectAll.razor
Source/Extensions/Blazorise.DataGrid/_DataGridMultiSelectAll.razor.cs

Data grid check all indeterminate state

---

Demos/Blazorise.Demo/Pages/Tests/RichTextEditPage.razor
Source/Blazorise/Base/BaseComponent.cs
Source/Extensions/Blazorise.RichTextEdit/BaseRichTextEditComponent.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.cs
Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js

Fix for RichTextEdit issue [1752](https://github.com/stsrki/Blazorise/issues/1752)

RTE - Queue requests for after render and support for content updates

---

Source/Blazorise/Utilities/AsyncDisposable.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs

Add support for RTE async dispose

---

Demos/Blazorise.Demo/Pages/Tests/TreeViewPage.razor
Source/Extensions/Blazorise.TreeView/Configuration/NodeStyling.cs
Source/Extensions/Blazorise.TreeView/TreeView.razor
Source/Extensions/Blazorise.TreeView/TreeView.razor.cs
Source/Extensions/Blazorise.TreeView/_TreeViewNode.razor
Source/Extensions/Blazorise.TreeView/_TreeViewNode.razor.cs
Source/Extensions/Blazorise.TreeView/_TreeViewNodeContent.razor
Source/Extensions/Blazorise.TreeView/_TreeViewNodeContent.razor.cs

TreeView Selected Class: Added Selected Node Class

---

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor.cs

Add EditOrder to DataGridColumn.
Fixed problems with order in inline edit mode.

Add EditOrder to DataGridColumn

---

Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs

Catch RTE canceled task

---

Source/Blazorise/Components/Select/Select.razor.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js

fixes #1100 Select component doesn't recognize changes by code

Fix Multiple Select not being updated programatically

---

Source/Extensions/Blazorise.Snackbar/Styles/blazorise.snackbar.scss
Source/Extensions/Blazorise.Snackbar/wwwroot/blazorise.snackbar.css

fixes #1944 Snackbar seems broken in version 0.9.3

Snackbar position

---

Build/Blazorise.Server.RC.props
Build/Blazorise.Server.props
Build/Blazorise.props
Demos/Blazorise.Demo.Bootstrap.RC/Startup.cs
Source/Blazorise/Base/BaseAfterRenderComponent.cs
Source/Blazorise/Base/BaseComponent.cs
Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Source/Blazorise/Components/Button/Button.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs
Source/Blazorise/Components/FileEdit/FileEdit.razor.cs
Source/Blazorise/Components/Modal/Modal.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Components/TextEdit/TextEdit.razor.cs
Source/Extensions/Blazorise.DataGrid/BaseDataGridComponent.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Tests/Blazorise.Tests/ButtonTest.cs

The first prototype of using IAsyncDisposable to clean the component and call JSInterop.
The purpose of this PR is to resolve issues with #1920

IAsyncDisposable

---

Source/Blazorise/Base/BaseAfterRenderComponent.cs

Small optimizations according to https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync

DisposeAsync optimizations

---

Source/Blazorise/Utilities/IDGenerator.cs

Use a cached delegate in the IdGenerator class.

---

Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

Fixed missing SelectedValueExpression from SelectList

---

Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs

fixes #1989 Step is missing theme CSS for primary color

Fix setp item active color

---

Source/Blazorise/Resources/Localization/Carousel/it.json
Source/Blazorise/Resources/Localization/FileEdit/it.json
Source/Extensions/Blazorise.DataGrid/Resources/Localization/DataGrid/it.json

@devrushnet check this please.
@stsrki I think that all translations in italian is fixed.

Italian translation

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Slider/Slider.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

fixes #2029 Slider error when changed

Fixes Slider validation

---

Source/Blazorise/wwwroot/blazorise.js

fixes #2030 DataGrid's Modal/Popup behavior

Don't close modal on click release

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

fixes #2011 MemoEdit - Size doesn't work

MemoEdit Size parameter is not applied

---

Source/Blazorise.Material/MaterialThemeGenerator.cs

fixes #2010 ThemeStepsOptions doesn't work (Material)

Fix material active step color

---

Source/Blazorise.AntDesign/Select.razor.cs

fixes #2016 AntDesign Select does not work

Fix AntDesign Select rendering

---

Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js

fixes #2036 Modal scrolling issue

Fixes modal scroll

---

Source/Blazorise.Bootstrap/Radio.razor
Source/Blazorise/Base/BaseInputComponent.razor.cs
Source/Blazorise/Components/Radio/Radio.razor.cs
Source/Blazorise/Components/Radio/RadioGroup.razor.cs

fixes #2051 [RadioGroup] Manual validation
fixes #1887 introduce difference for disabled radio button

RadioGroup fixes

---

Source/Blazorise.AntDesign/Select.razor
Source/Blazorise.AntDesign/Select.razor.cs

resolves #2059 MultiSelect dos not closed oblur

Sup093 antdesign select blur

---

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor

resolves #2065 Class setting on DataGridRow Command

Apply CellStyle to datagrid command column

---

.gitignore
NuGet/dotnet-pack.bat
NuGet/pack.bat
NuGet/push-myget.bat
NuGet/push.bat

resolves #2054 Debug symbols for Blazorise

NuGet debug symbols

---

Source/Blazorise/Components/Validation/Validation.razor.cs
Source/Blazorise/Components/Validation/Validations.razor.cs

fixed #2078 Validation threading issue

Fixed Validation threading issue

---

Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs

fixes #2082 DataGrid editing nested fields

Fix DataGrid nested field accesor

---

Source/Blazorise/Components/Button/Button.cs
Tests/Blazorise.Tests/ButtonTest.cs

See [2067](https://github.com/stsrki/Blazorise/issues/2067)

ICommand.CanExecute behavior disables button

---

Demos/Blazorise.Demo/Pages/Tests/LiveChartsPage.razor.cs

fixes #1999 v0.9.3 - HorizontalBarChart not working (Material)

Fixed horizontal bar live chart demo

---

Source/Blazorise/wwwroot/blazorise.js

fixes #2044 JSException when viewed on Edge mobile app

Remove JS optional chaining

---

Source/Blazorise/Components/Bar/Bar.razor.cs

fixes #1959 Hamburger Menu Drop Down Not Correct when Browser is Refreshed

Set Bar broken=true by default

---

Source/Blazorise.AntDesign/TextEdit.razor
Source/Blazorise.Bulma/MemoEdit.razor
Source/Blazorise.Bulma/NumericEdit.razor
Source/Blazorise.Bulma/TextEdit.razor
Source/Blazorise/Base/BaseTextInput.razor.cs
Source/Blazorise/Components/MemoEdit/MemoEdit.razor
Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor
Source/Blazorise/Components/Slider/Slider.razor
Source/Blazorise/Components/TextEdit/TextEdit.razor

fixes #2085 TextEdit input events refactoring
fixes #1134 Slider refresh value

Fix cursor jumping when fast typing

---

Source/Blazorise.AntDesign/Button.cs
Source/Blazorise.Bootstrap/Button.cs
Source/Blazorise.Bulma/Button.cs
Source/Blazorise.Frolic/Button.cs
Source/Blazorise/Components/Button/Button.cs
Source/Blazorise/Extensions/RenderTreeBuilderExtensions.cs

resolves #2057 Clicked not working as expected for Button of type Link.

Enable Clicked event for Link Button

---

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs
docs/_docs/extensions/selectlist.md

resolves #1401 SelectList defaultvalue

SelectList default item

---

Demos/Blazorise.Demo/Pages/Tests/RichTextEditPage.razor
Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs
Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js

See defect [2042](https://github.com/stsrki/Blazorise/issues/2042)

Improvements to content update events

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Button/Buttons.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

resolves #2139 Vertical button group is not working

Fixes Bootstrap vertical buttons

---

Source/Blazorise.Material/Styles/_layout.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

resolves #2134 Material Modal behind Layoutheader

Fix Material layout z-index

---

Source/Blazorise.AntDesign/Select.razor.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

resolves #2122 Unable to select items using Autocomplete extension

Increase onblur autoclose time

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/DataGridAggregate.cs
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor.cs

closes https://github.com/stsrki/Blazorise/issues/2161

DataGrid aggregation function

---

Source/Blazorise/Config.cs

resolves #2165 Memory-leak on Server-side Blazor

Register ComponentActivator as transient

---

Source/Blazorise.AntDesign/Styles/_tabs.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css

resolves #1529 Tabs Components

Add scrollbar for AntDesign Tabs overflow

---

Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js

resolves #1703 NumericEdit Decimal not dynamically handled

Dynamically update NumericEdit decimals

---

Source/Blazorise/Styles/_divider.scss
Source/Blazorise/Styles/_mixins.scss
Source/Blazorise/Styles/_variables.scss
Source/Blazorise/Styles/blazorise.scss
Source/Blazorise/Themes/Models/ThemeDividerOptions.cs
Source/Blazorise/wwwroot/blazorise.css

fixes #1165 Divider Thickness don't apply to DividerType.TextContent

Fix divider thickness

---

Source/Extensions/Blazorise.DataGrid/Resources/Localization/DataGrid/fr.json

Fix french translation

---

Source/Blazorise.AntDesign/Switch.razor
Source/Blazorise.Bootstrap/Switch.razor
Source/Blazorise.Bulma/Switch.razor
Source/Blazorise.Frolic/Switch.razor
Source/Blazorise.Material/Switch.razor
Source/Blazorise/Components/Switch/Switch.razor

fixes #1083 Switch ReadOnly, Disabled unexpected behavior

Fixes Switch ReadOnly behavior

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridNumericColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEditValidation.razor

resolves #1416 Add Decimals and DecimalsSeparator to NumericEdit in the _BaseDataGridCellEdit for DataGridNumericColumn

Additional parameters for DataGridNumericColumn

---

Source/Blazorise.AntDesign/AntDesignThemeGenerator.cs
Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bulma/BulmaThemeGenerator.cs
Source/Blazorise.Frolic/FrolicThemeGenerator.cs
Source/Blazorise/Themes/Models/ThemeButtonOptions.cs

resolves #647 Change a button's disabled properties

Add button disabled opacity to theme options

---

Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise.Bulma/Styles/_form.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Material/Styles/_form.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

resolves #2116 Readonly or Disabled attribute for SelectList component

ReadOnly Select

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

fixes #1602 Autocomplete with some data containing null

Fix Autocomplete TextField null exception

---

Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Utilities/MathUtils.cs
Source/Blazorise/wwwroot/blazorise.js
Tests/Blazorise.E2ETests/NumericEditTest.cs

resolves
- #993 NumericEdit: add option to allow only positive values
- #1696 NumericEdit issues with Min=0
- #1733 NumericEdit with steps button
- #1892 NumericEdit Min="0" allows negative values
- #1286 Strange step behaviour in NumericEdit

NumericEdit improvements

---

Source/Blazorise.Frolic/ProgressBar.razor
Source/Blazorise/Components/Progress/ProgressBar.razor
Source/Blazorise/Components/Progress/ProgressBar.razor.cs

resolves #2200 ProgressBar percentage

Dynamically calculate progress bar percentage

---

Source/Blazorise.Bootstrap/Config.cs
Source/Blazorise.Bootstrap/NumericEdit.razor
Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs

resolves #1733 NumericEdit with steps button
Only Bootstrap provider is done with this PR. For other PR I will do them per request, as needed.

Spin buttons for Bootstrap NumericEdit

---

Source/Blazorise.Bootstrap/NumericEdit.razor
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs

resolves #1733 NumericEdit with steps button

Spin buttons should not change NumericEdit in read only

---

Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs

resolves #2043 BarDropdownToggle - Can there be a Clicked handler added

Add Clicked event on toggle components

---

Source/Blazorise.AntDesign/AntDesignStyleProvider.cs
Source/Blazorise.Bootstrap/BootstrapStyleProvider.cs

resolves #2215 Modal is not centered when it is set to center

Remove padding-right for centered Modal

---

Source/Blazorise/wwwroot/blazorise.js

resolves #2211 ReadOnly NumericEdit still editable using arrow keys

Don't allow change of NumericEdit ReadOnly

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Pages/Tests/BordersPage.razor
Demos/Blazorise.Demo/Pages/Tests/FlexPage.razor
Demos/Blazorise.Demo/Pages/Tests/LayoutPage.razor
Demos/Blazorise.Demo/Pages/Tests/SizingPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_utilities.scss
Source/Blazorise.AntDesign/Styles/_variables.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/Styles/_variables.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_utilities.scss
Source/Blazorise.Frolic/Styles/_variables.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise/Base/BaseComponent.cs
Source/Blazorise/Enums/SizingSize.cs
Source/Blazorise/Enums/SizingType.cs
Source/Blazorise/Fluent/FluentFlex.cs
Source/Blazorise/Fluent/FluentSizing.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Tests/Blazorise.Tests/SizingTest.cs

resolves #942 
Done:
- fluent builder for Width and Height
- sizes 25% - 100%
- min, max, and viewport rules
- demo page
- fixed Float utility build

Sizing utilities

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Fluent/FluentDisplay.cs
Source/Blazorise/Fluent/FluentFlex.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Tests/Blazorise.Tests/FluentDisplayTest.cs
Tests/Blazorise.Tests/FluentFlexTest.cs

resolves #2243 Add Condition to Display utility
Adds an `.If(...)` rule for Display and Flex

Conditions for Display and Flex utility

---

Source/Blazorise/BlazoriseOptions.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
docs/_docs/components/numeric.md

closes #2230 NumericEdit set ShowSpinButtons option globally

Global options for ShowSpinButtons

---

Source/Blazorise/Components/Modal/ModalTitle.razor
Source/Blazorise/Components/Modal/ModalTitle.razor.cs
docs/_docs/components/modal.md

closes #2232 Modal Title HeadingSize

Add SIze parameter on ModalTitle

---

Demos/Blazorise.Demo/Pages/Dashboard.razor
Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor
Demos/Blazorise.Demo/Pages/Tests/TypographyPage.razor
Source/Blazorise/Base/BaseComponent.cs
Source/Blazorise/Base/BaseTypographyComponent.cs
docs/_posts/2021-03-24-release-notes-094.md

resolves #2251 Move Typography parameters to BaseComponent class

Typography parameters moved to BaseComponent class

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Pages/Tests/VerticalAlignPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_utilities.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_utilities.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise/Base/BaseComponent.cs
Source/Blazorise/Enums/VerticalAlignment.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

Vertical alignment utility

---

Demos/Blazorise.Demo/Pages/Tests/LayoutPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_grid.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_utilities.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise/Components/Row/Row.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

Add NoGutters utility on Row column

---

Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor

resolves #2262 Show zeros when DataGrid have no items

Show zeros in DataGrid when no items found

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Button.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/Button.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Button.cs
Source/Blazorise.Frolic/Button.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Button/Button.cs
Source/Blazorise/Extensions/RenderTreeBuilderExtensions.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

resolves #2253 Link-Type Button cannot be Disabled

Disable link buttons

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/FileEdit.razor
Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css
Source/Blazorise/Components/FileEdit/FileEdit.razor.cs

resolves #2240 FileEdit filename text overflows the component
resolves #2252 FileEdit Validation

FileEdit fixes

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Pages/Tests/ShadowPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_utilities.scss
Source/Blazorise.AntDesign/Styles/_variables.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/Styles/_variables.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_utilities.scss
Source/Blazorise.Frolic/Styles/_variables.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise/Base/BaseComponent.cs
Source/Blazorise/Enums/Shadow.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

Shadow utility

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor.cs

resolves #1420 DataGrid row vertical alignment

Adds VerticalAlignment on DataGridColumn

---

Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

closes #2272 Add Disabled to SelectList

Adds Disabled parameter to SelectList

---

Demos/Blazorise.Demo/Pages/Tests/ButtonsPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_dropdown.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/DropdownToggle.razor
Source/Blazorise.Bulma/Styles/_dropdown.scss
Source/Blazorise.Bulma/Styles/_variables.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise.Frolic/Styles/_dropdown.scss
Source/Blazorise.Frolic/Styles/blazorise.frolic.scss
Source/Blazorise.Frolic/wwwroot/blazorise.frolic.css
Source/Blazorise/Components/Dropdown/DropdownHeader.razor
Source/Blazorise/Components/Dropdown/DropdownHeader.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/dropdown.md

closes #2281 DropdownHeader component

DropdownHeader component

---

Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js

Fix for [2268](https://github.com/stsrki/Blazorise/issues/2268)

RTE - SetDeltaAsync not working

---

Source/Blazorise.Material/Styles/_card.scss
Source/Blazorise.Material/Styles/blazorise.material.scss
Source/Blazorise.Material/wwwroot/blazorise.material.css

resolves #1510 z-index issue with autocomplete (and other items)

Fix Material dropdown menu overflow

---

Blazorise.sln
Demos/Blazorise.Demo.AntDesign/wwwroot/index.html
Demos/Blazorise.Demo.Bootstrap.RC/Pages/_Host.cshtml
Demos/Blazorise.Demo.Bootstrap/wwwroot/index.html
Demos/Blazorise.Demo.Bulma/wwwroot/index.html
Demos/Blazorise.Demo.Frolic/wwwroot/index.html
Demos/Blazorise.Demo.Material/wwwroot/index.html
Demos/Blazorise.Demo/Blazorise.Demo.csproj
Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Pages/Tests/SpinKitPage.razor
Demos/Blazorise.Demo/_Imports.razor
NuGet/dotnet-pack.bat
Source/Blazorise/Themes/Models/ThemeSpinKitOptions.cs
Source/Blazorise/Themes/Models/ThemeVariables.cs
Source/Blazorise/Themes/Theme.cs
Source/Blazorise/Themes/ThemeGenerator.cs
Source/Extensions/Blazorise.SpinKit/Blazorise.SpinKit.csproj
Source/Extensions/Blazorise.SpinKit/SpinKit.razor
Source/Extensions/Blazorise.SpinKit/SpinKit.razor.cs
Source/Extensions/Blazorise.SpinKit/SpinKitType.cs
Source/Extensions/Blazorise.SpinKit/_Imports.razor
Source/Extensions/Blazorise.SpinKit/wwwroot/blazorise.spinkit.css
docs/_docs/extensions/spinkit.md
docs/_docs/helpers/enums.md

closes #777 Spinkit Implementation

SpinKit extension

---

Source/Blazorise/Themes/ThemeGenerator.cs

resolves #1618 Able to set color in header

Add null checks for bar theme settings

---

Source/Blazorise/JSRunner.cs

resolves #2324 Multi-select SelectedValues returns distinct values

Remove distinct filter for multiple select values

---

Source/Blazorise.AntDesign/Select.razor.cs
Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs
Source/Blazorise/Components/FileEdit/FileEdit.razor.cs
Source/Blazorise/Components/Modal/Modal.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs

Set disposed DotNetObjectReference to null

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/PaginationTemplates.cs
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor.cs

Fix unused DataGrid pagination templates

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor.cs

fixes #2345 The value of DataGrid aggregate column will not be automatically updated with filtering

Calculate DataGrid aggregates based on filtered data

---

Demos/Blazorise.Demo/Pages/Tests/LayoutPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_grid.scss
Source/Blazorise.AntDesign/Styles/_mixins.scss
Source/Blazorise.AntDesign/Styles/_variables.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_layout.scss
Source/Blazorise.Bulma/Styles/_mixins.scss
Source/Blazorise.Bulma/Styles/_variables.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Row/Row.razor.cs
Source/Blazorise/Enums/RowColumnsSize.cs
Source/Blazorise/Fluent/FluentRowColumns.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
Tests/Blazorise.Tests/FluentRowColumnsTest.cs

resolves #2360 Implement Row Columns utility

Support for RowColumns on a Row component

---

Source/Extensions/Blazorise.Components/DropdownList.razor
Source/Extensions/Blazorise.Components/DropdownList.razor.cs

Adds missing parameters to DropdownList

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/BarDropdownDivider.razor
Source/Blazorise.AntDesign/Config.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise/Components/Bar/BarDropdownDivider.razor
Source/Blazorise/Components/Bar/BarDropdownDivider.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/bar.md

resolves #2391 Bar -> Add a BarDropdownDivider

BarDropdownDivider component

---

Demos/Blazorise.Demo/Pages/Tests/TypographyPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_utilities.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css
Source/Blazorise/Base/BaseComponent.cs
Source/Blazorise/Enums/TextOverflow.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/typography.md
docs/_docs/helpers/enums.md

resolves #2409 Add TextOverflow utility enum for BaseTypographyComponent

TextOverflow utility

---

Source/Blazorise/Utilities/Parsers.cs

fixes #2351 24 time format of TimePicker

Fix internal time format

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Material/MaterialThemeGenerator.cs

fixes #2374 EditText/Tab Underline - Theme

Fix input focused color

---

Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs

fixes #2437 Time Picker malfunction in 0.9.3.7

Fix TimeEdit internal format

---

Source/Blazorise.Bulma/DateEdit.razor
Source/Blazorise/Components/DateEdit/DateEdit.razor

fixes #2435 Date component Max attribute not working as expected with InputMode.DateTime

Fix Min and Max format for DateEdit

---

Source/Blazorise/Components/Modal/Modal.razor.cs

Null check for modal first FocusableComponent

---

Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor
Source/Blazorise.AntDesign/FileEdit.razor
Source/Blazorise.Bootstrap/FileEdit.razor
Source/Blazorise.Bulma/FileEdit.razor
Source/Blazorise/Components/FileEdit/FileEdit.razor
Source/Blazorise/Components/FileEdit/FileEdit.razor.cs
docs/_docs/components/file.md

resolves #2476 Placeholder for FileEdit

Placeholder for FileEdit component

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/ModalContent.razor
Source/Blazorise.AntDesign/Styles/_modal.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap/ModalContent.razor
Source/Blazorise.Bootstrap/ModalContent.razor.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Config.cs
Source/Blazorise.Bulma/ModalContent.cs
Source/Blazorise.Frolic/FrolicClassProvider.cs
Source/Blazorise/Components/Modal/ModalBody.razor.cs
Source/Blazorise/Components/Modal/ModalContent.razor
Source/Blazorise/Components/Modal/ModalContent.razor.cs
Source/Blazorise/Components/Modal/ModalFooter.razor.cs
Source/Blazorise/Components/Modal/ModalHeader.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/modal.md
docs/_posts/2021-03-24-release-notes-094.md

resolves #1946 Bootstrap > Modal Dialog > Support modal-dialog-scrollable

Modal dialog scrollable option

---

Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js
docs/_docs/components/date-picker.md

resolves #2422 New DatePicker recommendations
Done
- Monday as first day of week
- New API to open/close calendar

DatePicker improvements

---

Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise/Components/Tooltip/Tooltip.razor.cs
Source/Blazorise/Enums/TooltipPlacement.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs
docs/_docs/components/tooltip.md
docs/_docs/helpers/enums.md
docs/_posts/2021-03-24-release-notes-094.md

resolves #2509 Add new enums for Tooltip Placement

Add more positions for Tooltip placement

---

Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs

resolves #2508 Consider adding an overload of SnackbarStack.PushAsync that accepts a MarkupString

Add overloads for SnackbarStack to accept MarkupString

---

Demos/Blazorise.Demo/Pages/Tests/TablesPage.razor
Demos/Blazorise.Demo/Pages/Tests/TablesPage.razor.cs
Source/Blazorise/Components/Table/Table.razor.cs
Source/Blazorise/Enums/TableResizeMode.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/Styles/_table.scss
Source/Blazorise/Styles/blazorise.scss
Source/Blazorise/wwwroot/blazorise.css
Source/Blazorise/wwwroot/blazorise.js
docs/_docs/components/table.md

Table Resize

---

Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor.cs

Multiselect : Evaluate RowSelectable fix

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

To Patch 0.9.3
Should also be merged/cherry picked into dev094 (or just copy paste). Let me know.
Related to issue #2531

MultiSelectAll : RowSelectable not being evaluated fix

---

Source/Extensions/Blazorise.Charts/BaseChart.cs
Source/Extensions/Blazorise.Charts/BaseChartOfT.cs
Source/Extensions/Blazorise.Charts/IBaseChart.cs
Source/Extensions/Blazorise.Charts/JS.cs
Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js

resolves #1842 Chart: RemoveDataSet API

Chart: RemoveDataSet API

---

Source/Blazorise/Components/Progress/ProgressBar.razor
Source/Blazorise/Components/Progress/ProgressBar.razor.cs

resolves #2539 Settings ProgressBar Max doesn't do anything

Fix percentage calculation for ProgressBar

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor

Datagrid set to single selection + existing MultiSelectColumn with filterable set to false fix

---

Blazorise.sln
Demos/Blazorise.Demo.AntDesign/wwwroot/index.html
Demos/Blazorise.Demo.Bootstrap.RC/Pages/_Host.cshtml
Demos/Blazorise.Demo.Bootstrap/wwwroot/index.html
Demos/Blazorise.Demo.Bulma/wwwroot/index.html
Demos/Blazorise.Demo.Material/wwwroot/index.html
Demos/Blazorise.Demo/Blazorise.Demo.csproj
Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Pages/Tests/MarkdownPage.razor
Demos/Blazorise.Demo/_Imports.razor
NuGet/dotnet-pack.bat
Source/Extensions/Blazorise.Markdown/Blazorise.Markdown.csproj
Source/Extensions/Blazorise.Markdown/Markdown.razor
Source/Extensions/Blazorise.Markdown/Markdown.razor.cs
Source/Extensions/Blazorise.Markdown/_Imports.razor
Source/Extensions/Blazorise.Markdown/wwwroot/blazorise.markdown.js
docs/_data/navigation.yml
docs/_docs/extensions/markdown.md
docs/_posts/2021-03-24-release-notes-094.md

resolves #2415 Add Markdown editor component
**Done**
- basic two-way `Value` binding
- documentation and release notes

Markdown component

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

DataGrid : Handle SelectionMode Changed

---

Source/Extensions/Blazorise.Charts/ChartOptions.cs
docs/_posts/2021-03-24-release-notes-094.md

fixes #2547 BarThickness and MaxBarThickness

Move BarThickness and MaxBarThickness to Axis options

---

Source/Blazorise/Components/Carousel/Carousel.razor.cs

Select first slide of SelectedSlide is not set on initialization

---

Source/Blazorise.AntDesign/Bar.razor.cs
Source/Blazorise.AntDesign/CollapseHeader.razor
Source/Blazorise/Components/Validation/EditContextValidator.cs

Reverts Megabit/Blazorise#2583

Revert "Spelling"

---

Demos/Blazorise.Demo.AntDesign/Program.cs
Demos/Blazorise.Demo.Bootstrap/Program.cs
Demos/Blazorise.Demo.Bulma/Program.cs
Tests/BasicTestApp.Client/Program.cs

i dont think any of the demos do http requests?

Remove HttpClient from demos

---

Source/Blazorise/Base/BaseAfterRenderComponent.cs
Source/Blazorise/Components/Repeater/Repeater.cs
Source/Blazorise/Utilities/CountdownTimer.cs

no required when there is no Finalizer

remove redundant SuppressFinalize

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor.cs
Source/Extensions/Blazorise.DataGrid/CellEditContext.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
docs/_docs/extensions/datagrid.md

resolves #2586 DataGrid UpdateEditingCell API
Cell can be changed in two ways:
1. through the edit context: `context.UpdateCell( nameof( Employee.FirstName ), "some value" )`
2. or through datagrid reference: `dataGridRef.UpdateCellEditValue( nameof( Employee.FirstName ), "some value" )`

DataGrid UpdateEditingCell API

---

Source/Blazorise/wwwroot/blazorise.js

Resize Event for recalculation of Fixed Header feature

---

Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor
Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/EventArguments.cs

resolves #2612 Capture DataGrid sort column/direction and page state

DataGrid Sort API

---

Source/Blazorise/Components/Tooltip/Tooltip.razor.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js

resolves #2629 Tooltip text is not updated on @bind-Text

Change Tooltip content dynamically

---

Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/wwwroot/blazorise.js

fixes #2639 DatePicker - Validation does not change border color

DatePicker classnames not applied

---

Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css

fixes #2632 Set numerical field buttons deeper in the field

Fix normal NumericEdit buttons radius

---

Source/Extensions/Blazorise.Charts/BaseChart.cs
Source/Extensions/Blazorise.Charts/ChartData.cs
Source/Extensions/Blazorise.Charts/ChartOptions.cs

To make it possible to draw the YAxis on left or right.
And to support multi scale charts (one chart goes from 30 to 90, the other from 0 to 10000)

Updates to ChartJS

---

Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Layouts/MainLayout.razor.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise/Components/Bar/BarToggler.razor.cs

resolves #2648 Fix closing of Bar from the separate BarToggler

Fix closing of Bar from the separate BarToggler

---

Source/Extensions/Blazorise.DataGrid/DataGridDateColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor
Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCellEditValidation.razor

resolves #2654 DataGridDateColumn contains time (minimum to seconds)

Add InputMode on DateGridDateColumn

---

Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js

show dataset label in tooltip title on pie/doughnut charts

---

Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js

fixes #2663 Default chart configuration

Default label callbacks for pie and doughnut chart

---

Source/Blazorise/Styles/_layout.scss
Source/Blazorise/wwwroot/blazorise.css

fixes #2661 Checkbox appears above other components

Fix fixed topbar z-index

---

Demos/Blazorise.Demo/Pages/Tests/IconsPage.razor

Just added a tooltip that shows a real name of the icon if hovered over.

Show a real name of the icon inside tooltip

---

Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Styles/_utilities.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css

fixes #2706 [Bulma 0.9.4.1] The class .is-rounded is wrongly set

Fix Bulma border radius utility

---

Source/Blazorise/Components/Tooltip/Tooltip.razor.cs

fixes #2709 Tooltip doesn't display when Inline is true

Fix Tooltip inline mode

---

Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js

fixes #2702 Modal dialog moves content

Calculate modal padding based on scrollbar size

---

Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.js
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js
Source/Blazorise.Material/wwwroot/blazorise.material.js
Source/Blazorise/wwwroot/blazorise.js

fixes #2678 tootlip js exception in 0.9.4

Add nullcheck for Tooltip element

---

Source/Blazorise/Components/Tooltip/Tooltip.razor.cs
Source/Blazorise/wwwroot/blazorise.js

fixes #2712 Unable to change TooltipOptions.MaxWidth in Blazorise theme

Assign Tooltip MaxWidth

---

Demos/Blazorise.Demo/Pages/Tests/ServicesPage.razor
Source/Blazorise/Models/NotificationOptions.cs
Source/Extensions/Blazorise.Components/NotificationAlert.razor
Source/Extensions/Blazorise.Components/NotificationAlert.razor.cs
Source/Extensions/Blazorise.Snackbar/Constants.cs
Source/Extensions/Blazorise.Snackbar/Snackbar.razor.cs
Source/Extensions/Blazorise.Snackbar/SnackbarOptions.cs
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs
docs/_docs/services/notificationservice.md

NotificationAlert component lacks an ability to set custom interval for a toast. So, added a parameter to the component and a property to NotificationOptions (to allow individual settings for notifications). Also updated documentation.

Added intervals configuration for NotificationAlert component.

---

Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js

Optimize Chart onclick and onhover events

---

Source/Blazorise/Resources/Localization/Carousel/sk.json
Source/Blazorise/Resources/Localization/FileEdit/sk.json
Source/Extensions/Blazorise.DataGrid/Resources/Localization/DataGrid/sk.json

Slovak language resources contribution.

Add Slovak language resources

---

Demos/Blazorise.Demo/App.razor
Source/Blazorise.AntDesign/Bar.razor
Source/Blazorise/Components/Bar/Bar.razor
Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/ThemeProvider/ThemeProvider.razor
Source/Blazorise/Components/ThemeProvider/ThemeProvider.razor.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js

Dynamically calculate HorizontalBarHeight if theme settings are undefined

---

Source/Blazorise/Resources/Localization/Carousel/sk.json
Source/Extensions/Blazorise.DataGrid/Resources/Localization/DataGrid/sk.json

I had been little bit too fast with previous pull request and I have been notified that there are some mistakes/inaccuracies in my translation. This PR is fixing it.
Sorry for any inconveniences.

Slovak localization corrections

---

Demos/Blazorise.Demo/Components/SideMenu.razor
Demos/Blazorise.Demo/Components/TopMenu.razor
Demos/Blazorise.Demo/Layouts/MainLayout.razor
Demos/Blazorise.Demo/Layouts/MainLayout.razor.cs
Source/Blazorise/Styles/_layout.scss
Source/Blazorise/wwwroot/blazorise.css

fixes #2747 Sider layout with header on top does not render properly

Fix sider layout when top header is fixed

---

Source/Extensions/Blazorise.DataGrid/Utils/RecursiveObjectActivator.cs
Tests/Blazorise.Benchmark/DataGrid/ReflectionBenchmark.cs
Tests/Blazorise.Tests/DataGrid/Utils/RecursiveObjectActivatorTests.cs

Follow up on PR #2756 & Issue #2758
Client now informed that the new activator will run out of memory due to cyclic object traversal.
Fixed to check for cyclic object traversal between previous types that are the same in the current object path traversal.
I called it internally as Circular Reference, it is not exactly circular reference, as the new object instances are always new references, but we do need to check for this type of cyclic traversal.
I tried to make it as simple as possible. We can review this more carefully in the future if any issue comes up.
We did take a hit for these cases as expected.
New test updated with client's reported sample code:
```
@page "/"
<DataGrid TItem="MarketDataModel"
Data="@BpsDataWithMarketData" Class="responsive-table table" ShowCaptions="true" …
```

RecursiveObjectActivator: Cyclic Object Traversal Fix

---

Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Layout/LayoutContent.razor
Source/Blazorise/Components/Layout/LayoutFooter.razor
Source/Blazorise/Components/Layout/LayoutHeader.razor
Source/Blazorise/Components/Layout/LayoutSider.razor
Source/Blazorise/Components/Layout/LayoutSiderContent.razor

fixes #2754 Problem with Layout After Blazorise Update

Calculate horizontal Bar height only for LayoutHeader

---

Demos/Blazorise.Demo.Material/wwwroot/index.html
Demos/Blazorise.Demo/Pages/Dashboard.razor
Demos/Blazorise.Demo/Pages/Tests/ButtonsPage.razor
Source/Blazorise/Components/Dropdown/DropdownToggle.razor

fixes #2769 Dropdown toggled-event stops working the second time you open the dropdown

Fix dropdown toggle

---

Demos/Blazorise.Demo/Components/FooterMenu.razor
Demos/Blazorise.Demo/Layouts/MainLayout.razor
Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Layout/LayoutFooter.razor
Source/Blazorise/Components/Layout/LayoutFooter.razor.cs
Source/Blazorise/Components/Layout/LayoutHeader.razor
Source/Blazorise/Components/Layout/LayoutHeader.razor.cs
Source/Blazorise/Styles/_bar.scss
Source/Blazorise/Styles/_layout.scss
Source/Blazorise/Themes/Models/ThemeBarOptions.cs
Source/Blazorise/Themes/Models/ThemeVariables.cs
Source/Blazorise/wwwroot/blazorise.css
Source/Blazorise/wwwroot/blazorise.js

Fix Bar height

---

Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js

fixes #2779 Modal Error - Cannot read property 'style' of null at Object.resetAdjustments

Add null check for modal adjustments

---

Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js

fixes #2702 Modal dialog moves content

Adjust Bootstrap modal and body paddings

---

Source/Blazorise.Bootstrap/NumericEdit.razor
Source/Blazorise.Bootstrap/NumericEdit.razor.cs

fixes #2784 NumericEdit ValidationError doesn´t work

Fix NumericEdit validations message for Bootstrap provider

---

docs/_docs/start.md

I assumed you meant 3.1 here, not 3.2 which is not a thing. Otherwise this should be 5.0 :)

Update start.md - Fixed typo

---

Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/wwwroot/blazorise.js

fixes #2841 TimePicker can not be disabled

Fix Disabled and ReadOnly states for DatePicker and TimePicker

---

Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css

fixes #2843 Invalid border-radius on components inside Addons

CSS rules for Dropdown inside of Addons

---

Source/Blazorise.Bootstrap/Styles/_form.scss
Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.css

resolves #2814 Slider ignores readonly setting

Don't allow to change readonly Slider

---

Source/Blazorise/Components/Carousel/Carousel.razor.cs
Source/Blazorise/Components/Carousel/CarouselSlide.razor.cs

Fixes #2832
Used code provided in the issue to test. Also tested with SelectedSlide parameter not being set, which would also cause the bug/error.

Fixed PreviouslySelectedSlide being null

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Add a callback for creating a new instance on editing to ensure nested object lifecycle

DataGrid: edit item creator

---

Documentation/Blazorise.Docs/Layouts/DocsLayout.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Grids/Code/ContainerBreakpointExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Grids/Examples/ContainerBreakpointExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Grids/GridPage.razor
Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise.AntDesign/Styles/_grid.scss
Source/Blazorise.AntDesign/wwwroot/blazorise.antdesign.css
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise/Components/Container/Container.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

resolves #2866 Container breakpoints
Introduces the new Breakpoint on the Container component.

Container breakpoints

---

Source/Blazorise/Resources/Localization/Carousel/pl.json
Source/Blazorise/Resources/Localization/FileEdit/pl.json
Source/Extensions/Blazorise.DataGrid/Resources/Localization/DataGrid/pl.json

* Add Polish language resources

Add Polish language resources

---

Demos/Blazorise.Demo/Pages/Tests/LayoutPage.razor
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise.Bulma/Tabs.razor
Source/Blazorise/Components/Tabs/Tabs.razor
Source/Blazorise/Components/Tabs/Tabs.razor.cs

resolves #2877 Add VerticalItemsColumnSize to Tabs

Vertical tabs size

---

Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor.cs

Datagrid : Command Column : Remove duplicated BuildCellStyle code.

---

Source/Blazorise.Bulma/Styles/_steps.scss
Source/Blazorise.Bulma/wwwroot/blazorise.bulma.css

Have .steps-content as independt rule on Bulma provider

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor

resolves #2681 Add Display utility to the DataGridColumn

Add  Display and HeaderDisplay for DataGridColumn

---

Source/Blazorise.AntDesign/BarIcon.razor
Source/Blazorise/Components/Bar/BarIcon.razor
Source/Blazorise/Components/Bar/BarIcon.razor.cs

resolves #2844 BarIcon is missing IconSize parameter

Add IconSize on BarIcon

---

Source/Blazorise/Base/BaseInputComponent.razor.cs
Source/Blazorise/Base/BaseTextInput.razor.cs
Source/Blazorise/Components/ColorEdit/ColorEdit.razor.cs
Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/Interfaces/IJSRunner.cs
Source/Blazorise/Interfaces/ISelectableComponent.cs
Source/Blazorise/JSRunner.cs
Source/Blazorise/wwwroot/blazorise.js

resolves #2757 Add Select method to input components
Also fixed the Focus for DatePicker and TimePicker.

Implement Select method on textual inputs

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataGridPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor

resolves #2883 Datagrid edit and save with enter key
Added parameter `SubmitFormOnEnter` on the DataGrid and made it default `true`.

DataGrid submit by enter key

---

Demos/Blazorise.Demo/Pages/Tests/CarouselPage.razor
Source/Blazorise/Components/Carousel/Carousel.razor.cs

Closes #2910
User noticed that disabling AutoPlay on Carousel was not working. This PR fixes it.
Used Blazorise's Demo CarouselPage to test. Changing the `AutoPlay` and `Interval` Parameters to test.

Carousel: Fixes disabling of AutoPlay not working

---

Source/Blazorise/wwwroot/blazorise.js

resolves #2929 TextEdit numeric mask not working

Fix NumericMaskValidator when used with TextEdit

---

Source/Blazorise.Material/MaterialThemeGenerator.cs

fixes #2913 Theme is not applied for Primary buttons in Modal

Fix material theme generator for button inside of modal

---

Source/Blazorise/Enums/TextRole.cs
Source/Blazorise/Extensions/EnumExtensions.cs

resolves #2905 TextRole add entry for "tel"

Add Telephone to TextRole

---

Source/Blazorise/wwwroot/blazorise.js

fixes #2967 Decimals attribute bug in NumericEdit

Don't truncate empty numeric values

---

Source/Extensions/Blazorise.Charts/wwwroot/blazorise.charts.js

fixes #2924 pie/doughnut default callback

Only set chart default callbacks if they are undefined

---

Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Source/Blazorise/Components/Button/Button.cs
Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs
Source/Blazorise/Components/FileEdit/FileEdit.razor.cs
Source/Blazorise/Components/Modal/Modal.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Components/TextEdit/TextEdit.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/Components/Tooltip/Tooltip.razor.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs

fixes #2944 Support for .NET 6 RC1 and JSInterop errors

Check for JSDisconnectedException in Net6

---

Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise/Enums/Background.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Themes/Models/ThemeBodyOptions.cs
Source/Blazorise/Themes/ThemeGenerator.cs

closes #3070 Can't get themes to work at all

Introduce Background.Body color

---

Source/Blazorise/Themes/Models/ThemeBarColorOptions.cs
Source/Blazorise/Themes/ThemeGenerator.cs

closes #2885 Theme bar gradient background

Add gradient for Bar background color

---

Source/Blazorise/Styles/_bar.scss
Source/Blazorise/wwwroot/blazorise.css

closes #2330 Incorrect default margin on sidebar/vertical bar BarMenu for desktop breakpoints

Fix Bar brand alignment

---

Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor

closes #3083 Issues with PopupClosing in DataGrid

Fix DataGrid popup structure

---

Source/Extensions/Blazorise.DataGrid/BaseDataGridComponent.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

Optimize disposal process of DataGrid components. With the new system, it is somewhat trickier to handle disposing of when inheritance is involved. With great power comes great responsibility 😅🤷‍♂️

Optimize disposing of DataGrid components

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Memos/MemoEditPage.razor
Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs
Source/Blazorise/wwwroot/memoEdit.js

closes #3096 Set MemoEdit height to show all text

AutoSize of MemoEdit component

---

Source/Extensions/Blazorise.Charts/ChartData.cs

closes #3116 Charts JsonNumberHandlingAttribute

JsonNumberHandling only for NET5

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Code/ITextLocalizerServiceExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Examples/ITextLocalizerServiceExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/LocalizationPage.razor

closes #3129 Update list of supported languages

Improve localization page

---

Source/Blazorise.AntDesign/wwwroot/tooltip.js
Source/Blazorise.Bootstrap/wwwroot/modal.js
Source/Blazorise.Bootstrap/wwwroot/tooltip.js
Source/Blazorise.Bootstrap5/wwwroot/modal.js
Source/Blazorise.Bootstrap5/wwwroot/tooltip.js
Source/Blazorise.Bulma/wwwroot/tooltip.js
Source/Blazorise.Material/wwwroot/modal.js
Source/Blazorise.Material/wwwroot/tooltip.js
Source/Extensions/Blazorise.Charts.Streaming/wwwroot/charts.streaming.js

closes #3122 JSInterop Exception using Tooltip in v0.9.5

JS relative paths

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/ModalPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor

Fix typos in docs

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/ModalPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Source/Blazorise/Base/BaseTextInput.razor.cs
Source/Blazorise/Themes/ThemeGenerator.cs
Source/Blazorise/wwwroot/table.js
Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs
Tests/Blazorise.Benchmark/Blazorise.Benchmark.csproj
Tests/Blazorise.Benchmark/Blazorise/ThemeBenchmark.cs
Tests/Blazorise.Benchmark/Program.cs
Tests/Blazorise.Tests/DataGrid/Utils/FunctionCompilerTests.cs
Tests/Blazorise.Tests/ThemeGeneratorTest.cs

Unused vars

---

Source/Blazorise/Components/Dropdown/DropdownItem.razor

DropdownItem : Remove StopPropagation and PreventDefault

---

Source/Blazorise/Components/Validation/Validation.razor.cs
Source/Blazorise/Utilities/IO/RemoteFileEntryStream.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

CancellationTokenSource Disposal

---

Source/Blazorise/Modules/BaseJSModule.cs

While testing before the release I have noticed that with Lazy the JS would get called even though disposal happened already.

Revert lazy module

---

Source/Blazorise/Modules/BaseJSModule.cs
Source/Blazorise/Modules/JSBreakpointModule.cs
Source/Blazorise/Modules/JSButtonModule.cs
Source/Blazorise/Modules/JSClosableModule.cs
Source/Blazorise/Modules/JSMemoEditModule.cs
Source/Blazorise/Modules/JSModalModule.cs
Source/Blazorise/Modules/JSNumericEditModule.cs
Source/Blazorise/Modules/JSTextEditModule.cs
Source/Blazorise/Modules/JSTooltipModule.cs

Fix JS Module deadlocks

---

Source/Blazorise.AntDesign/wwwroot/tooltip.js
Source/Blazorise.Bootstrap/wwwroot/tooltip.js
Source/Blazorise.Bootstrap5/wwwroot/tooltip.js
Source/Blazorise.Bulma/wwwroot/tooltip.js
Source/Blazorise.Material/wwwroot/tooltip.js
Source/Blazorise/Components/Tooltip/Tooltip.razor.cs

Autodetect tooltip inline mode

---

Source/Blazorise.AntDesign/TextEdit.razor
Source/Blazorise.Bootstrap/NumericEdit.razor
Source/Blazorise.Bootstrap5/NumericEdit.razor
Source/Blazorise.Bulma/NumericEdit.razor
Source/Blazorise.Bulma/TextEdit.razor
Source/Blazorise.Material/NumericEdit.razor
Source/Blazorise/Components/InputMask/InputMask.razor
Source/Blazorise/Components/NumericEdit/NumericEdit.razor
Source/Blazorise/Components/TextEdit/TextEdit.razor
Source/Extensions/Blazorise.Charts/BarChart.razor
Source/Extensions/Blazorise.Charts/Chart.razor
Source/Extensions/Blazorise.Charts/DoughnutChart.razor
Source/Extensions/Blazorise.Charts/HorizontalBarChart.razor
Source/Extensions/Blazorise.Charts/LineChart.razor
Source/Extensions/Blazorise.Charts/PieChart.razor
Source/Extensions/Blazorise.Charts/PolarAreaChart.razor
Source/Extensions/Blazorise.Charts/RadarChart.razor
Source/Extensions/Blazorise.RichTextEdit/BaseRichTextEditComponent.cs
Source/Extensions/Blazorise.RichTextEdit/JSRichTextEditModule.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor
Source/Extensions/Blazorise.RichTextEdit/wwwroot/richtextedit.js

Autogenerate RTE ElementId

---

Source/Extensions/Blazorise.Charts/BaseChart.cs

Fix Chart not being destroyed propertly

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor

DataGrid : Docs : Add missing doc descriptions

---

Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor

Fix Blazor.wasm multi select clickFromCheck tracking

---

Documentation/Blazorise.Docs/Pages/Docs/UsagePage.razor

Add Components Naming Convention Docs

---

Source/Blazorise/EventArguments/BLMouseEventArgs.cs
Source/Blazorise/Interfaces/Modules/IJSUtilitiesModule.cs
Source/Blazorise/Modules/JSUtilitiesModule.cs
Source/Blazorise/Utilities/EventArgsMapper.cs
Source/Blazorise/wwwroot/utilities.js
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

DataGrid : MacOs Meta key as Ctrl Click

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

DataGrid: Expose DisplayData & FilteredData getters.

---

Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Add AsyncValidator to Autocomplete

---

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
Documentation/Blazorise.Docs/Pages/News/2022-02-01-release-notes-100.razor
Source/Blazorise/Components/Dropdown/DropdownMenu.razor
Source/Blazorise/Components/Dropdown/DropdownMenu.razor.cs
Source/Blazorise/wwwroot/closable.js
Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete CloseOnSelection feature

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Selects/SelectPage.razor

Add Select Enum Note

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Templates.razor

Closes #3306
There kinda was already a note. Reworded.

DataGrid : ButtonRow : Note : Save / Cancel Should be configured in DataGridCommandColumn

---

Source/Extensions/Blazorise.Markdown/wwwroot/markdown.js

Properly destroy markdown instance

---

Source/Extensions/Blazorise.Charts/Options/ChartAxis.cs
Source/Extensions/Blazorise.Charts/Options/ChartAxisTime.cs
Source/Extensions/Blazorise.Charts/Options/ChartAxisTimeDisplayFormat.cs

Support for Time Cartesian Axis

---

Source/Blazorise/wwwroot/button.js
Source/Blazorise/wwwroot/datePicker.js
Source/Blazorise/wwwroot/fileEdit.js
Source/Blazorise/wwwroot/inputMask.js
Source/Blazorise/wwwroot/tooltip.js
Source/Extensions/Blazorise.Charts.Streaming/wwwroot/charts.streaming.js

ES6 compatibility level

---

Source/Blazorise/Resources/Localization/ColorPicker/is.json
Source/Extensions/Blazorise.DataGrid/Resources/Localization/DataGrid/is.json

Fix Icelandic localization

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bootstrap5/BootstrapThemeGenerator.cs

Fix theming of card image top radius

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Times/TimeEditPage.razor
Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs

TimeEdit fixes

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Times/TimeEditPage.razor
Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs

Null Step on TimeEdit

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/BindingDataPage.razor

Virtualize NET5 Task Cancelled exception note

---

Demos/Blazorise.Demo/Pages/Tests/ValidationsPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/ValidationPage.razor
Source/Blazorise/Components/Validation/ValidationError.razor
Source/Blazorise/Components/Validation/ValidationError.razor.cs
Source/Blazorise/Components/Validation/ValidationSummary.razor
Source/Blazorise/Components/Validation/ValidationSummary.razor.cs

ValidationError improvements

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-02-01-release-notes-100.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Closes #3388
There already exists an `EditItemCreator` haha!
`ValidationItemCreator` does make sense to exist.

DataGrid : ValidationItemCreator

---

Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor

DataGrid : Fix Existing MultiSelectColumn with DataGridSelectionMode.Single and DataGridEditMode.Inline rendering an empty row cell
Closes #3414

DataGrid : Fix multi select inline edit mode bug

---

Blazorise.sln
Demos/Blazorise.Demo/Blazorise.Demo.csproj
Demos/Blazorise.Demo/Components/SideMenu.razor
Demos/Blazorise.Demo/Pages/Tests/QRCodePage.razor
Demos/Blazorise.Demo/_Imports.razor
Documentation/Blazorise.Docs/Blazorise.Docs.csproj
Documentation/Blazorise.Docs/Layouts/DocsLayout.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/Code/BasicQRCodeExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/Code/ImportQRCodeExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/Code/QRCodeNugetInstallExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/Examples/BasicQRCodeExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/Examples/ImportQRCodeExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/Examples/QRCodeNugetInstallExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/QRCodePage.razor
Documentation/Blazorise.Docs/Pages/News/2022-02-01-release-notes-100.razor
Documentation/Blazorise.Docs/_Imports.razor
Source/Extensions/Blazorise.QRCode/Blazorise.QRCode.csproj
Source/Extensions/Blazorise.QRCode/Enums/EccLevel.cs
Source/Extensions/Blazorise.QRCode/QRCode.cs
Source/Extensions/Blazorise.QRCode/_Imports.razor

QRCode component

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataGridPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-02-01-release-notes-100.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor

DataGrid Prevent Row Click

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Add Unmatched Attributes to DataGrid

---

Source/Blazorise.Bootstrap/NumericPicker.razor.cs
Source/Blazorise.Bootstrap5/NumericPicker.razor.cs

Fix Width for NumericPicker wrapper

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

MultiSelect : Prefer DisplayData over viewData

---

Source/Blazorise.AntDesign/Table.razor
Source/Blazorise.AntDesign/TableBody.razor
Source/Blazorise.AntDesign/TableHeader.razor
Source/Blazorise.AntDesign/TableRowHeader.razor
Source/Blazorise.Bulma/Table.razor
Source/Blazorise/Base/BaseDraggableComponent.cs
Source/Blazorise/Components/Table/Table.razor
Source/Blazorise/Components/Table/TableBody.razor
Source/Blazorise/Components/Table/TableFooter.razor
Source/Blazorise/Components/Table/TableHeader.razor
Source/Blazorise/Components/Table/TableHeaderCell.razor
Source/Blazorise/Components/Table/TableRow.razor
Source/Blazorise/Components/Table/TableRowCell.razor
Source/Blazorise/Components/Table/TableRowHeader.razor

Fix Draggable on table components

---

Source/Extensions/Blazorise.Video/wwwroot/video.js

Fix sourceUrl var naming for video

---

Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

Set default _DataGridRow Color to None

---

Demos/Blazorise.Demo/Components/DoingWorkComponent.razor
Demos/Blazorise.Demo/Pages/Tests/ModalsPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Modals/ModalPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-02-01-release-notes-100.razor
Source/Blazorise.Bootstrap/Modal.razor
Source/Blazorise.Bootstrap5/Modal.razor
Source/Blazorise/Components/Modal/Modal.razor
Source/Blazorise/Components/Modal/Modal.razor.cs
Source/Blazorise/Enums/ModalRenderMode.cs

Closes #3464
Missing docs, but this will be it.

Modal Render Mode

---

Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/Code/TooltipTriggerTargetExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/Examples/TooltipTriggerTargetExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/TooltipPage.razor
Source/Blazorise/Components/Tooltip/Tooltip.razor.cs
Source/Blazorise/wwwroot/tooltip.js

Tooltip target

---

Source/Blazorise/Components/Bar/Bar.razor.cs
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs
Source/Blazorise/Components/Modal/Modal.razor.cs
Source/Blazorise/Extensions/ModuleExtensions.cs
Source/Blazorise/Extensions/ObjectExtensions.cs
Source/Extensions/Blazorise.Charts/Data/ChartDataset.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Source/Extensions/Blazorise.Components/ListView.razor.cs

REMOVE NET6_0_OR_GREATER Flag

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bootstrap5/BootstrapThemeGenerator.cs
Source/Blazorise/Themes/Models/ThemeColorOptions.cs

Theme Color.Link support

---

Demos/Blazorise.Demo/Pages/Tests/ModalsPage.razor
Source/Blazorise/Components/MessageAlert/MessageAlert.razor.cs
Source/Blazorise/Models/MessageOptions.cs
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor

Consistent order and colors of modal buttons

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

DataGrid : Handle Delete Edge Case : SelectedRow being edited is deleted

---

Source/Blazorise/Enums/Target.cs

Target fix

---

Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs

Remove text-center from CardDeck classname

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Memos/MemoEditPage.razor
Source/Blazorise.Bulma/MemoEdit.razor
Source/Blazorise/Components/MemoEdit/MemoEdit.razor
Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs
Source/Blazorise/Components/TextEdit/TextEdit.razor.cs

MemoEdit pattern

---

Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

Add Multiple parameter to SelectList

---

Source/Blazorise/Components/TimePicker/TimePicker.razor.cs

Fix Min and Max format for TimePicker

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/NumericPickerPage.razor
Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs
Source/Blazorise/Enums/NumericMinMaxLimitsOverride.cs
Source/Blazorise/Extensions/EnumExtensions.cs
Source/Blazorise/wwwroot/numericPicker.js

Adds MinMaxLimitsOverride parameter to NumericPicker

NumericPicker MinMaxLimitsOverride parameter

---

Demos/Blazorise.Demo/Pages/Tests/ChartsPage.razor.cs
Source/Extensions/Blazorise.Charts/Options/ChartAxis.cs
Source/Extensions/Blazorise.Charts/Options/ChartScaleTitle.cs

Chart: Add missing Scale Title

---

Demos/Blazorise.Demo/Pages/Tests/PickersPage.razor
Source/Blazorise.Bootstrap/NumericPicker.razor
Source/Blazorise.Bootstrap5/NumericPicker.razor
Source/Blazorise.Bulma/NumericPicker.razor
Source/Blazorise.Material/NumericPicker.razor
Source/Blazorise/Base/BaseTextInput.razor.cs
Source/Blazorise/Components/NumericPicker/NumericPicker.razor
Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs
Source/Blazorise/wwwroot/numericPicker.js

fixes #3529
fixes #3531
fixes #3547
Fixes NumericPicker value by moving all the editing to the autoNumeric and making the synchronization between C# and JSInterop.
---
Code to test various behaviors along with the validation:
```cshtml
<Card Margin="Margin.Is4.FromTop">
<CardHeader>
<CardTitle>Numeric Picker</CardTitle>
</CardHeader>
<CardBody>
<Validation Validator="@ValidateNumber">
<Field Horizontal>
<FieldLabel ColumnSize="ColumnSize.IsFull.OnTablet.Is3.OnDesktop">Bind with Immediate enabled</FieldLabel>
<FieldBody ColumnSize="ColumnSize.IsFull.OnTablet.Is9.OnDesktop">
<Addons>
<Addon AddonType="AddonType.Body">
<NumericPicker @bind-Value="@num1" Immediate="true" />
</Addon>
<Addon AddonType="AddonType.End">
<Button Color="Color.Primary" Clicked="@(()=>num1=5.1m)">Set</Button> …
```

NumericPicker: Fix value synchronization

---

Source/Extensions/Blazorise.Charts/ChartModel.cs
Source/Extensions/Blazorise.Charts/wwwroot/charts.js

Chart: fix click event and model parsing

---

Source/Blazorise/Modules/JSTooltipModule.cs

Tooltip: Fix tooltip content not being changed

---

Source/Blazorise/Components/Droppable/DropZone.razor.cs
Source/Blazorise/wwwroot/dragDrop.js

DragDrop: missing destroy method

---

Source/Blazorise.Bootstrap5/BootstrapThemeGenerator.cs

Range: fix theming colors for BS5

---

Source/Blazorise/wwwroot/numericPicker.js

NumericPicker: fix warning for caretPositionOnFocus

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataGridPage.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor

DataGrid: show readonly Check when DataGridCheckColumn

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Code/InlineDatePickerExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/DatePickerPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Examples/InlineDatePickerExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Times/Code/InlineTimePickerExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Times/Examples/InlineTimePickerExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Times/TimePickerPage.razor
Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/wwwroot/datePicker.js
Source/Blazorise/wwwroot/timePicker.js

DatePicker and TimePicker: Inline mode

---

Source/Blazorise/Components/MessageAlert/MessageAlert.razor
Source/Blazorise/Components/MessageAlert/MessageAlert.razor.cs
Source/Blazorise/Models/MessageOptions.cs

MessageService: Size option

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Progresses/Code/MultipleProgressHideValueExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Progresses/Examples/MultipleProgressHideValueExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Progresses/ProgressPage.razor
Source/Blazorise.Bulma/ProgressBar.razor
Source/Blazorise/Components/Progress/Progress.razor.cs
Source/Blazorise/Components/Progress/ProgressBar.razor
Source/Blazorise/Components/Progress/ProgressBar.razor.cs

Progress: add ShowValue parameter

---

Build/Blazorise.props
Documentation/Blazorise.Docs/Components/Footer.razor
Source/Extensions/Blazorise.Animate/Blazorise.Animate.csproj
Source/Extensions/Blazorise.QRCode/Blazorise.QRCode.csproj
Source/Extensions/Blazorise.RichTextEdit/Blazorise.RichTextEdit.csproj
Source/Extensions/Blazorise.TreeView/Blazorise.TreeView.csproj

NuGet Package set Company as Author

---

Source/Blazorise/Components/Modal/Modal.razor.cs

Modal Visibility Handling Pipeline : Invoke VisibleChanged sooner

---

Source/Blazorise/wwwroot/numericPicker.js

NumericPicker: update options in batch

---

Source/Extensions/Blazorise.Charts/Options/ChartAxis.cs

Chart: Linear Axis specific options

---

Source/Blazorise/wwwroot/numericPicker.js

NumericPicker: set emptyInputBehavior to allow null

---

.github/workflows/label-actions.yml

Create label-actions.yml - Workflow

---

.github/label-actions.yml

Create label-actions.yml - Configuration

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Closes #3627 
**Code used to test:**
```
<div>
<Autocomplete TItem="Person"
Data="@_people"
TextField="@((item) => item.FirstName)"
ValueField="@((item) => item.FirstName)"
Placeholder="Select Person"
SelectedValue="@selectedValue"
SelectedValueChanged="(x => OnPersonSelectedChanged(x))"
FreeTyping
Filter="AutocompleteFilter.Contains">
<NotFoundContent> Not found </NotFoundContent>
@foreach (var eventItem in _events)
{
<CardDeck>
<Card Style="background-color:lightgray" Margin="Margin.Is3.FromBottom">
<Div Margin="Margin.Is3">
<Autocomplete TItem="Person"
Data="@_people"
TextField="@((item) => item.FirstName)"
ValueField="@((item) => item.FirstName)"
Placeholder="Select Person"
SelectedValue="@eventItem.PersonItem.FirstName" …
```

Autocomplete : Add await InvokeAsync( StateHasChanged ); on SelectedText syncronization with SelectedValue

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Code/NumericPickerIntegerExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Examples/NumericPickerIntegerExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/NumericPickerPage.razor
Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs
Source/Blazorise/Utilities/TypeHelper.cs

closes #3650
**Usage**
```
<NumericPicker TValue="int" />
<NumericPicker TValue="decimal" />
```

NumericPicker: only allow decimal if the TValue is not integer

---

Source/Extensions/Blazorise.Charts/ChartModel.cs

Chart: add missing DatasetLabel on models

---

Source/Blazorise/Base/BaseTextInput.razor.cs

Fix TextEdit color classname being set for null value

---

Source/Blazorise/wwwroot/numericPicker.js

NumericPicker: Prevent mouse wheel to change value

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/Code/IconGlobalSettingsExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/Examples/IconGlobalSettingsExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/IconsPage.razor
Source/Blazorise/BlazoriseOptions.cs
Source/Blazorise/Components/Icon/Icon.razor
Source/Blazorise/Components/Icon/Icon.razor.cs
Source/Extensions/Blazorise.Icons.Material/Icon.razor

Global icon options

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs

Check: fix theming for disabled state

---

Source/Blazorise.Material/Config.cs
Source/Blazorise.Material/MaterialBehaviourProvider.cs

Material: add missing BehaviourProvider

---

Demos/Blazorise.Demo.AntDesign/wwwroot/index.html
Demos/Blazorise.Demo.Bootstrap.Server/Pages/_Host.cshtml
Demos/Blazorise.Demo.Bootstrap/wwwroot/index.html
Demos/Blazorise.Demo.Bootstrap5/wwwroot/index.html
Demos/Blazorise.Demo.Bulma/wwwroot/index.html
Demos/Blazorise.Demo.Material/wwwroot/index.html
Documentation/Blazorise.Docs.Server/Pages/_Host.cshtml
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/Code/ChartResourcesExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/Examples/ChartResourcesExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartTrendline/Code/ChartTrendlineResourcesExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartTrendline/Examples/ChartTrendlineResourcesExample.snippet
Documentation/Blazorise.Docs/Pages/News/2022-03-01-release-notes-100.razor
Source/Extensions/Blazorise.Charts/Data/BarChartDataset.cs
Source/Extensions/Blazorise.Charts/Data/LineChartDataset.cs
Source/Extensions/Blazorise.Charts/Data/ScatterChartDataset.cs

Chart: fix stacked datasets

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Code/NumericPickerMouseWheelExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Examples/NumericPickerMouseWheelExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/NumericPickerPage.razor
Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs
Source/Blazorise/Enums/NumericWheelOn.cs
Source/Blazorise/Extensions/EnumExtensions.cs
Source/Blazorise/wwwroot/numericPicker.js

NumericPicker: control the behavior of mouse wheel

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Markdown/MarkdownPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/QRCode/QRCodePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/RichTextEdit/RichTextEditPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Sidebar/SidebarPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Snackbar/SnackbarPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/SpinKit/SpinKitPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/TreeView/TreeViewPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Video/VideoPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Guides/AntDesign/AntDesignGuidePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Guides/Bootstrap/BootstrapGuidePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Guides/Bootstrap5/Bootstrap5GuidePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Guides/Bulma/BulmaGuidePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Guides/Material/MaterialGuidePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/Notifications/NotificationPage.razor
Documentation/Blazorise.Docs/Pages/Docs/StartPage.razor

Docs: fix import using notes

---

Source/Extensions/Blazorise.Charts/Options/Specifics/PieChartOptions.cs
Source/Extensions/Blazorise.Charts/Options/Specifics/PolarAreaChartOptions.cs

Remove default pie-chart option values

---

Source/Extensions/Blazorise.TreeView/TreeView.razor

TreeView: pass the parameters to the _TreeViewNode

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor

Docs: add note for using complex-data in charts

---

Source/Blazorise/wwwroot/memoEdit.js

MemoEdit: fix autosizing for first render

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete : Set filter to dirty after removing an item when multiple is set

---

Source/Blazorise/Components/FileEdit/FileEdit.razor.cs
Source/Blazorise/Utilities/IO/FileEntry.cs
Source/Blazorise/Utilities/IO/IFileEntry.cs
Source/Blazorise/Utilities/IO/IFileEntryOwner.cs
Source/Extensions/Blazorise.Markdown/Markdown.razor.cs

FileEdit : Add Cancelation Token to WriteToStreamAsync

---

Source/Extensions/Blazorise.DataGrid/Utils/RecursiveObjectActivator.cs
Tests/Blazorise.Tests/DataGrid/Utils/RecursiveObjectActivatorTests.cs

RecursiveObjectActivator | Make sure to only try to instantiate writable properties 

---

Source/Blazorise/Components/Dropdown/Dropdown.razor.cs
Source/Blazorise/Components/Dropdown/DropdownToggle.razor.cs

Fix SplitDropdown Not Closing On Button Click

---

Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Closes #3799 
@paulosdfigueiredo if you want/have the time to test it, we appreciate it.

Autocomplete : Make sure to refresh on SyncMultipleValuesAndTexts 

---

Source/Blazorise/Components/Table/TableRowHeader.razor
Source/Blazorise/Components/Table/TableRowHeader.razor.cs

TableRowHeader: add ColumnSpan/RowSpan Properties

---

Demos/Blazorise.Demo/App.razor
Documentation/Blazorise.Docs/App.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Code/MessageServiceUsageExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/Examples/MessageServiceUsageExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/Messages/MessagePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/Notifications/Code/NotificationServiceUsageExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Services/Notifications/Examples/NotificationServiceUsageExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/Notifications/NotificationPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/PageProgresses/Code/PageProgressServiceUsageExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Services/PageProgresses/Examples/PageProgressServiceUsageExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/PageProgresses/PageProgressPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-03-01-release-notes-110.razor
Source/Blazorise/Components/MessageAlert/MessageAlert.razor.cs
Source/Blazorise/Components/MessageAlert/MessageProvider.razor
Source/Blazorise/Components/MessageAlert/MessageProvider.razor.cs
Source/Blazorise/Components/Progress/PageProgressAlert.razor.cs
Source/Blazorise/Components/Progress/PageProgressProvider.razor
Source/Blazorise/Components/Progress/PageProgressProvider.razor.cs
Source/Extensions/Blazorise.Components/NotificationAlert.razor.cs
Source/Extensions/Blazorise.Components/NotificationProvider.razor
Source/Extensions/Blazorise.Components/NotificationProvider.razor.cs

Mark *Alert APIs as absolete and introduce new *Provider APIs

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/Code/DragDropReorderingExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/DragDropPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/Examples/DragDropReorderingExample.razor
Source/Blazorise/Components/Droppable/DraggableDroppedEventArgs.cs
Source/Blazorise/Components/Droppable/DraggableIndexChangedEventArgs.cs
Source/Blazorise/Components/Droppable/DraggableTransaction.cs
Source/Blazorise/Components/Droppable/DraggableTransactionEnded.cs
Source/Blazorise/Components/Droppable/DropContainer.razor.cs
Source/Blazorise/Components/Droppable/DropZone.razor
Source/Blazorise/Components/Droppable/DropZone.razor.cs
Source/Blazorise/Components/Droppable/_Draggable.razor
Source/Blazorise/Components/Droppable/_Draggable.razor.cs
Source/Blazorise/Styles/_dropzone.scss
Source/Blazorise/wwwroot/blazorise.css
Tests/BasicTestApp.Client/DropZoneReorderComponent.razor
Tests/Blazorise.Tests/Blazorise.Tests.csproj
Tests/Blazorise.Tests/Components/DropZoneTest.cs
Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs

DropZone: reorder items

---

Source/Blazorise/Components/Validation/Validation.razor.cs

Validation: show error if input is not defined

---

Source/Blazorise.Bootstrap/BootstrapThemeGenerator.cs
Source/Blazorise.Bootstrap5/Bootstrap5ThemeGenerator.cs

Fix border utility theme colors

---

Source/Blazorise/Components/InputMask/InputMask.razor
Source/Blazorise/Components/InputMask/InputMask.razor.cs

InputMask: fix binding for null value

---

Source/Blazorise/Components/DatePicker/DatePicker.razor.cs

Refactored SetParametersAsync based on NumericPicker. Check changes should only occur if picker is rendered and CurrentValueHandler should not be called to prevent unwanted event.
Closes #3798

DatePicker: Improve SetParametersAsync and prevent incorrect DateChanged or DatesChanged

---

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/Code/AutocompleteReadDataExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/Examples/AutocompleteReadDataExample.razor
Documentation/Blazorise.Docs/Pages/News/2021-10-21-release-notes-094-7.razor
Documentation/Blazorise.Docs/Pages/News/2022-03-01-release-notes-110.razor
Documentation/Blazorise.Docs/Pages/News/2022-04-11-release-notes-103.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Source/Extensions/Blazorise.Components/EventArguments/AutoCompleteReadDataEventArgs.cs

AutoComplete : ReadData

---

README.md

Add contributing notes to ReadMe

Contributing ReadME

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-03-01-release-notes-110.razor
Source/Extensions/Blazorise.DataGrid/Configuration/VirtualizeOptions.cs
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

DataGrid virtualize disable row move on edit option

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
Documentation/Blazorise.Docs/Pages/News/2022-03-01-release-notes-110.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

AutoComplete : ConfirmKey

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
Documentation/Blazorise.Docs/Pages/News/2022-03-01-release-notes-110.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

AutoComplete : AutoSelectFirstItem parameter

---

Source/Extensions/Blazorise.Components/ListView.razor

ListView : Render ChildContent at the bottom of the list if provided

---

Demos/Blazorise.Demo/Pages/Tests/ComponentsPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/SelectList/Code/SelectListExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/SelectList/Code/SelectListMultipleExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/SelectList/Examples/SelectListExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/SelectList/Examples/SelectListMultipleExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/SelectList/SelectListPage.razor
Source/Blazorise/Components/Select/Select.razor.cs
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

SelectList: add SelectedValues parameter and update docs

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

BugFix : Multiple + MinLen 0 | Show options after 1st selection

---

Source/Blazorise/Components/MessageAlert/MessageAlert.razor
Source/Blazorise/Components/MessageAlert/MessageProvider.razor

MessageProvider: center text

---

Source/Blazorise.AntDesign/AntDesignClassProvider.cs
Source/Blazorise/Components/Pagination/PaginationItem.razor
Source/Blazorise/Components/Pagination/PaginationItem.razor.cs

PaginationItem: fix disabled state

---

Source/Extensions/Blazorise.Charts/wwwroot/charts.js

Chart: fix invalid dotnetAdapter variable name

---

Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/DragDropPage.razor

This reverts commit 9b04a71203999ead5ecfc71932bcf351b951d10b.

Revert "Docs: Removed redundant property (#3999)"

---

Source/Blazorise/Components/Droppable/DraggableDroppedEventArgs.cs
Source/Blazorise/Components/Droppable/DropContainer.razor.cs
Tests/Blazorise.Tests/Components/DropZoneTest.cs

Added source drop zone name to dropped event args

---

Source/Blazorise.AntDesign/Config.cs
Source/Blazorise.AntDesign/Modules/AntDesignJSFileEditModule.cs
Source/Blazorise.AntDesign/wwwroot/fileEdit.js

FileEdit : AntDesign : Missing Open JS dependency

---

Documentation/Blazorise.Docs/Layouts/DocsLayout.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-09-01-release-notes-110.razor
Source/Extensions/Blazorise.DataGrid/Contexts/PaginationContext.cs

DataGrid: increase default PageSize to 10

---

Source/Blazorise/Components/Jumbotron/JumbotronTitle.razor
Source/Blazorise/Components/Jumbotron/JumbotronTitle.razor.cs

Jumbrotron: dynamically render the heading element

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/SelectList/SelectListPage.razor
Source/Extensions/Blazorise.Components/SelectList.razor
Source/Extensions/Blazorise.Components/SelectList.razor.cs

Hello, this PR closes https://github.com/Megabit/Blazorise/issues/4044.

Added DisabledField parameter to SelectList component

---

Demos/Blazorise.Demo/Pages/Tests/StepsPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Steps/Code/StepNavigationAllowedExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Steps/Examples/StepNavigationAllowedExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Steps/StepPage.razor
Documentation/Blazorise.Docs/Pages/News/2022-09-01-release-notes-110.razor
Source/Blazorise/Components/Steps/Step.razor.cs
Source/Blazorise/Components/Steps/StepNavigationContext.cs
Source/Blazorise/Components/Steps/Steps.razor.cs

Closes https://github.com/Megabit/Blazorise/issues/2624

Steps: added NextStep, PreviousStep methods

---

Source/Extensions/Blazorise.Charts/ChartColor.cs

Add ChartColor ToString

---

Source/Blazorise/Localization/TextLocalizer.cs

Fix GetLocalizationResourceNames retrieval

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/TooltipPage.razor
Source/Blazorise/Components/Tooltip/Tooltip.razor.cs
Source/Blazorise/wwwroot/tooltip.js

Tooltip: add AppendTo and ZIndex

---

Source/Blazorise/Components/Button/CloseButton.razor.cs

CloseButton: Disabled state not working

---

Tests/BasicTestApp.Client/AutocompleteMultipleReadDataComponent.razor
Tests/BasicTestApp.Client/AutocompleteReadDataComponent.razor

Tests : Investigate intermitent error on tests (v1.1)

---

Source/Blazorise/Components/FocusTrap/FocusTrap.razor
Source/Blazorise/Components/FocusTrap/FocusTrap.razor.cs

FocusTrap: Fix focus loss when holding tab key

---

Source/Blazorise/ComponentDisposer.cs

Closes #4137
(Can you first try on your demos app before releasing)

Fix component disposer on wasm

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Tests/BasicTestApp.Client/AutocompleteComponent.razor
Tests/BasicTestApp.Client/AutocompleteMultipleComponent.razor
Tests/BasicTestApp.Client/AutocompleteMultipleReadDataComponent.razor
Tests/BasicTestApp.Client/AutocompleteReadDataComponent.razor
Tests/Blazorise.Tests/Components/AutoCompleteComponentTest.cs
Tests/Blazorise.Tests/Components/AutoCompleteMultipleComponentTest.cs
Tests/Blazorise.Tests/Components/AutocompleteMultipleReadDataComponentTest.cs
Tests/Blazorise.Tests/Components/AutocompleteReadDataComponentTest.cs
Tests/Blazorise.Tests/Components/Base/AutocompleteBaseComponentTest.cs
Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs

Autocomplete: revert breaking change API

---

Documentation/Blazorise.Docs/Pages/Docs/UsagePage.razor

Docs : Usage : Add note about bUnit

---

Source/Blazorise/ComponentDisposer.cs

Component disposer : Active Flag to avoid breaking custom DI containers

---

Source/Extensions/Blazorise.Charts/wwwroot/charts.js

Closes https://support.blazorise.com/issues/52

Chart: fix update of aspectRatio

---

Source/Blazorise/wwwroot/datePicker.js

DatePicker: disableMobile mode

---

Source/Blazorise/wwwroot/filePicker.js

Remove getOnlyTrueFiles check from filePicker.js

---

Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Resources/Localization/DatePicker/cs.json
Source/Blazorise/Resources/Localization/DatePicker/de.json
Source/Blazorise/Resources/Localization/DatePicker/en.json
Source/Blazorise/Resources/Localization/DatePicker/es.json
Source/Blazorise/Resources/Localization/DatePicker/fr.json
Source/Blazorise/Resources/Localization/DatePicker/hr.json
Source/Blazorise/Resources/Localization/DatePicker/is.json
Source/Blazorise/Resources/Localization/DatePicker/it.json
Source/Blazorise/Resources/Localization/DatePicker/nl.json
Source/Blazorise/Resources/Localization/DatePicker/pl.json
Source/Blazorise/Resources/Localization/DatePicker/pt.json
Source/Blazorise/Resources/Localization/DatePicker/ru.json
Source/Blazorise/Resources/Localization/DatePicker/sk.json
Source/Blazorise/Resources/Localization/DatePicker/tr.json
Source/Blazorise/Resources/Localization/DatePicker/zh.json
Source/Blazorise/wwwroot/datePicker.js

DatePicker: add RangeSeparator

---

Demos/Blazorise.Demo/Pages/Tests/LiveChartsPage.razor
Demos/Blazorise.Demo/Pages/Tests/LiveChartsPage.razor.cs
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartStreaming/ChartStreamingPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartStreaming/Code/ChartStreamingPauseExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartStreaming/Examples/ChartStreamingPauseExample.razor
Source/Extensions/Blazorise.Charts.Streaming/ChartStreaming.razor.cs
Source/Extensions/Blazorise.Charts.Streaming/ChartStreamingOptions.cs
Source/Extensions/Blazorise.Charts.Streaming/JSChartStreamingModule.cs
Source/Extensions/Blazorise.Charts.Streaming/wwwroot/charts.streaming.js

Closes #4258
Closes #4260
Closes #4242

Chart streaming improvements

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/PagerPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor.cs

Datagrid pagination fixes

---

Source/Blazorise/wwwroot/datePicker.js

DatePicker: call destroy when disposed

---

Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs

Add Disabled parameter to BarDropdownToggle

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Links/LinkPage.razor
Source/Blazorise/Components/Link/Link.razor.cs
Source/Blazorise/Enums/Match.cs

Link: Add CustomMatch parameter

---

Source/Extensions/Blazorise.RichTextEdit/BaseRichTextEditComponent.cs
Source/Extensions/Blazorise.RichTextEdit/RichTextEdit.razor.cs

RichTextEdit: wait for the first render to execute methods

---

Source/Blazorise/Components/Droppable/DropContainer.razor.cs

DropContainer: null checks for transaction

---

Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs

NumericPicker: wait for the first render to execute methods

---

Source/Blazorise.AntDesign/DropdownItem.razor

Closes  #4212
Applied same click handling as in default DropdownItem

Ant Design, same DropdownItem Click Handling

---

Source/Blazorise.AntDesign/BarDropdownToggle.razor
Source/Blazorise.Bootstrap5/BarDropdownToggle.razor
Source/Blazorise.Bulma/BarDropdownToggle.razor
Source/Blazorise.Tailwind/BarDropdownToggle.razor
Source/Blazorise/Components/Bar/BarDropdownToggle.razor
Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs

BarDropdownToggle show focus when navigating with tab key

---

Source/Blazorise/Components/Check/Check.razor.cs
Source/Blazorise/Components/ColorEdit/ColorEdit.razor.cs
Source/Blazorise/Components/DateEdit/DateEdit.razor.cs
Source/Blazorise/Components/InputMask/InputMask.razor.cs
Source/Blazorise/Components/MemoEdit/MemoEdit.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Components/Radio/Radio.razor.cs
Source/Blazorise/Components/Select/Select.razor.cs
Source/Blazorise/Components/Slider/Slider.razor.cs
Source/Blazorise/Components/Switch/Switch.razor.cs
Source/Blazorise/Components/TextEdit/TextEdit.razor.cs
Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs

Closes #4326
**Test code**
```razor
<Row>
<Column>
<Card Margin="Margin.Is4.OnY">
<CardBody>
<Validation Validator="IsText">
<TextEdit Placeholder="Enter name" @bind-Text="name">
<Feedback>
<ValidationNone>Please enter the name.</ValidationNone>
<ValidationSuccess>Name is good.</ValidationSuccess>
<ValidationError>Enter valid name!</ValidationError>
</Feedback>
</TextEdit>
</Validation>
<Button Clicked="UpdateName" Color="Color.Primary">Change name</Button>
</CardBody>
</Card>
</Column>
<Column>
<Card Margin="Margin.Is4.OnY">
<CardBody>
<Validation Validator="IsNumber">
<NumericEdit Placeholder="Enter number" @bind-Value="num1">
<Feedback>
<ValidationNone>Please enter number.</ValidationNone>
<ValidationSuccess>number is good.</ValidationSuccess>
<ValidationError>Enter valid …
```

Validate input fields when value is updated through parameter

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Files/FileEditPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Files/FilePickerPage.razor
Source/Blazorise/Components/FilePicker/FilePicker.razor
Source/Blazorise/Components/FilePicker/FilePicker.razor.cs

FilePicker: add Disable and ReadOnly parameters

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataGridPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridModal.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor

DataGrid: add EditFieldColumnSize

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/Code/AutocompleteHighlightExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/Examples/AutocompleteHighlightExample.razor
Documentation/Blazorise.Docs/Pages/News/2023-01-15-release-notes-120.razor
Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs
Source/Blazorise.Bulma/BulmaClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Closes #3791
Closes #3727
Also fixed dropodown classnames.

Autocomplete: improvements

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/PagerPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/GettingStartedPage.razor
Documentation/Blazorise.Docs/Pages/News/2023-01-15-release-notes-120.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/PaginationTemplates.cs
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor.cs

DataGrid PageSelectorTemplate And PageSizesTemplate

---

Source/Blazorise/Resources/Localization/FilePicker/de.json

Fix german translation for file picker

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/DatePickerPage.razor
Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/wwwroot/datePicker.js

DatePicker: disable input on mobile devices

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/Code/ChartHorizontalBarExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/Examples/ChartHorizontalBarExample.razor

Docs: Horizontal Bar Chart example

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Revert DataGrid Dirty Filter Check

---

.github/dependabot.yml
Build/Blazorise.Client.props
Build/Blazorise.Demo.props
Build/Blazorise.Docs.props
Build/Blazorise.Server.RC.props
Build/Blazorise.Server.props
Build/Blazorise.props
Documentation/Blazorise.Docs/Blazorise.Docs.csproj
Shared/Blazorise.Shared/Blazorise.Shared.csproj
Source/SourceGenerators/Blazorise.Generator.Features/Blazorise.Generator.Features.csproj
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Server/BasicTestApp.Server.csproj
Tests/Blazorise.E2ETests/Blazorise.E2ETests.csproj

Reverts Megabit/Blazorise#4485

Revert "Add NuGet to dependabot configuration"

---

Source/Extensions/Blazorise.Icons.FontAwesome/FontAwesomeIcons.cs

Remove FontAwesome invalid icon

---

Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs

NumericEdit: checks Min and Max on blur

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete: trim text in free typing mode

---

Source/Blazorise/Components/Carousel/Carousel.razor.cs
Source/Blazorise/Components/Carousel/CarouselSlide.razor.cs

Closes #4553
Testing code : 
```
<Column>
<Card Margin="Margin.Is4.FromBottom">
<CardHeader>
<Button Clicked="RenderOther">Render Other </Button>
</CardHeader>
<CardBody>
<Carousel Autoplay AutoRepeat>
<Repeater Context="photo"
Items="_allPhotos">
<CarouselSlide @key="photo.PhotoId" Name="@photo.PhotoId">
<Image Display="Display.Block"
Source="@photo.PhotoLink"
Width="Width.Is100" />
</CarouselSlide>
</Repeater>
</Carousel>
</CardBody>
</Card>
</Column>
@code {
private List<Photo> _allPhotos = new() {
new() { PhotoId = "1", PhotoLink = "_content/Blazorise.Demo/img/slides/slide-01.jpg" } ,
new() { PhotoId = "2", PhotoLink = "_content/Blazorise.Demo/img/slides/slide-02.jpg" } ,
new() { PhotoId = "3", PhotoLink = "_content/Blazorise.Demo/img/slides/slide-03.jpg" },
};
private class Photo
{ …
```

Carousel RemoveSlide

---

Source/Blazorise/wwwroot/timePicker.js

TimePicker: properly destroy picker instance

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/CommonPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Code/GlobalLocalizerExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/Examples/GlobalLocalizerExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Helpers/Localization/LocalizationPage.razor

Docs: fix enums and global localization example

---

Source/Extensions/Blazorise.TreeView/Extensions/NodeStateExtensions.cs
Source/Extensions/Blazorise.TreeView/Internal/_TreeViewNode.razor.cs
Source/Extensions/Blazorise.TreeView/TreeView.razor.cs

TreeView: check SelectedNode against internal state value

---

Source/Blazorise/Components/TimeEdit/TimeEdit.razor.cs
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/Utilities/Parsers.cs

TimePicker: Fix TimeOnly value parser

---

Source/Blazorise/Themes/ThemeGenerator.cs

Support for 3 letter hex color in theme generator

---

Documentation/Blazorise.Docs/Pages/Docs/Specifications/AutocompletePage.razor

Simple change submitted through github UI

Autocomplete doc spec : Rename SelectedValueChanged to SelectedTextChanged

---

Source/Blazorise/Adapters/DatePickerAdapter.cs
Source/Blazorise/Components/DatePicker/DatePicker.razor
Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/Components/DatePicker/IDatePicker.cs
Source/Blazorise/Interfaces/Modules/IJSDatePickerModule.cs
Source/Blazorise/Modules/JSDatePickerModule.cs
Source/Blazorise/wwwroot/datePicker.js

DatePicker : Fix Events not Triggering

---

Source/Blazorise/Components/Bar/BarBrand.razor
Source/Blazorise/Components/Bar/BarToggler.razor.cs
Source/Blazorise/States/BarState.cs
Source/Blazorise/States/BarTogglerState.cs

Closes #4058
This was my solution to keep it synced. 
I didnt't really find the `Cropper` example applicable, but let me know if you have a better suggestion.

Synchronize mobile BarToggler with "main Toggler"

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Code/MultipleDatePickerExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Code/RangeDatePickerExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/DatePickerPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Examples/MultipleDatePickerExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Examples/RangeDatePickerExample.razor

DatePicker Docs : Add Missing Attributes

---

Source/Extensions/Blazorise.Charts.Trendline/ChartTrendlineData.cs

Make ChartTrendlineData Color nullable

---

Source/Blazorise/Components/Bar/BarDropdownToggle.razor.cs
Tests/BasicTestApp.Client/BarComponent.razor
Tests/BasicTestApp.Client/Index.razor
Tests/Blazorise.Tests/Components/BarComponentTest.cs
Tests/Blazorise.Tests/Components/BarTest.cs
Tests/Blazorise.Tests/Helpers/BlazoriseConfig.cs

Bar dropdown toggle not firing clicked

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Tests/Blazorise.Tests/Components/AutoCompleteComponentTest.cs
Tests/Blazorise.Tests/Components/Base/AutocompleteBaseComponentTest.cs

Autocomplete SelectedValue + SelectedText changed at the same time, sync fix

---

Demos/Blazorise.Demo.AntDesign/Program.cs
Demos/Blazorise.Demo.Bootstrap.Server/Startup.cs
Demos/Blazorise.Demo.Bootstrap.Server/appsettings.json
Demos/Blazorise.Demo.Bootstrap/Program.cs
Demos/Blazorise.Demo.Bootstrap5/Program.cs
Demos/Blazorise.Demo.Bulma/Program.cs
Demos/Blazorise.Demo.Material/Program.cs
Demos/Blazorise.Demo.Tailwind/Program.cs
Demos/Blazorise.Demo/Config.cs
Documentation/Blazorise.Docs.Server/Startup.cs
Documentation/Blazorise.Docs.Server/appsettings.json
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Guides/Licensing/Code/LicensingGuideAddKeyExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Guides/Licensing/Examples/LicensingGuideAddKeyExample.snippet
Source/Blazorise/BlazoriseOptions.cs
Source/Blazorise/Licensing/BlazoriseLicenseProvider.cs

Add ProductToken to BlazoriseOptions

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

DataGrid: Add AggregateRowStyling, and obsolete GroupRowStyling

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Tests/BasicTestApp.Client/Autocomplete_4634Component.razor
Tests/BasicTestApp.Client/Index.razor
Tests/Blazorise.E2E.Tests/Tests/Extensions/Autocomplete/Autocomplete_4634_Tests.cs

Autocomplete selected value set programatically refresh options

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs
Tests/BasicTestApp.Client/Autocomplete_4772Component.razor
Tests/Blazorise.E2E.Tests/Tests/Extensions/Autocomplete/Autocomplete_4772Tests.cs

Autocomplete min len0 fix data not reloading | After blur

---

Source/Extensions/Blazorise.TreeView/TreeView.razor.cs
Tests/BasicTestApp.Client/BasicTestApp.Client.csproj
Tests/BasicTestApp.Client/TreeViewComponent.razor
Tests/BasicTestApp.Client/wwwroot/index.html
Tests/Blazorise.Tests/Components/TreeViewComponentTest.cs
Tests/Blazorise.Tests/Extensions/TestExtensions.cs

Treeview | Fix Observable listener for actions other then Add | Reload

---

Source/Extensions/Blazorise.DataGrid/_DataGridCell.razor.cs

DataGrid: Use ValidationsHandlerType from ParentDataGrid

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Carousels/CarouselPage.razor

Docs: add best practices for Carousel component

---

Source/Blazorise/Base/BaseDraggableComponent.cs

Prevents the JS call on each Dispose() when the JSDragDropModule has not Init

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/TreeView/TreeViewPage.razor
Documentation/Blazorise.Docs/Pages/News/2023-06-01-release-notes-130.razor
Source/Extensions/Blazorise.TreeView/Internal/_TreeViewNode.razor.cs
Source/Extensions/Blazorise.TreeView/TreeView.razor.cs

Closes #4843
- Introduced Observable Collection for Children
- Introduced new TreeView.RemoveNode api
Testing code with both alternatives:
```
<TreeView @ref="treeViewRef"
TNode="NodeInfo"
Nodes="Nodes"
@bind-SelectedNode="selectedNode"
ExpandedNodes="@ExpandedNodes"
GetChildNodes="@(item => item.Children)"
HasChildNodes="@(item => HasChildren(item))"
ExpandedNodesChanged="@OnExpandedNodes">
<NodeContent>
<Icon Name="IconName.Folder" />
@context.Text
<Button Size="Size.ExtraSmall" Margin="Margin.Is1" Color="Color.Danger" Clicked="() => RemoveNode(context)">Rmv Api</Button>
<Button Size="Size.ExtraSmall" Color="Color.Danger" Clicked="() => RemoveNodeObservable(context)">Rmv Observable</Button>
<Button Size="Size.ExtraSmall" Color="Color.Warning" Clicked="() => …
```

TreeView | RemoveNode Api | Observable Children Reload

---

Source/Extensions/Blazorise.Charts/Options/ChartArcElements.cs
Source/Extensions/Blazorise.Charts/Options/ChartAxisScaleLabel.cs

Chart: fix nullable fields

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/DragDrops/DragDropPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Cropper/Code/CropperMessageSizeExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Cropper/CropperPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Cropper/Examples/CropperMessageSizeExample.snippet

Docs improvements

---

Source/Blazorise.Bootstrap/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap5/Bootstrap5ClassProvider.cs

Modal: fix duplicate modal size classnames

---

Demos/Blazorise.Demo/Pages/Tests/VideoPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Video/Code/VideoMultipleSourcesExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Video/Examples/VideoMultipleSourcesExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Video/VideoPage.razor
Documentation/Blazorise.Docs/Pages/News/2023-06-01-release-notes-130.razor
Source/Blazorise/Utilities/CamelCaseEnumJsonConverter.cs
Source/Extensions/Blazorise.Video/Video.razor
Source/Extensions/Blazorise.Video/Video.razor.cs
Source/Extensions/Blazorise.Video/VideoMedia.cs
Source/Extensions/Blazorise.Video/VideoSettingsType.cs
Source/Extensions/Blazorise.Video/VideoSource.cs
Source/Extensions/Blazorise.Video/wwwroot/video.js

https://github.com/Megabit/Blazorise/discussions/4881

Video quality options

---

Source/Blazorise/Components/Icon/Icon.razor.cs

Icon: fix order of options priority

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/DataGridApi.razor

Docs : DataGrid : Add Missing parameter Documentation

---

Source/Extensions/Blazorise.Cropper/CropperAdapter.cs

Cropper: fixed issues on JSInvokable in CropperAdapter

---

Source/Blazorise/Base/BaseTextInput.razor.cs
Source/Blazorise/wwwroot/datePicker.js
Source/Blazorise/wwwroot/utilities.js

DatePicker: fixed placeholder text

---

Source/Blazorise/Components/Validation/ValidationError.razor
Tests/BasicTestApp.Client/ValidateAnnotationsComponent.razor
Tests/BasicTestApp.Client/ValidateSelectComponent.razor
Tests/Blazorise.Tests/Components/ValidateAnnotationsComponentTest.cs

ValidationError: show content with higher priority

---

Source/Blazorise.Tailwind/TailwindClassProvider.cs

FieldLabel: fix required indicator for Tailwind

---

Source/Blazorise.AntDesign/Slider.razor
Source/Blazorise.Bootstrap/NumericPicker.razor
Source/Blazorise.Bootstrap5/NumericPicker.razor
Source/Blazorise.Bulma/NumericEdit.razor
Source/Blazorise.Bulma/NumericPicker.razor
Source/Blazorise.Material/NumericPicker.razor
Source/Blazorise/Base/BaseInputComponent.razor.cs
Source/Blazorise/Components/NumericEdit/NumericEdit.razor
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs
Source/Blazorise/Components/NumericPicker/NumericPicker.razor
Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs
Source/Blazorise/Components/Slider/Slider.razor
Source/Blazorise/Components/Slider/Slider.razor.cs
Source/Blazorise/Extensions/ObjectExtensions.cs

Fix conversion of component values to InvariantCulture

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Code/BasicNumericEditExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Code/NumericEditGenericExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Examples/BasicNumericEditExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/Examples/NumericEditGenericExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Numerics/NumericEditPage.razor

Docs: Improve NumericEdit examples and notes

---

Source/Blazorise.Bootstrap5/FileEdit.razor
Source/Blazorise/Components/Validation/ValidationRule.cs

FileEdit: fix validation feedback not showing up

---

Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/wwwroot/datePicker.js
Source/Blazorise/wwwroot/observer.js

Closes #5121
This picker makes it to observe for any changes on internal `altinput` and then to assign the validation classnames to the wrapper element.

DatePicker: Observe date picker input class names

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

**To reproduce:**
`DataGrid` with `ReadData`:
- Go to last page
- Change page size to allow more records per page
- Both PageSize and Page Changed events will trigger and internally it won't call `ReadData`.
**Problem**
- PageSizeChanged event triggers
- internal HandleReadData triggers
- IsLoading is set to true
- The task yields back control before calling `ReadData`
- PageChanged event triggers and cancels the current operation (CancellationToken)
- internal HandleReadData triggers
- IsLoading is true and jumps out
- The PageSizeChanged HandleReadData resumes and verifies the cancellation token that has been cancelled and jumps out
... 
with this, no `ReadData` was called and the data will not update.

Fix ReadData handling between PageSizeChanged and PageChanged

---

Source/Blazorise/Resources/Localization/MessageProvider/ru.json

MessageProvider: Change russian localization

---

Demos/Blazorise.Demo/Pages/Tests/SignaturePadPage.razor
Source/Extensions/Blazorise.SignaturePad/wwwroot/signaturepad.js

SignaturePad: fix scaling on smaller screens

---

Source/Blazorise/wwwroot/timePicker.js

TimePicker: removed null from placeholder

---

Source/Blazorise/wwwroot/datePicker.js

DatePicker: fix inputMask.js case-sensitive filename

---

Source/Extensions/Blazorise.TreeView/Internal/_TreeViewNode.razor.cs

`CollectionChanged` was accumulating handlers, these were not being disposed of.
Please merge this through 1.3 / 1.4.

TreeViewNode | Make sure to dispose of CollectionChanged event handlers

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete | SelectedTexts null check

---

Source/Blazorise/wwwroot/datePicker.js

DatePicker: use proper fallback for placeholder

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/NewFilesToBuild.txt
Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/Code/TooltipWithHtmlExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/Examples/TooltipWithHtmlExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Tooltips/TooltipPage.razor

Docs: add Tooltip HTML example

---

Documentation/Blazorise.Docs/NewFilesToBuild.txt
Source/Extensions/Blazorise.SignaturePad/wwwroot/signaturepad.js

SignaturePad: resize canvas on visibility changes

---

Source/Blazorise/Components/Carousel/Carousel.razor.cs

AnimationEnd | Null check SelectedSlide

---

Demos/Blazorise.Demo/Components/ThemeColorSelector.razor
Demos/Blazorise.Demo/Components/ThemeColorSelector.razor.cs
Demos/Blazorise.Demo/Pages/Tests/DataGrid/EditingRapidPage.razor
Source/Extensions/Blazorise.DataGrid/Utils/RecursiveObjectActivator.cs
Source/Extensions/Blazorise.Icons.FontAwesome/FontAwesomeIcons.cs
Source/Helpers/Blazorise.Tests.bUnit/Blazorise.Tests.bUnit.csproj

https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0050#workaround
Also fixed a few other warnings

Formatterservices is obsolete formatter based serialization is obsolete and should not be used

---

Source/Blazorise.AntDesign/Config.cs

Alert: register AntDesign component override

---

Source/Extensions/Blazorise.RichTextEdit/JSRichTextEditModule.cs

#5376 Fix snow theme css not loading

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/ColumnChooserPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Code/DataGridColumnChooserPositionExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/DataGridApi.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Examples/DataGridColumnChooserPositionExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Features/ColumnChooserPage.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor
Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor.cs

Allow column chooser button to be aligned horizontally

---

Source/Blazorise/Components/Validation/Validations.razor.cs

For #5386
- [ X] New feature (non-breaking change which adds functionality)
- [X ] The PR is submitted to the correct branch (`master` for dev, `rel-1.x` for maintenance).
- [ X] My code follows the code style of this project.

Validations: Make Public AllValidationsSuccessful and HasFailedValidations

---

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs

https://blazorise.com/support/issues/159

DataGridColumn: Fix Displayable updating

---

Source/Extensions/Blazorise.SignaturePad/wwwroot/signaturepad.js

SignaturePad: fix aspect ratio

---

Source/Blazorise/wwwroot/datePicker.js
Source/Blazorise/wwwroot/timePicker.js

DatePicker and TimePicker: override id on hidden input

---

Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs

```
<Button Clicked="@(() => displayable = !displayable)">Display</Button>
<DataGrid TItem="Employee"
Data="inMemoryData"
Responsive
ShowPager
ShowPageSizes>
<DataGridColumn TextAlignment="TextAlignment.Center" TItem="Employee" Field="@nameof( Employee.Id )" Caption="#" Width="60px" />
<DataGridColumn TItem="Employee" Displayable=displayable Field="@nameof( Employee.FirstName )" Caption="First Name">
</DataGridColumn>
<DataGridColumn TItem="Employee" Field="@nameof( Employee.LastName )" Caption="Last Name" />
<DataGridColumn TItem="Employee" Field="@nameof( Employee.Email )" Caption="Email" />
<DataGridColumn TItem="Employee" Field="@nameof( Employee.City )" Caption="City">
<CaptionTemplate>
<Icon Name="IconName.City" /> @context.Caption
</CaptionTemplate> …
```

DataGridColumn: Adjust Displayable to use SetDisplaying

---

Source/Blazorise/wwwroot/datePicker.js
Source/Blazorise/wwwroot/timePicker.js

DatePicker: fix the observer for hidden element

---

Source/Extensions/Blazorise.Video/VideoSource.cs
Source/Extensions/Blazorise.Video/VideoTrack.cs

Video: fix Tracks options mapping

---

Source/Blazorise.Tailwind/Components/Badge.razor
Source/Blazorise.Tailwind/Components/Badge.razor.cs

Badge: fix closing of modals when clicked on badge in Autocomplete

---

Source/Blazorise.Bootstrap5/Components/FileEdit.razor

FileEdit: show placeholder for BS5 input

---

Source/Blazorise.Bulma/Components/DateEdit.razor
Source/Blazorise.Bulma/Components/TimeEdit.razor
Source/Blazorise.FluentUI2/Components/DateEdit.razor
Source/Blazorise.FluentUI2/Components/TimeEdit.razor
Source/Blazorise/Components/DateEdit/DateEdit.razor
Source/Blazorise/Components/TimeEdit/TimeEdit.razor

https://blazorise.com/support/issues/198/timeedit-not-displaying-seconds

TimeEdit & DateEdit: fix the placement of step attribute

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Closes #insert_issue_number
- [x ] Bug fix (non-breaking change which fixes an issue)

Autocomplete: Respect validation mode

---

Source/Blazorise.Bootstrap5/Components/FileEdit.razor

FileEdit: fix default button text

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Video/VideoPage.razor
Source/Extensions/Blazorise.Charts/Options/ChartOptions.cs
Source/Extensions/Blazorise.Charts/Options/ChartParsing.cs
Source/Extensions/Blazorise.Charts/Options/ChartPlugins.cs
Source/Extensions/Blazorise.Charts/Options/ChartScales.cs

Docs: minor improvements

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Code/DatePickerDisabledDaysExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/DatePickerPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Dates/Examples/DatePickerDisabledDaysExample.razor
Documentation/Blazorise.Docs/Pages/News/2024-07-15-release-notes-160.razor
Source/Blazorise/Components/DatePicker/DatePicker.razor.cs
Source/Blazorise/wwwroot/datePicker.js

DatePicker: add DisabledDays parameter

---

Documentation/Blazorise.Docs/Layouts/DocsLayout.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/InputMasks/Code/InputMaskPlaceholderExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/InputMasks/Examples/InputMaskPlaceholderExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/InputMasks/InputMaskPage.razor
Documentation/Blazorise.Docs/Pages/News/2024-07-15-release-notes-160.razor
Source/Blazorise/Components/InputMask/InputMask.razor.cs
Source/Blazorise/wwwroot/inputMask.js

InputMask: add new MaskPlaceholder parameter

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Bar/BarPage.razor

Related to #5567
- [-] My code follows the code style of this project.
- [-] I've added relevant tests.

BarLink: Fix type of Match in the documentation

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Chart/ChartPage.razor
Source/Extensions/Blazorise.Charts/Options/ChartInteraction.cs
Source/Extensions/Blazorise.Charts/Options/ChartOptions.cs

Chart: fix the API of Interaction options

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/Snackbar/SnackbarPage.razor

Enhances documentation of SnackbarStack to describe how the Snackbar options can be used along with the Stack.

Docs: Update SnackbarStack to include details about how to specify Snackbar options

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Theming/Examples/ThemingBodyOptions.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Theming/ThemingPage.razor
Documentation/Blazorise.Docs/Pages/News/2024-07-15-release-notes-160.razor
Source/Blazorise/Themes/Options/ThemeBodyOptions.cs
Source/Blazorise/Themes/Options/ThemeFontOptions.cs
Source/Blazorise/Themes/Options/ThemeVariables.cs
Source/Blazorise/Themes/ThemeGenerator.cs

Theme: add FontOptions on ThemeBody

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/ChartDataLabels/ChartDataLabelsPage.razor

DataLabel: fix typo in documentation

---

Source/Blazorise.Bootstrap5/Components/FileEdit.razor

FileEdit: don't show selected files on pick button

---

Source/Blazorise.Bulma/Config.cs
Source/Blazorise.FluentUI2/Config.cs

Targetting v1.5, don't forget to pull this to v1.6

Bulma & FluentUI: Register IThemeGenerator as scoped

---

Source/Blazorise.Bulma/Components/NumericEdit.razor
Source/Blazorise.FluentUI2/Components/NumericEdit.razor
Source/Blazorise/Components/NumericEdit/NumericEdit.razor
Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs

There was already a `minDefined` and a `maxDefined`.

NumericEdit: Assign html attributes min and max if user has assigned

---

Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor

I know know, it all feels hacky, but the whole multiple select feature is quite hacky haha.
So `ClickStopPropagation="@(ParentDataGrid.MultiSelectColumn?.PreventRowClick ?? false)"` makes it so clicking around the checkbox stops the click from propagating.
Since in this case the click is stopped from propagating. When the user actually clicks the checkbox, then we use the `OnMultiSelectCheckClicked` to still identify that we have a check click and invoke the `HandleClick` manually.
Since the `HandleClick` is important to be maintained we just added a `multiSelectPreventRowClick` that avoids triggering the `DetailRow`, everything else seems ok to run.
```
@page "/tests/datagrid/selection/multiple"
<Row>
<Column>
<Card Margin="Margin.Is4.OnY">
<CardHeader>
<CardTitle>Datagrid: Multiple …
```

DataGridRowMultiSelect: Honor PreventRowClick

---

Documentation/Blazorise.Docs/Pages/Docs/Components/Links/LinkPage.razor
Source/Blazorise/Base/BaseLinkComponent.cs
Source/Blazorise/Components/Bar/BarLink.razor.cs
Source/Blazorise/Enums/Match.cs
Source/Extensions/Blazorise.Sidebar/SidebarLink.razor.cs

Closes #5580
There is no need for special release notes as we will just point to the changelog for full details of 1.7.

Link: Make CustomMatch enough to match the URL

---

Source/Blazorise/Components/NumericPicker/NumericPicker.razor.cs
Source/Blazorise/wwwroot/numericPicker.js

NumericPicker: fix stepper with keyboard

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/Code/ValidationIValidatableObjectExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/Examples/ValidationIValidatableObjectExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/ValidationPage.razor

Docs: IValidatableObject example

---

Source/Extensions/Blazorise.Charts/Options/ChartAxisTime.cs

Chart: Fix DisplayFormats property name

---

Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/DataGridApi.razor
Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridAggregateRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowCommand.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowEdit.razor
Source/Extensions/Blazorise.DataGrid/_DataGridRowMultiSelect.razor

Closes #5656
The original ticket only mentioned TextOverflow. But, I have also added all other parameters related to text stylings. I have covered display cell, filter, header, and aggregate cells.

DataGrid: add text styling parameters

---

Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor
Source/Extensions/Blazorise.DataGrid/DataGridColumn.cs
Source/Extensions/Blazorise.DataGrid/_DataGridRow.razor.cs

DataGridColumn: Undeprecate CellClass and CellStyle

---

Demos/Blazorise.Demo/Pages/Tests/VideoPage.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Video/VideoApi.razor
Documentation/Blazorise.Docs/Pages/News/2024-10-15-release-notes-170.razor
Source/Extensions/Blazorise.Video/JSVideoModule.cs
Source/Extensions/Blazorise.Video/Video.razor.cs
Source/Extensions/Blazorise.Video/wwwroot/video.js

Video: add SetPlaybackRate method

---

Documentation/Blazorise.Docs/Components/TopMenuEnd.razor

second try on https://github.com/Megabit/Blazorise/pull/5789

Web: fix the wrapping text in the top menu

---

Documentation/Blazorise.Docs/Services/CssProvidersService.cs

Docs: Broken links on FluentUI 

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/VirtualizeExternalSourcePage.razor
Demos/Blazorise.Demo/Pages/Tests/DataGrid/VirtualizeInMemoryPage.razor

dotnet run / local browser
- [ x] Bug fix (non-breaking change which fixes an issue)
(for sample code)
- [ x] The PR is submitted to the correct branch (`master` for dev, `rel-1.x` for maintenance).
- [x ] My code follows the code style of this project.

Demos: Remove duplicate EmployeeData.Genders column

---

Source/Blazorise/ComponentActivator.cs

ComponentActivator: fix for parameterless constructor

---

Documentation/Blazorise.Docs/Pages/Docs/Guides/AntDesign/Examples/AntDesignGuideSourceFilesExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/Bootstrap/Examples/BootstrapGuideSourceFilesExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/Bootstrap5/Examples/Bootstrap5GuideSourceFilesExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/Bulma/Examples/BulmaGuideSourceFilesExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/FluentUI2/Examples/FluentUI2GuideSourceFiles1Example.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/Material/Examples/MaterialGuideSourceFilesExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/Tailwind/Examples/TailwindGuideSourceFiles1Example.snippet
Documentation/Blazorise.Docs/Pages/Docs/Guides/Tailwind/Examples/TailwindGuideSourceFiles3Example.snippet

Docs: Adds version number to all Blazorise resources in examples

---

Documentation/Blazorise.Docs.Compiler/ApiDocsGenerator/ComponentsApiDocsGenerator.cs
Documentation/Blazorise.Docs.Compiler/ApiDocsGenerator/Helpers/StringHelpers.cs

Docs: Generic types for component names without <TValue>

---

Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete: OrdinalIgnoreCase on string comparison

---

Source/Blazorise/wwwroot/colorPicker.js

ColorPicker: fix default null color

---

Documentation/Blazorise.Docs.Compiler/ApiDocsGenerator/ComponentsApiDocsGenerator.cs
Documentation/Blazorise.Docs.Compiler/ApiDocsGenerator/Extensions/EnumerableExtensions.cs

Docs: check for null on namespace on API docs generator

---

Documentation/Blazorise.Docs/Pages/News/2025-05-01-release-notes-200.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete: string comparison method as parameter

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Services/ToastProvider/Code/ToastProviderHideIconExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Services/ToastProvider/Examples/ToastProviderHideIconExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Services/ToastProvider/ToastProviderPage.razor
Documentation/Blazorise.Docs/Pages/News/2025-05-01-release-notes-200.razor
Source/Blazorise/Components/Toast/ToastInstance.cs
Source/Blazorise/Components/ToastProvider/ToastProvider.razor
Source/Blazorise/Components/ToastProvider/ToastProvider.razor.cs
Source/Blazorise/Models/ToastInstanceOptions.cs

Closes #5922 
- adds `ToastStyle`, `ToastClass` and `IconName` to

ToastProvider: Styling customizations

---

Source/Extensions/Blazorise.Video/wwwroot/video.js

Video: use media-seeking-request for seeking event

---

Source/Blazorise.FluentUI2/Components/BarToggler.razor

BarToggler: fix spacing for FluentUI2 provider

---

Demos/Blazorise.Demo/Pages/Tests/DataGrid/EditingBatchEdit.razor
Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

DataGrid: Removes new rows created when BatchEdit enabled and operation canceled

---

Source/Blazorise/Components/Dropdown/DropdownItem.razor

Closes https://blazorise.com/support/issues/267/unexpected-cursor-and-click-behaviour-in-autocomplete

Autocomplete: add cursor pointer to checkbox

---

Source/Blazorise.Bootstrap5/Components/Carousel.razor

Carousel: fix BS5 indicators

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Code/DataGridCustomColumnFilteringExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Examples/DataGridCustomColumnFilteringExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Extensions/DataGrid/Features/FilteringPage.razor

Closes #5612
Custom column and custom filter on the column with usage of `FilterTemplate` as requested in the issue.

Docs: Update DataGrid custom column filtering example

---

Shared/Blazorise.Shared/Data/PageEntryData.cs

Docs: Add file picker to the search

---

Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete: add ItemDisabled API

---

Source/Blazorise/Components/Field/FieldLabel.razor.cs

FieldLabel: RequiredIndicator are reflected correctly

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Validations/Code/GlobalLocalizationExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/Code/FontAwesomeNugetInstallExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/Code/IconsNugetInstallExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/Examples/FontAwesomeNugetInstallExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/Examples/IconsNugetInstallExample.snippet
Documentation/Blazorise.Docs/Pages/Docs/Extensions/Icons/IconsPage.razor

Docs: improve Icons page

---

Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Components/Times/Code/TimePickerIncrementsExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Components/Times/Examples/TimePickerIncrementsExample.razor
Documentation/Blazorise.Docs/Pages/Docs/Components/Times/TimePickerPage.razor
Documentation/Blazorise.Docs/Pages/News/2025-03-10-release-notes-180.razor
Source/Blazorise/Components/TimePicker/TimePicker.razor.cs
Source/Blazorise/Modules/JSOptions/TimePickerJSOptions.cs
Source/Blazorise/wwwroot/timePicker.js

Closes #6066
\+ docs and release notes

TimePicker: add HourIncrement and MinuteIncrement

---

Source/Blazorise/wwwroot/floatingUi.js

Closes #6079
based on https://floating-ui.com/docs/hide#hide

Dropdown: add `hide` middleware to floatingUi for hiding when scrolling

---

Source/Blazorise.Bootstrap5/Providers/Bootstrap5ClassProvider.cs

Badge: change BS5 classnames of background colors

---

Source/Blazorise/Components/Badge/Badge.razor.cs

Autocomplete: fix disabled color for Badge close button

---

Source/Blazorise/Components/DatePicker/DatePicker.razor.cs

DatePicker: Clarify behavior when updating Min and Max date constraints

---

Source/Blazorise.AntDesign/Providers/AntDesignThemeGenerator.cs
Source/Blazorise.Bootstrap/Providers/BootstrapThemeGenerator.cs
Source/Blazorise.Bootstrap5/Providers/Bootstrap5ThemeGenerator.cs
Source/Blazorise.Bulma/Providers/BulmaThemeGenerator.cs

ThemeGenerator: fix string conversion of DisabledOpacity

---

Source/Blazorise/Components/ToastProvider/ToastProvider.razor

ToastProvider: propagate all parameters to Toaster

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs
Tests/Blazorise.Tests/Components/DataGridComponentTest.cs

DataGrid: DeepClone item before and after the update

---

Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs

Solves https://github.com/Megabit/Blazorise/pull/6126#issuecomment-2916550269
I just removed few lines. It does the same thing still.

DataGrid: simplifies OnColumnDropped method

---

Source/Blazorise.Bootstrap5/Providers/Bootstrap5ThemeGenerator.cs

ThemeGenerator: fix BS5 badge colors

---

Demos/Blazorise.Demo/Components/TopMenu.razor
Source/Blazorise.AntDesign/Components/BarDropdownItem.razor
Source/Blazorise.AntDesign/Providers/AntDesignClassProvider.cs
Source/Blazorise.Bootstrap/Providers/BootstrapClassProvider.cs
Source/Blazorise.Bootstrap5/Providers/Bootstrap5ClassProvider.cs
Source/Blazorise.Bulma/Providers/BulmaClassProvider.cs
Source/Blazorise.FluentUI2/Components/BarDropdownItem.razor
Source/Blazorise.FluentUI2/Providers/FluentUI2ClassProvider.cs
Source/Blazorise.Tailwind/Components/BarDropdownItem.razor
Source/Blazorise.Tailwind/Components/_BarOnlyLink.razor
Source/Blazorise.Tailwind/Providers/TailwindClassProvider.cs
Source/Blazorise/Components/Bar/BarDropdownItem.razor
Source/Blazorise/Components/Bar/BarDropdownItem.razor.cs
Source/Blazorise/Interfaces/IClassProvider.cs
Source/Blazorise/Providers/ClassProvider.cs
Source/Blazorise/Providers/EmptyClassProvider.cs

BarDropdownItem: add Disabled parameter

---

Source/Extensions/Blazorise.Splitter/JSSplitModule.cs
Source/Extensions/Blazorise.Splitter/Splitter.razor.cs
Source/Extensions/Blazorise.Splitter/wwwroot/blazorise.splitter.js

Splitter: fix dispose logic

---

Source/Blazorise.AntDesign/Components/BarDropdownItem.razor
Source/Blazorise.FluentUI2/Components/BarDropdownItem.razor
Source/Blazorise.Tailwind/Components/BarDropdownItem.razor
Source/Blazorise/Components/Bar/BarDropdownItem.razor
Source/Blazorise/Components/Bar/BarDropdownItem.razor.cs

BarDropdownItem: add CustomMatch parameter

---

Demos/Blazorise.Demo/Pages/Tests/ServicesPage.razor
Documentation/Blazorise.Docs/Models/Snippets.generated.cs
Documentation/Blazorise.Docs/Pages/Docs/Services/Notifications/Code/NotificationServiceWithOptionsExampleCode.html
Documentation/Blazorise.Docs/Pages/Docs/Services/Notifications/Examples/NotificationServiceWithOptionsExample.razor
Source/Blazorise/Models/NotificationOptions.cs
Source/Extensions/Blazorise.Components/NotificationAlert.razor.cs
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor
Source/Extensions/Blazorise.Snackbar/SnackbarStack.razor.cs

NotificationOptions: add missing ShowOkButton property

---

Source/Blazorise.Bootstrap5/Providers/Bootstrap5ThemeGenerator.cs

Badge: fix close button theme color

---

Source/Extensions/Blazorise.PdfViewer/wwwroot/pdfviewer.js

PdfViewer: fix invalid worker path

---

Source/Blazorise/Components/Validation/ValidationRule.cs

Validation: improve email validation regex

---

Source/Extensions/Blazorise.Components/TransferList.razor

TransferList: fix callbacks for Start and End items

---

Source/Extensions/Blazorise.Icons.Material/MaterialIconProvider.cs

Material Icons: fix filter icon

---

Source/Extensions/Blazorise.Components/Autocomplete.razor
Source/Extensions/Blazorise.Components/Autocomplete.razor.cs

Autocomplete: fix the incomplete menu closing
